import type {Request}from"express";import{prisma}from"../db/prisma.js";import{writeAudit}from"./audit.service.js";import{ApiError,booleanValue,cleanString,numberValue,plain,requireText,roundMoney}from"../utils/http.js";
function tier(points:number){if(points>=10000)return"Platinum";if(points>=5000)return"Gold";if(points>=1000)return"Silver";return"Bronze"}
export async function getProgram(businessId:string){let p=await prisma.loyaltyProgram.findFirst({where:{businessId,active:true},orderBy:{createdAt:"asc"}});if(!p)p=await prisma.loyaltyProgram.create({data:{businessId,name:"Default Loyalty Program",pointsPerCurrency:1,redemptionRate:.01,active:true}});return plain(p);}
export async function saveProgram(req:Request,businessId:string,userId:string|null,input:any){const existing=await prisma.loyaltyProgram.findFirst({where:{businessId,active:true}});return prisma.$transaction(async tx=>{const row=existing?await tx.loyaltyProgram.update({where:{id:existing.id},data:{name:cleanString(input.name),pointsPerCurrency:input.pointsPerCurrency===undefined?undefined:numberValue(input.pointsPerCurrency,1),redemptionRate:input.redemptionRate===undefined?undefined:numberValue(input.redemptionRate,.01),rules:input.rules===undefined?undefined:input.rules,active:input.active===undefined?undefined:booleanValue(input.active)}}):await tx.loyaltyProgram.create({data:{businessId,name:cleanString(input.name)||"Default Loyalty Program",pointsPerCurrency:numberValue(input.pointsPerCurrency,1),redemptionRate:numberValue(input.redemptionRate,.01),rules:input.rules,active:booleanValue(input.active,true)}});await writeAudit(tx,req,{businessId,userId,action:"loyalty.program.save",entityType:"LoyaltyProgram",entityId:row.id,before:existing||undefined,after:row});return plain(row);});}
export async function listAccounts(businessId:string,q:any={}){const rows=await prisma.loyaltyAccount.findMany({where:{businessId,...(cleanString(q.search)?{customerName:{contains:cleanString(q.search),mode:"insensitive"}}:{})},orderBy:[{points:"desc"},{customerName:"asc"}]});const total=rows.reduce((a,r)=>a+Number(r.points),0);return{accounts:plain(rows),totalPoints:roundMoney(total),members:rows.length};}
async function resolveCustomer(tx:any,businessId:string,input:any){const customerId=cleanString(input.customerId)||null;if(customerId){const c=await tx.customer.findFirst({where:{id:customerId,businessId}});if(!c)throw new ApiError(404,"Customer not found");return{id:c.id,name:c.name}}return{id:null,name:requireText(input.customerName,"Customer")}}
async function change(req:Request,businessId:string,userId:string|null,input:any,kind:"earn"|"redeem"|"adjust"){const amount=Math.abs(numberValue(input.amount)),rawPoints=Math.abs(numberValue(input.points));return prisma.$transaction(async tx=>{const c=await resolveCustomer(tx,businessId,input);const program=await tx.loyaltyProgram.findFirst({where:{businessId,active:true},orderBy:{createdAt:"asc"}});const rate=Number(program?.pointsPerCurrency||1),redemption=Number(program?.redemptionRate||.01);let points=rawPoints||roundMoney(amount*(kind==="redeem"?(redemption>0?1/redemption:100):rate));if(points<=0)throw new ApiError(400,"Points or amount must be greater than zero");let account=await tx.loyaltyAccount.findFirst({where:{businessId,customerId:c.id}});if(!account&&c.id===null)account=await tx.loyaltyAccount.findFirst({where:{businessId,customerName:c.name}});if(!account)account=await tx.loyaltyAccount.create({data:{businessId,customerId:c.id,customerName:c.name,points:0,tier:"Bronze"}});const current=Number(account.points),delta=kind==="redeem"?-points:(kind==="adjust"&&numberValue(input.points)<0?-points:points);if(current+delta<0)throw new ApiError(409,"Insufficient loyalty points");const next=roundMoney(current+delta),updated=await tx.loyaltyAccount.update({where:{id:account.id},data:{points:next,tier:tier(next),customerName:c.name}});const ledger=await tx.loyaltyLedger.create({data:{businessId,customerId:c.id,customerName:c.name,type:kind,points:delta,value:kind==="redeem"?roundMoney(points*redemption):amount,referenceNo:cleanString(input.referenceNo),notes:cleanString(input.notes)}});await writeAudit(tx,req,{businessId,userId,action:`loyalty.${kind}`,entityType:"LoyaltyLedger",entityId:ledger.id,after:ledger});return{account:plain(updated),ledger:plain(ledger)};});}
export const earn=(req:Request,b:string,u:string|null,i:any)=>change(req,b,u,i,"earn");export const redeem=(req:Request,b:string,u:string|null,i:any)=>change(req,b,u,i,"redeem");export const adjust=(req:Request,b:string,u:string|null,i:any)=>change(req,b,u,i,"adjust");
export async function ledger(businessId:string,q:any={}){const rows=await prisma.loyaltyLedger.findMany({where:{businessId,...(cleanString(q.customerId)?{customerId:cleanString(q.customerId)}:{})},orderBy:{createdAt:"desc"},take:250});return plain(rows);}
