import type { Request,Response } from "express";
import { prisma } from "../db/prisma.js";
const db:any=prisma; const bid=(r:Request)=>r.tenant!.businessId; const key=(r:Request)=>r.header("Idempotency-Key")||null;
const ok=(res:Response,data:any,status=200)=>res.status(status).json({ok:true,data}); const fail=(res:Response,message:string,status=400)=>res.status(status).json({ok:false,error:{message}});
const owned=async(model:string,businessId:string,id:string)=>db[model].findFirst({where:{id,businessId}});

export async function furnitureDashboard(r:Request,res:Response){const b=bid(r);const [orders,production,deliveries,balance]=await Promise.all([db.furnitureCustomOrder.count({where:{businessId:b,status:{notIn:["completed","cancelled"]}}}),db.furnitureProductionStage.count({where:{businessId:b,status:"in_progress"}}),db.furnitureDelivery.count({where:{businessId:b,status:"scheduled"}}),db.furnitureCustomOrder.aggregate({where:{businessId:b,status:{not:"cancelled"}},_sum:{balance:true}})]);return ok(res,{openOrders:orders,inProduction:production,scheduledDeliveries:deliveries,outstandingBalance:Number(balance._sum.balance||0)});}
export async function furnitureOrders(r:Request,res:Response){return ok(res,await db.furnitureCustomOrder.findMany({where:{businessId:bid(r)},orderBy:{createdAt:"desc"},take:100}));}
export async function furnitureOrderCreate(r:Request,res:Response){const b=bid(r),x=r.body,k=key(r);if(!x.customerId||!x.description)return fail(res,"Customer and description are required");if(!await owned("customer",b,x.customerId))return fail(res,"Customer not found",404);if(k){const old=await db.furnitureCustomOrder.findFirst({where:{businessId:b,idempotencyKey:k}});if(old)return ok(res,old);}const quoted=Math.max(0,Number(x.quotedAmount||0)),deposit=Math.max(0,Number(x.depositRequired||0));const order=await db.$transaction(async(tx:any)=>{const o=await tx.furnitureCustomOrder.create({data:{businessId:b,orderNo:`FUR-${Date.now()}`,customerId:x.customerId,productId:x.productId||null,description:String(x.description),quotedAmount:quoted,depositRequired:deposit,balance:quoted,expectedAt:x.expectedAt?new Date(x.expectedAt):null,idempotencyKey:k}});for(const [i,name] of ["Design","Cutting","Assembly","Finishing","Packing"].entries())await tx.furnitureProductionStage.create({data:{businessId:b,customOrderId:o.id,stageName:name,sequence:i+1}});return o;});return ok(res,order,201);}
export async function furnitureMeasurements(r:Request,res:Response){const b=bid(r),x=r.body;if(!await owned("furnitureCustomOrder",b,r.params.id))return fail(res,"Order not found",404);if(!x.measurementKey||Number(x.measurementValue)<0)return fail(res,"Valid measurement is required");return ok(res,await db.furnitureMeasurement.create({data:{businessId:b,customOrderId:r.params.id,measurementKey:x.measurementKey,measurementValue:Number(x.measurementValue),unit:x.unit||"cm",notes:x.notes||null}}),201);}
export async function furnitureStageUpdate(r:Request,res:Response){const b=bid(r),x=r.body;if(!["pending","in_progress","completed","blocked"].includes(x.status))return fail(res,"Invalid stage status");const row=await db.furnitureProductionStage.findFirst({where:{id:r.params.id,businessId:b}});if(!row)return fail(res,"Stage not found",404);const data:any={status:x.status,assignedTo:x.assignedTo||row.assignedTo,notes:x.notes??row.notes};if(x.status==="in_progress"&&!row.startedAt)data.startedAt=new Date();if(x.status==="completed")data.completedAt=new Date();return ok(res,await db.furnitureProductionStage.update({where:{id:row.id},data}));}
export async function furniturePayment(r:Request,res:Response){const b=bid(r),x=r.body,k=key(r),amount=Number(x.amount||0);if(amount<=0)return fail(res,"Positive amount required");const order=await owned("furnitureCustomOrder",b,r.params.id);if(!order)return fail(res,"Order not found",404);if(amount>Number(order.balance))return fail(res,"Payment exceeds balance",409);if(k){const old=await db.furniturePayment.findFirst({where:{businessId:b,idempotencyKey:k}});if(old)return ok(res,old);}const p=await db.$transaction(async(tx:any)=>{const payment=await tx.furniturePayment.create({data:{businessId:b,customOrderId:order.id,amount,paymentType:x.paymentType||"installment",method:x.method||"cash",reference:x.reference||null,idempotencyKey:k}});await tx.furnitureCustomOrder.update({where:{id:order.id},data:{balance:{decrement:amount},status:Number(order.balance)-amount<=0?"paid":order.status}});return payment;});return ok(res,p,201);}
export async function furnitureDeliveryCreate(r:Request,res:Response){const b=bid(r),x=r.body;if(!await owned("furnitureCustomOrder",b,x.customOrderId))return fail(res,"Order not found",404);return ok(res,await db.furnitureDelivery.create({data:{businessId:b,customOrderId:x.customOrderId,scheduledAt:new Date(x.scheduledAt),vehicleReference:x.vehicleReference||null,driverName:x.driverName||null}}),201);}

export async function workshopDashboard(r:Request,res:Response){const b=bid(r);const [vehicles,jobs,approval,bays]=await Promise.all([db.workshopVehicle.count({where:{businessId:b,active:true}}),db.workshopJobCard.count({where:{businessId:b,status:{in:["open","in_progress","quality_check"]}}}),db.workshopEstimate.count({where:{businessId:b,status:"awaiting_approval"}}),db.workshopBay.count({where:{businessId:b,active:true}})]);return ok(res,{vehicles,openJobs:jobs,awaitingApproval:approval,serviceBays:bays});}
export async function workshopVehicles(r:Request,res:Response){return ok(res,await db.workshopVehicle.findMany({where:{businessId:bid(r)},orderBy:{createdAt:"desc"},take:100}));}
export async function workshopVehicleCreate(r:Request,res:Response){const b=bid(r),x=r.body;if(!x.customerId||!x.registrationNo||!x.make||!x.model)return fail(res,"Customer, registration, make and model are required");if(!await owned("customer",b,x.customerId))return fail(res,"Customer not found",404);return ok(res,await db.workshopVehicle.create({data:{businessId:b,customerId:x.customerId,registrationNo:x.registrationNo,vin:x.vin||null,make:x.make,model:x.model,modelYear:x.modelYear?Number(x.modelYear):null,mileage:Number(x.mileage||0)}}),201);}
export async function workshopInspectionCreate(r:Request,res:Response){const b=bid(r),x=r.body;if(!await owned("workshopVehicle",b,x.vehicleId))return fail(res,"Vehicle not found",404);const ins=await db.$transaction(async(tx:any)=>{const h=await tx.workshopInspection.create({data:{businessId:b,vehicleId:x.vehicleId,inspectionNo:`INS-${Date.now()}`,mileage:Number(x.mileage||0),fuelLevel:x.fuelLevel||null,notes:x.notes||null}});if(Array.isArray(x.items)&&x.items.length)await tx.workshopInspectionItem.createMany({data:x.items.map((i:any)=>({businessId:b,inspectionId:h.id,itemName:String(i.itemName),condition:String(i.condition||"ok"),notes:i.notes||null}))});return h;});return ok(res,ins,201);}
export async function workshopEstimateCreate(r:Request,res:Response){const b=bid(r),x=r.body,k=key(r),items=Array.isArray(x.items)?x.items:[];if(!await owned("workshopVehicle",b,x.vehicleId)||!items.length)return fail(res,"Vehicle and estimate items are required");if(k){const old=await db.workshopEstimate.findFirst({where:{businessId:b,idempotencyKey:k}});if(old)return ok(res,old);}const subtotal=items.reduce((s:number,i:any)=>s+Number(i.quantity||1)*Number(i.unitPrice||0),0),tax=Math.max(0,Number(x.tax||0));const e=await db.$transaction(async(tx:any)=>{const h=await tx.workshopEstimate.create({data:{businessId:b,estimateNo:`EST-${Date.now()}`,vehicleId:x.vehicleId,subtotal,tax,total:subtotal+tax,idempotencyKey:k,status:"awaiting_approval"}});await tx.workshopEstimateItem.createMany({data:items.map((i:any)=>({businessId:b,estimateId:h.id,itemType:i.itemType||"labour",description:String(i.description),quantity:Number(i.quantity||1),unitPrice:Number(i.unitPrice||0),lineTotal:Number(i.quantity||1)*Number(i.unitPrice||0)}))});return h;});return ok(res,e,201);}
export async function workshopJobCreate(r:Request,res:Response){const b=bid(r),x=r.body,k=key(r);const vehicle=await owned("workshopVehicle",b,x.vehicleId);if(!vehicle)return fail(res,"Vehicle not found",404);if(x.technicianId&&!await owned("workshopTechnician",b,x.technicianId))return fail(res,"Technician not found",404);if(x.bayId){if(!await owned("workshopBay",b,x.bayId))return fail(res,"Bay not found",404);const conflict=await db.workshopJobCard.findFirst({where:{businessId:b,bayId:x.bayId,status:{in:["open","in_progress"]}}});if(conflict)return fail(res,"Service bay already assigned",409);}if(k){const old=await db.workshopJobCard.findFirst({where:{businessId:b,idempotencyKey:k}});if(old)return ok(res,old);}return ok(res,await db.workshopJobCard.create({data:{businessId:b,jobNo:`JOB-${Date.now()}`,vehicleId:x.vehicleId,estimateId:x.estimateId||null,technicianId:x.technicianId||null,bayId:x.bayId||null,priority:x.priority||"normal",promisedAt:x.promisedAt?new Date(x.promisedAt):null,idempotencyKey:k}}),201);}
export async function workshopJobs(r:Request,res:Response){return ok(res,await db.workshopJobCard.findMany({where:{businessId:bid(r)},orderBy:{createdAt:"desc"},take:100}));}

export async function wholesaleDashboard(r:Request,res:Response){const b=bid(r);const [orders,picks,dispatches,backorders]=await Promise.all([db.wholesaleSalesOrder.count({where:{businessId:b,status:{notIn:["delivered","cancelled"]}}}),db.wholesalePickList.count({where:{businessId:b,status:{not:"completed"}}}),db.wholesaleDispatch.count({where:{businessId:b,status:{in:["planned","dispatched"]}}}),db.wholesaleBackorder.count({where:{businessId:b,status:"open"}})]);return ok(res,{openOrders:orders,openPickLists:picks,activeDispatches:dispatches,backorders});}
export async function wholesalePriceLists(r:Request,res:Response){return ok(res,await db.wholesalePriceList.findMany({where:{businessId:bid(r),active:true}}));}
export async function wholesalePriceListCreate(r:Request,res:Response){if(!r.body.name)return fail(res,"Price-list name required");return ok(res,await db.wholesalePriceList.create({data:{businessId:bid(r),name:r.body.name,currency:r.body.currency||"USD"}}),201);}
export async function wholesaleOrders(r:Request,res:Response){return ok(res,await db.wholesaleSalesOrder.findMany({where:{businessId:bid(r)},orderBy:{createdAt:"desc"},take:100}));}
export async function wholesaleOrderCreate(r:Request,res:Response){const b=bid(r),x=r.body,k=key(r),items=Array.isArray(x.items)?x.items:[];if(!x.customerId||!items.length)return fail(res,"Customer and items required");if(!await owned("customer",b,x.customerId))return fail(res,"Customer not found",404);if(k){const old=await db.wholesaleSalesOrder.findFirst({where:{businessId:b,idempotencyKey:k}});if(old)return ok(res,old);}const subtotal=items.reduce((s:number,i:any)=>s+Number(i.quantity||0)*Number(i.unitPrice||0),0),discount=Math.max(0,Number(x.discount||0));const o=await db.$transaction(async(tx:any)=>{const h=await tx.wholesaleSalesOrder.create({data:{businessId:b,orderNo:`WSO-${Date.now()}`,customerId:x.customerId,customerPo:x.customerPo||null,territory:x.territory||null,subtotal,discount,total:Math.max(0,subtotal-discount),requestedDeliveryAt:x.requestedDeliveryAt?new Date(x.requestedDeliveryAt):null,idempotencyKey:k,status:"confirmed"}});await tx.wholesaleSalesOrderItem.createMany({data:items.map((i:any)=>({businessId:b,salesOrderId:h.id,productId:i.productId,description:String(i.description),quantity:Number(i.quantity),unit:i.unit||"unit",unitPrice:Number(i.unitPrice),lineTotal:Number(i.quantity)*Number(i.unitPrice)}))});return h;});return ok(res,o,201);}
export async function wholesaleAllocate(r:Request,res:Response){const b=bid(r),order=await owned("wholesaleSalesOrder",b,r.params.id);if(!order)return fail(res,"Sales order not found",404);const items=await db.wholesaleSalesOrderItem.findMany({where:{businessId:b,salesOrderId:order.id}});const pick=await db.$transaction(async(tx:any)=>{const p=await tx.wholesalePickList.create({data:{businessId:b,pickNo:`PICK-${Date.now()}`,salesOrderId:order.id,assignedTo:r.body.assignedTo||null}});for(const i of items){const available=Math.max(0,Number(r.body.available?.[i.productId]??i.quantity));const allocated=Math.min(Number(i.quantity),available);await tx.wholesaleSalesOrderItem.update({where:{id:i.id},data:{allocatedQuantity:allocated}});await tx.wholesalePickListItem.create({data:{businessId:b,pickListId:p.id,salesOrderItemId:i.id,requestedQuantity:i.quantity,pickedQuantity:0}});if(allocated<Number(i.quantity))await tx.wholesaleBackorder.create({data:{businessId:b,salesOrderItemId:i.id,quantity:Number(i.quantity)-allocated}});}await tx.wholesaleSalesOrder.update({where:{id:order.id},data:{status:"allocated"}});return p;});return ok(res,pick,201);}
export async function wholesaleDispatchCreate(r:Request,res:Response){const b=bid(r),x=r.body;if(!await owned("wholesaleSalesOrder",b,x.salesOrderId))return fail(res,"Sales order not found",404);return ok(res,await db.wholesaleDispatch.create({data:{businessId:b,dispatchNo:`DSP-${Date.now()}`,salesOrderId:x.salesOrderId,routeName:x.routeName||null,driverName:x.driverName||null,vehicleReference:x.vehicleReference||null}}),201);}

export async function furnitureApprovalCreate(r:Request,res:Response){const b=bid(r),x=r.body,order=await owned("furnitureCustomOrder",b,r.params.id);if(!order)return fail(res,"Order not found",404);const latest=await db.furnitureApproval.findFirst({where:{businessId:b,customOrderId:order.id},orderBy:{revision:"desc"}});const revision=Number(latest?.revision||0)+1;const row=await db.$transaction(async(tx:any)=>{const a=await tx.furnitureApproval.create({data:{businessId:b,customOrderId:order.id,status:x.status||"approved",revision,approvedBy:x.approvedBy||null,notes:x.notes||null,approvedAt:(x.status||"approved")==="approved"?new Date():null}});await tx.furnitureCustomOrder.update({where:{id:order.id},data:{status:a.status==="approved"?"approved":order.status,approvedAt:a.status==="approved"?new Date():order.approvedAt,revision:{increment:1}}});return a;});return ok(res,row,201);}
export async function furnitureInstallationCreate(r:Request,res:Response){const b=bid(r),x=r.body;if(!await owned("furnitureDelivery",b,x.deliveryId))return fail(res,"Delivery not found",404);return ok(res,await db.furnitureInstallation.create({data:{businessId:b,deliveryId:x.deliveryId,scheduledAt:new Date(x.scheduledAt),technicianName:x.technicianName||null,notes:x.notes||null}}),201);}
export async function furnitureInstallationComplete(r:Request,res:Response){const b=bid(r),row=await owned("furnitureInstallation",b,r.params.id);if(!row)return fail(res,"Installation not found",404);return ok(res,await db.furnitureInstallation.update({where:{id:row.id},data:{status:"completed",completedAt:new Date(),notes:r.body.notes??row.notes}}));}
export async function furnitureWarrantyClaimCreate(r:Request,res:Response){const b=bid(r),x=r.body;if(!await owned("furnitureWarranty",b,x.warrantyId))return fail(res,"Warranty not found",404);if(!x.issue)return fail(res,"Issue is required");return ok(res,await db.furnitureWarrantyClaim.create({data:{businessId:b,warrantyId:x.warrantyId,claimNo:`FWC-${Date.now()}`,issue:String(x.issue)}}),201);}
export async function furnitureReports(r:Request,res:Response){const b=bid(r);const [orders,stages,claims,payments]=await Promise.all([db.furnitureCustomOrder.groupBy({by:["status"],where:{businessId:b},_count:{_all:true}}),db.furnitureProductionStage.groupBy({by:["status"],where:{businessId:b},_count:{_all:true}}),db.furnitureWarrantyClaim.groupBy({by:["status"],where:{businessId:b},_count:{_all:true}}),db.furniturePayment.aggregate({where:{businessId:b},_sum:{amount:true}})]);return ok(res,{orders,productionStages:stages,warrantyClaims:claims,totalPayments:Number(payments._sum.amount||0)});}

export async function workshopPartReserve(r:Request,res:Response){const b=bid(r),x=r.body,k=key(r);if(!await owned("workshopJobCard",b,r.params.id))return fail(res,"Job card not found",404);if(!await owned("product",b,x.productId))return fail(res,"Product not found",404);if(Number(x.quantity)<=0)return fail(res,"Positive quantity required");if(k){const old=await db.workshopPartReservation.findFirst({where:{businessId:b,idempotencyKey:k}});if(old)return ok(res,old);}return ok(res,await db.workshopPartReservation.create({data:{businessId:b,jobCardId:r.params.id,productId:x.productId,quantity:Number(x.quantity),idempotencyKey:k}}),201);}
export async function workshopQualityCheckCreate(r:Request,res:Response){const b=bid(r),x=r.body,job=await owned("workshopJobCard",b,r.params.id);if(!job)return fail(res,"Job card not found",404);if(!["passed","failed","rework"].includes(x.result))return fail(res,"Invalid quality result");const q=await db.$transaction(async(tx:any)=>{const row=await tx.workshopQualityCheck.create({data:{businessId:b,jobCardId:job.id,result:x.result,checklist:x.checklist||null,notes:x.notes||null,checkedBy:x.checkedBy||null}});await tx.workshopJobCard.update({where:{id:job.id},data:{status:x.result==="passed"?"completed":x.result==="rework"?"in_progress":"quality_check",completedAt:x.result==="passed"?new Date():null}});return row;});return ok(res,q,201);}
export async function workshopInvoiceCreate(r:Request,res:Response){const b=bid(r),x=r.body,k=key(r),job=await owned("workshopJobCard",b,r.params.id);if(!job)return fail(res,"Job card not found",404);if(k){const old=await db.workshopInvoice.findFirst({where:{businessId:b,idempotencyKey:k}});if(old)return ok(res,old);}const estimate=job.estimateId?await owned("workshopEstimate",b,job.estimateId):null;const part=await db.workshopPartUsage.aggregate({where:{businessId:b,jobCardId:job.id},_sum:{unitCost:true}});const total=Math.max(0,Number(x.total??estimate?.total??part._sum.unitCost??0));return ok(res,await db.workshopInvoice.create({data:{businessId:b,jobCardId:job.id,invoiceNo:`WINV-${Date.now()}`,total,balance:total,idempotencyKey:k}}),201);}
export async function workshopPaymentCreate(r:Request,res:Response){const b=bid(r),x=r.body,k=key(r),amount=Number(x.amount||0),invoice=await owned("workshopInvoice",b,r.params.id);if(!invoice)return fail(res,"Invoice not found",404);if(amount<=0||amount>Number(invoice.balance))return fail(res,"Invalid payment amount",409);if(k){const old=await db.workshopPayment.findFirst({where:{businessId:b,idempotencyKey:k}});if(old)return ok(res,old);}const p=await db.$transaction(async(tx:any)=>{const row=await tx.workshopPayment.create({data:{businessId:b,invoiceId:invoice.id,amount,method:x.method||"cash",reference:x.reference||null,idempotencyKey:k}});const balance=Number(invoice.balance)-amount;await tx.workshopInvoice.update({where:{id:invoice.id},data:{paidAmount:{increment:amount},balance,status:balance<=0?"paid":"partial"}});return row;});return ok(res,p,201);}
export async function workshopReminderCreate(r:Request,res:Response){const b=bid(r),x=r.body;if(!await owned("workshopVehicle",b,x.vehicleId))return fail(res,"Vehicle not found",404);return ok(res,await db.workshopServiceReminder.create({data:{businessId:b,vehicleId:x.vehicleId,dueAt:new Date(x.dueAt),dueMileage:x.dueMileage?Number(x.dueMileage):null,message:x.message||null}}),201);}
export async function workshopReports(r:Request,res:Response){const b=bid(r);const [jobs,invoices,quality,reminders]=await Promise.all([db.workshopJobCard.groupBy({by:["status"],where:{businessId:b},_count:{_all:true}}),db.workshopInvoice.aggregate({where:{businessId:b},_sum:{total:true,balance:true}}),db.workshopQualityCheck.groupBy({by:["result"],where:{businessId:b},_count:{_all:true}}),db.workshopServiceReminder.count({where:{businessId:b,status:"pending"}})]);return ok(res,{jobs,invoiced:Number(invoices._sum.total||0),receivable:Number(invoices._sum.balance||0),quality,serviceReminders:reminders});}

export async function wholesaleAssignPriceList(r:Request,res:Response){const b=bid(r),x=r.body;if(!await owned("customer",b,x.customerId)||!await owned("wholesalePriceList",b,x.priceListId))return fail(res,"Customer or price list not found",404);return ok(res,await db.wholesaleCustomerPriceAssignment.upsert({where:{businessId_customerId:{businessId:b,customerId:x.customerId}},create:{businessId:b,customerId:x.customerId,priceListId:x.priceListId},update:{priceListId:x.priceListId,active:true}}),201);}
export async function wholesaleUnitConversionCreate(r:Request,res:Response){const b=bid(r),x=r.body;if(!await owned("product",b,x.productId))return fail(res,"Product not found",404);if(Number(x.factor)<=0)return fail(res,"Positive conversion factor required");return ok(res,await db.wholesaleUnitConversion.upsert({where:{businessId_productId_fromUnit_toUnit:{businessId:b,productId:x.productId,fromUnit:x.fromUnit,toUnit:x.toUnit}},create:{businessId:b,productId:x.productId,fromUnit:x.fromUnit,toUnit:x.toUnit,factor:Number(x.factor)},update:{factor:Number(x.factor)}}),201);}
export async function wholesalePackingCreate(r:Request,res:Response){const b=bid(r),x=r.body,pick=await owned("wholesalePickList",b,x.pickListId);if(!pick)return fail(res,"Pick list not found",404);return ok(res,await db.$transaction(async(tx:any)=>{const p=await tx.wholesalePackingList.create({data:{businessId:b,packingNo:`PACK-${Date.now()}`,pickListId:pick.id,status:"packed",packedBy:x.packedBy||null,packedAt:new Date()}});await tx.wholesalePickList.update({where:{id:pick.id},data:{status:"completed"}});return p;}),201);}
export async function wholesaleRouteCreate(r:Request,res:Response){const b=bid(r),x=r.body;if(!x.name)return fail(res,"Route name required");return ok(res,await db.wholesaleDeliveryRoute.create({data:{businessId:b,name:x.name,driverName:x.driverName||null,vehicleReference:x.vehicleReference||null}}),201);}
export async function wholesaleDispatchDeliver(r:Request,res:Response){const b=bid(r),d=await owned("wholesaleDispatch",b,r.params.id);if(!d)return fail(res,"Dispatch not found",404);return ok(res,await db.$transaction(async(tx:any)=>{const row=await tx.wholesaleDispatch.update({where:{id:d.id},data:{status:"delivered",deliveredAt:new Date()}});await tx.wholesaleSalesOrder.update({where:{id:d.salesOrderId},data:{status:"delivered"}});return row;}));}
export async function wholesaleCollectionCreate(r:Request,res:Response){const b=bid(r),x=r.body,k=key(r),amount=Number(x.amount||0),order=await owned("wholesaleSalesOrder",b,x.salesOrderId);if(!order)return fail(res,"Sales order not found",404);if(amount<=0)return fail(res,"Positive amount required");if(k){const old=await db.wholesaleCollection.findFirst({where:{businessId:b,idempotencyKey:k}});if(old)return ok(res,old);}return ok(res,await db.wholesaleCollection.create({data:{businessId:b,salesOrderId:order.id,customerId:order.customerId,amount,method:x.method||"bank",reference:x.reference||null,idempotencyKey:k}}),201);}
export async function wholesaleReports(r:Request,res:Response){const b=bid(r);const [orders,dispatches,backorders,collections]=await Promise.all([db.wholesaleSalesOrder.groupBy({by:["status"],where:{businessId:b},_count:{_all:true},_sum:{total:true}}),db.wholesaleDispatch.groupBy({by:["status"],where:{businessId:b},_count:{_all:true}}),db.wholesaleBackorder.aggregate({where:{businessId:b,status:"open"},_sum:{quantity:true}}),db.wholesaleCollection.aggregate({where:{businessId:b},_sum:{amount:true}})]);return ok(res,{orders,dispatches,openBackorderQuantity:Number(backorders._sum.quantity||0),collections:Number(collections._sum.amount||0)});}


export async function furnitureProcurementCreate(r:Request,res:Response){const b=bid(r),x=r.body;if(!await owned("furnitureCustomOrder",b,x.customOrderId))return fail(res,"Order not found",404);if(!x.description)return fail(res,"Description is required");return ok(res,await db.furnitureProcurement.create({data:{businessId:b,customOrderId:x.customOrderId,supplierId:x.supplierId||null,description:String(x.description),amount:Math.max(0,Number(x.amount||0)),status:x.status||"requested",orderedAt:x.status==="ordered"?new Date():null}}),201);}
export async function furnitureReturnCreate(r:Request,res:Response){const b=bid(r),x=r.body;if(!await owned("furnitureCustomOrder",b,x.customOrderId))return fail(res,"Order not found",404);if(!x.reason)return fail(res,"Return reason required");return ok(res,await db.furnitureReturn.create({data:{businessId:b,customOrderId:x.customOrderId,returnNo:`FRET-${Date.now()}`,reason:String(x.reason)}}),201);}
export async function furnitureReturnResolve(r:Request,res:Response){const b=bid(r),row=await owned("furnitureReturn",b,r.params.id);if(!row)return fail(res,"Return not found",404);if(!r.body.resolution)return fail(res,"Resolution required");return ok(res,await db.furnitureReturn.update({where:{id:row.id},data:{status:"resolved",resolution:String(r.body.resolution),resolvedAt:new Date()}}));}
export async function furnitureInstallationSignoff(r:Request,res:Response){const b=bid(r),x=r.body,inst=await owned("furnitureInstallation",b,r.params.id);if(!inst)return fail(res,"Installation not found",404);if(!x.customerName)return fail(res,"Customer name required");const row=await db.$transaction(async(tx:any)=>{const s=await tx.furnitureInstallationSignoff.upsert({where:{businessId_installationId:{businessId:b,installationId:inst.id}},create:{businessId:b,installationId:inst.id,customerName:x.customerName,signatureReference:x.signatureReference||null,notes:x.notes||null},update:{customerName:x.customerName,signatureReference:x.signatureReference||null,notes:x.notes||null,signedAt:new Date()}});await tx.furnitureInstallation.update({where:{id:inst.id},data:{status:"completed",completedAt:new Date()}});return s;});return ok(res,row,201);}
export async function furnitureWarrantyClaimResolve(r:Request,res:Response){const b=bid(r),row=await owned("furnitureWarrantyClaim",b,r.params.id);if(!row)return fail(res,"Warranty claim not found",404);return ok(res,await db.furnitureWarrantyClaim.update({where:{id:row.id},data:{status:"resolved",resolution:r.body.resolution||"Resolved",resolvedAt:new Date()}}));}

export async function workshopPostReservedParts(r:Request,res:Response){const b=bid(r),k=key(r),job=await owned("workshopJobCard",b,r.params.id);if(!job)return fail(res,"Job card not found",404);if(k){const old=await db.workshopInventoryPosting.findFirst({where:{businessId:b,idempotencyKey:k}});if(old)return ok(res,old);}const rows=await db.workshopPartReservation.findMany({where:{businessId:b,jobCardId:job.id,status:"reserved"}});if(!rows.length)return fail(res,"No reserved parts to post",409);const result=await db.$transaction(async(tx:any)=>{let first:any=null;for(const p of rows){const product=await tx.product.findFirst({where:{id:p.productId,businessId:b}});if(!product)throw new Error("Reserved product not found");const quantity=Number(p.quantity);if(Number(product.currentStock||0)<quantity)throw new Error(`Insufficient stock for ${product.name||p.productId}`);await tx.product.update({where:{id:product.id},data:{currentStock:{decrement:quantity}}});const post=await tx.workshopInventoryPosting.create({data:{businessId:b,jobCardId:job.id,productId:p.productId,quantity,postingType:"issue",idempotencyKey:first?null:k}});if(!first)first=post;await tx.workshopPartReservation.update({where:{id:p.id},data:{status:"used"}});await tx.workshopPartUsage.create({data:{businessId:b,jobCardId:job.id,productId:p.productId,quantity,unitCost:Number(product.costPrice||0)}});}return first;});return ok(res,result,201);}
export async function workshopVehicleDeliver(r:Request,res:Response){const b=bid(r),x=r.body,job=await owned("workshopJobCard",b,r.params.id);if(!job)return fail(res,"Job card not found",404);if(job.status!=="completed")return fail(res,"Quality-approved completed job required",409);if(!x.deliveredTo)return fail(res,"Receiver name required");const row=await db.$transaction(async(tx:any)=>{const d=await tx.workshopVehicleDelivery.upsert({where:{businessId_jobCardId:{businessId:b,jobCardId:job.id}},create:{businessId:b,jobCardId:job.id,deliveredTo:x.deliveredTo,signatureReference:x.signatureReference||null,notes:x.notes||null},update:{deliveredTo:x.deliveredTo,signatureReference:x.signatureReference||null,notes:x.notes||null,deliveredAt:new Date()}});await tx.workshopJobCard.update({where:{id:job.id},data:{status:"delivered"}});return d;});return ok(res,row,201);}

export async function wholesaleCreditProfileUpsert(r:Request,res:Response){const b=bid(r),x=r.body;if(!await owned("customer",b,x.customerId))return fail(res,"Customer not found",404);return ok(res,await db.wholesaleCreditProfile.upsert({where:{businessId_customerId:{businessId:b,customerId:x.customerId}},create:{businessId:b,customerId:x.customerId,creditLimit:Math.max(0,Number(x.creditLimit||0)),creditDays:Math.max(0,Number(x.creditDays||0)),blocked:Boolean(x.blocked)},update:{creditLimit:Math.max(0,Number(x.creditLimit||0)),creditDays:Math.max(0,Number(x.creditDays||0)),blocked:Boolean(x.blocked)}}),201);}
export async function wholesaleCreditCheck(r:Request,res:Response){const b=bid(r),customerId=String(r.params.customerId),amount=Math.max(0,Number(r.query.amount||0));if(!await owned("customer",b,customerId))return fail(res,"Customer not found",404);const profile=await db.wholesaleCreditProfile.findFirst({where:{businessId:b,customerId}});const orders=await db.wholesaleSalesOrder.aggregate({where:{businessId:b,customerId,status:{notIn:["delivered","cancelled"]}},_sum:{total:true}});const collections=await db.wholesaleCollection.aggregate({where:{businessId:b,customerId},_sum:{amount:true}});const exposure=Math.max(0,Number(orders._sum.total||0)-Number(collections._sum.amount||0)),limit=Number(profile?.creditLimit||0),available=Math.max(0,limit-exposure);return ok(res,{blocked:Boolean(profile?.blocked),creditLimit:limit,exposure,available,approved:!profile?.blocked&&amount<=available});}
export async function wholesalePackingCreateDetailed(r:Request,res:Response){const b=bid(r),x=r.body,pick=await owned("wholesalePickList",b,x.pickListId);if(!pick)return fail(res,"Pick list not found",404);const items=Array.isArray(x.items)?x.items:[];if(!items.length)return fail(res,"Packing items required");const row=await db.$transaction(async(tx:any)=>{const p=await tx.wholesalePackingList.create({data:{businessId:b,packingNo:`PACK-${Date.now()}`,pickListId:pick.id,status:"packed",packedBy:x.packedBy||null,packedAt:new Date()}});for(const i of items){if(Number(i.quantity)<=0)throw new Error("Positive packed quantity required");await tx.wholesalePackingListItem.create({data:{businessId:b,packingListId:p.id,salesOrderItemId:String(i.salesOrderItemId),quantity:Number(i.quantity),unit:i.unit||"unit"}});}await tx.wholesalePickList.update({where:{id:pick.id},data:{status:"completed"}});return p;});return ok(res,row,201);}
export async function wholesaleProofOfDelivery(r:Request,res:Response){const b=bid(r),x=r.body,d=await owned("wholesaleDispatch",b,r.params.id);if(!d)return fail(res,"Dispatch not found",404);if(!x.receiverName)return fail(res,"Receiver name required");const row=await db.$transaction(async(tx:any)=>{const pod=await tx.wholesaleProofOfDelivery.upsert({where:{businessId_dispatchId:{businessId:b,dispatchId:d.id}},create:{businessId:b,dispatchId:d.id,receiverName:x.receiverName,signatureReference:x.signatureReference||null,notes:x.notes||null},update:{receiverName:x.receiverName,signatureReference:x.signatureReference||null,notes:x.notes||null,deliveredAt:new Date()}});await tx.wholesaleDispatch.update({where:{id:d.id},data:{status:"delivered",deliveredAt:new Date()}});await tx.wholesaleSalesOrder.update({where:{id:d.salesOrderId},data:{status:"delivered"}});return pod;});return ok(res,row,201);}
export async function wholesaleAgeing(r:Request,res:Response){const b=bid(r);const orders=await db.wholesaleSalesOrder.findMany({where:{businessId:b,status:{notIn:["cancelled"]}},select:{id:true,customerId:true,total:true,createdAt:true}});const collected=await db.wholesaleCollection.groupBy({by:["salesOrderId"],where:{businessId:b},_sum:{amount:true}});const map=new Map(collected.map((x:any)=>[x.salesOrderId,Number(x._sum.amount||0)]));const now=Date.now(),buckets={current:0,days31to60:0,days61to90:0,over90:0};for(const o of orders){const bal=Math.max(0,Number(o.total)-Number(map.get(o.id)||0));const days=Math.floor((now-new Date(o.createdAt).getTime())/86400000);if(days<=30)buckets.current+=bal;else if(days<=60)buckets.days31to60+=bal;else if(days<=90)buckets.days61to90+=bal;else buckets.over90+=bal;}return ok(res,buckets);}
export async function releaseDNotificationRules(r:Request,res:Response){return ok(res,await db.releaseDNotificationRule.findMany({where:{businessId:bid(r),industry:String(r.params.industry)}}));}
export async function releaseDNotificationRuleUpsert(r:Request,res:Response){const b=bid(r),industry=String(r.params.industry),x=r.body;if(!x.eventCode)return fail(res,"Event code required");return ok(res,await db.releaseDNotificationRule.upsert({where:{businessId_industry_eventCode:{businessId:b,industry,eventCode:x.eventCode}},create:{businessId:b,industry,eventCode:x.eventCode,enabled:x.enabled!==false,daysBefore:x.daysBefore==null?null:Number(x.daysBefore),channel:x.channel||"in_app"},update:{enabled:x.enabled!==false,daysBefore:x.daysBefore==null?null:Number(x.daysBefore),channel:x.channel||"in_app"}}),201);}
