import type { Request } from 'express';
import { prisma } from '../db/prisma.js';
import { ApiError, cleanString, dateValue, numberValue, plain, requireText } from '../utils/http.js';

function revision(body:any){ return Math.max(1, Math.floor(numberValue(body?.revision, 1))); }
function page(query:any){ return { take: Math.min(200, Math.max(1, numberValue(query?.limit, 50))), skip: Math.max(0, numberValue(query?.offset, 0)) }; }
async function assertOwned(model:any,id:string,businessId:string,label:string){ const row=await model.findFirst({where:{id,businessId}}); if(!row) throw new ApiError(404,`${label} not found`); return row; }

export async function gymDashboard(businessId:string){
  const now=new Date(), in30=new Date(now.getTime()+30*86400000);
  const [activeMembers,activeMemberships,expiring,plans]=await Promise.all([
    prisma.gymMember.count({where:{businessId,status:'active',archivedAt:null}}),
    prisma.gymMembership.count({where:{businessId,status:'active'}}),
    prisma.gymMembership.count({where:{businessId,status:'active',endDate:{gte:now,lte:in30}}}),
    prisma.gymMembershipPlan.count({where:{businessId,active:true}}),
  ]); return {activeMembers,activeMemberships,expiringMemberships:expiring,activePlans:plans};
}
export async function listGymMembers(businessId:string,q:any){return plain(await prisma.gymMember.findMany({where:{businessId,archivedAt:null, ...(cleanString(q?.search)?{OR:[{fullName:{contains:cleanString(q.search),mode:'insensitive'}},{memberNo:{contains:cleanString(q.search),mode:'insensitive'}},{phone:{contains:cleanString(q.search),mode:'insensitive'}}]}:{})},orderBy:{createdAt:'desc'},...page(q)}));}
export async function createGymMember(businessId:string,body:any){return plain(await prisma.gymMember.create({data:{businessId,memberNo:requireText(body.memberNo,'memberNo'),fullName:requireText(body.fullName,'fullName'),phone:cleanString(body.phone),email:cleanString(body.email),dateOfBirth:dateValue(body.dateOfBirth),emergencyContact:cleanString(body.emergencyContact)}}));}
export async function updateGymMember(businessId:string,id:string,body:any){const current=await assertOwned(prisma.gymMember,id,businessId,'Gym member'); if(current.revision!==revision(body)) throw new ApiError(409,'Stale gym member revision',{currentRevision:current.revision}); return plain(await prisma.gymMember.update({where:{id},data:{fullName:cleanString(body.fullName),phone:cleanString(body.phone),email:cleanString(body.email),status:cleanString(body.status),revision:{increment:1}}}));}
export async function archiveGymMember(businessId:string,id:string){await assertOwned(prisma.gymMember,id,businessId,'Gym member'); return plain(await prisma.gymMember.update({where:{id},data:{status:'inactive',archivedAt:new Date(),revision:{increment:1}}}));}
export async function listGymPlans(businessId:string){return plain(await prisma.gymMembershipPlan.findMany({where:{businessId},orderBy:{name:'asc'}}));}
export async function createGymPlan(businessId:string,body:any){return plain(await prisma.gymMembershipPlan.create({data:{businessId,code:requireText(body.code,'code'),name:requireText(body.name,'name'),durationDays:Math.max(1,numberValue(body.durationDays,30)),price:numberValue(body.price)}}));}
export async function createGymMembership(businessId:string,body:any){return plain(await prisma.$transaction(async tx=>{const member=await tx.gymMember.findFirst({where:{id:requireText(body.memberId,'memberId'),businessId,archivedAt:null}}); const plan=await tx.gymMembershipPlan.findFirst({where:{id:requireText(body.planId,'planId'),businessId,active:true}}); if(!member||!plan) throw new ApiError(400,'Member or plan does not belong to this tenant'); const start=dateValue(body.startDate)||new Date(); const end=dateValue(body.endDate)||new Date(start.getTime()+plan.durationDays*86400000); return tx.gymMembership.create({data:{businessId,memberId:member.id,planId:plan.id,startDate:start,endDate:end,amount:numberValue(body.amount,Number(plan.price)),paidAmount:numberValue(body.paidAmount)}});}));}

export async function schoolDashboard(businessId:string){const [students,classes,enrollments]=await Promise.all([prisma.schoolStudent.count({where:{businessId,status:'active',archivedAt:null}}),prisma.schoolClassSection.count({where:{businessId,active:true}}),prisma.schoolEnrollment.count({where:{businessId,status:'active'}})]); return {activeStudents:students,activeClasses:classes,activeEnrollments:enrollments};}
export async function listSchoolStudents(businessId:string,q:any){return plain(await prisma.schoolStudent.findMany({where:{businessId,archivedAt:null,...(cleanString(q?.search)?{OR:[{fullName:{contains:cleanString(q.search),mode:'insensitive'}},{admissionNo:{contains:cleanString(q.search),mode:'insensitive'}}]}:{})},orderBy:{createdAt:'desc'},...page(q)}));}
export async function createSchoolStudent(businessId:string,body:any){return plain(await prisma.schoolStudent.create({data:{businessId,admissionNo:requireText(body.admissionNo,'admissionNo'),fullName:requireText(body.fullName,'fullName'),dateOfBirth:dateValue(body.dateOfBirth)}}));}
export async function createSchoolClass(businessId:string,body:any){return plain(await prisma.schoolClassSection.create({data:{businessId,academicYear:requireText(body.academicYear,'academicYear'),grade:requireText(body.grade,'grade'),section:requireText(body.section,'section'),capacity:Math.max(1,numberValue(body.capacity,30))}}));}
export async function listSchoolClasses(businessId:string){return plain(await prisma.schoolClassSection.findMany({where:{businessId,active:true},orderBy:[{academicYear:'desc'},{grade:'asc'},{section:'asc'}]}));}
export async function enrollStudent(businessId:string,body:any){return plain(await prisma.$transaction(async tx=>{const student=await tx.schoolStudent.findFirst({where:{id:requireText(body.studentId,'studentId'),businessId,archivedAt:null}}); const section=await tx.schoolClassSection.findFirst({where:{id:requireText(body.classSectionId,'classSectionId'),businessId,active:true}}); if(!student||!section) throw new ApiError(400,'Student or class does not belong to this tenant'); const count=await tx.schoolEnrollment.count({where:{businessId,classSectionId:section.id,status:'active'}}); if(count>=section.capacity) throw new ApiError(409,'Class capacity has been reached'); return tx.schoolEnrollment.create({data:{businessId,studentId:student.id,classSectionId:section.id}});}));}

export async function clinicDashboard(businessId:string){const start=new Date();start.setHours(0,0,0,0);const end=new Date(start.getTime()+86400000);const [patients,practitioners,appointments]=await Promise.all([prisma.clinicPatient.count({where:{businessId,status:'active',archivedAt:null}}),prisma.clinicPractitioner.count({where:{businessId,active:true}}),prisma.clinicAppointment.count({where:{businessId,startAt:{gte:start,lt:end},status:{not:'cancelled'}}})]);return {activePatients:patients,activePractitioners:practitioners,todayAppointments:appointments};}
export async function listClinicPatients(businessId:string,q:any){return plain(await prisma.clinicPatient.findMany({where:{businessId,archivedAt:null,...(cleanString(q?.search)?{OR:[{fullName:{contains:cleanString(q.search),mode:'insensitive'}},{patientNo:{contains:cleanString(q.search),mode:'insensitive'}},{phone:{contains:cleanString(q.search),mode:'insensitive'}}]}:{})},orderBy:{createdAt:'desc'},...page(q)}));}
export async function createClinicPatient(businessId:string,body:any){if(body.consentConfirmed!==true) throw new ApiError(400,'Patient consent confirmation is required'); return plain(await prisma.clinicPatient.create({data:{businessId,patientNo:requireText(body.patientNo,'patientNo'),fullName:requireText(body.fullName,'fullName'),phone:cleanString(body.phone),dateOfBirth:dateValue(body.dateOfBirth),consentConfirmed:true}}));}
export async function listPractitioners(businessId:string){return plain(await prisma.clinicPractitioner.findMany({where:{businessId,active:true},orderBy:{fullName:'asc'}}));}
export async function createPractitioner(businessId:string,body:any){return plain(await prisma.clinicPractitioner.create({data:{businessId,fullName:requireText(body.fullName,'fullName'),specialty:requireText(body.specialty,'specialty'),licenseReference:cleanString(body.licenseReference)}}));}
export async function listAppointments(businessId:string,q:any){return plain(await prisma.clinicAppointment.findMany({where:{businessId,...(dateValue(q?.from)?{startAt:{gte:dateValue(q.from)}}:{})},include:{patient:{select:{patientNo:true,fullName:true}},practitioner:{select:{fullName:true,specialty:true}}},orderBy:{startAt:'asc'},...page(q)}));}
export async function createAppointment(businessId:string,body:any){return plain(await prisma.$transaction(async tx=>{const patient=await tx.clinicPatient.findFirst({where:{id:requireText(body.patientId,'patientId'),businessId,archivedAt:null}}); const practitioner=await tx.clinicPractitioner.findFirst({where:{id:requireText(body.practitionerId,'practitionerId'),businessId,active:true}}); if(!patient||!practitioner) throw new ApiError(400,'Patient or practitioner does not belong to this tenant'); const start=dateValue(body.startAt),end=dateValue(body.endAt); if(!start||!end||end<=start) throw new ApiError(400,'Valid startAt and endAt are required'); const conflict=await tx.clinicAppointment.findFirst({where:{businessId,practitionerId:practitioner.id,status:{notIn:['cancelled','no_show']},startAt:{lt:end},endAt:{gt:start}}}); if(conflict) throw new ApiError(409,'Practitioner already has an appointment in this time range'); if(cleanString(body.room)){const roomConflict=await tx.clinicAppointment.findFirst({where:{businessId,room:cleanString(body.room),status:{notIn:['cancelled','no_show']},startAt:{lt:end},endAt:{gt:start}}});if(roomConflict) throw new ApiError(409,'Room already has an appointment in this time range');} return tx.clinicAppointment.create({data:{businessId,patientId:patient.id,practitionerId:practitioner.id,startAt:start,endAt:end,service:requireText(body.service,'service'),room:cleanString(body.room)}});}));}


export async function listGymTrainers(businessId:string){return plain(await prisma.gymTrainer.findMany({where:{businessId,active:true},orderBy:{fullName:'asc'}}));}
export async function createGymTrainer(businessId:string,body:any){return plain(await prisma.gymTrainer.create({data:{businessId,employeeNo:cleanString(body.employeeNo),fullName:requireText(body.fullName,'fullName'),phone:cleanString(body.phone),specialties:cleanString(body.specialties)}}));}
export async function listGymClasses(businessId:string,q:any){return plain(await prisma.gymClass.findMany({where:{businessId,...(dateValue(q?.from)?{startAt:{gte:dateValue(q.from)}}:{})},include:{trainer:{select:{fullName:true}},_count:{select:{bookings:{where:{status:'booked'}}}}},orderBy:{startAt:'asc'},...page(q)}));}
export async function createGymClass(businessId:string,body:any){return plain(await prisma.$transaction(async tx=>{const trainerId=cleanString(body.trainerId)||null; if(trainerId) await assertOwned(tx.gymTrainer,trainerId,businessId,'Gym trainer'); const start=dateValue(body.startAt),end=dateValue(body.endAt); if(!start||!end||end<=start) throw new ApiError(400,'Valid startAt and endAt are required'); const room=cleanString(body.room); const OR:any[]=[]; if(trainerId) OR.push({trainerId}); if(room) OR.push({room}); if(OR.length){const conflict=await tx.gymClass.findFirst({where:{businessId,status:{not:'cancelled'},OR,startAt:{lt:end},endAt:{gt:start}}});if(conflict)throw new ApiError(409,'Trainer or room already has a class in this time range');} return tx.gymClass.create({data:{businessId,trainerId,name:requireText(body.name,'name'),room,startAt:start,endAt:end,capacity:Math.max(1,numberValue(body.capacity,20))}});}));}
export async function bookGymClass(businessId:string,body:any){return plain(await prisma.$transaction(async tx=>{const gymClass=await tx.gymClass.findFirst({where:{id:requireText(body.classId,'classId'),businessId,status:'scheduled'}}); const member=await tx.gymMember.findFirst({where:{id:requireText(body.memberId,'memberId'),businessId,status:'active',archivedAt:null}}); if(!gymClass||!member)throw new ApiError(400,'Class or member does not belong to this tenant'); const count=await tx.gymClassBooking.count({where:{businessId,classId:gymClass.id,status:'booked'}}); if(count>=gymClass.capacity)throw new ApiError(409,'Class capacity has been reached'); return tx.gymClassBooking.create({data:{businessId,classId:gymClass.id,memberId:member.id}});}));}
export async function gymCheckIn(businessId:string,body:any){return plain(await prisma.$transaction(async tx=>{const member=await tx.gymMember.findFirst({where:{id:requireText(body.memberId,'memberId'),businessId,status:'active',archivedAt:null}});if(!member)throw new ApiError(404,'Active gym member not found'); const now=new Date(); const active=await tx.gymMembership.findFirst({where:{businessId,memberId:member.id,status:'active',startDate:{lte:now},endDate:{gte:now}}});if(!active)throw new ApiError(409,'Member has no active membership'); return tx.gymCheckIn.create({data:{businessId,memberId:member.id,method:cleanString(body.method)||'manual'}});}));}

export async function listSchoolGuardians(businessId:string){return plain(await prisma.schoolGuardian.findMany({where:{businessId},orderBy:{fullName:'asc'}}));}
export async function createSchoolGuardian(businessId:string,body:any){return plain(await prisma.schoolGuardian.create({data:{businessId,fullName:requireText(body.fullName,'fullName'),phone:requireText(body.phone,'phone'),email:cleanString(body.email),relation:cleanString(body.relation)}}));}
export async function linkSchoolGuardian(businessId:string,body:any){return plain(await prisma.$transaction(async tx=>{await assertOwned(tx.schoolStudent,requireText(body.studentId,'studentId'),businessId,'School student');await assertOwned(tx.schoolGuardian,requireText(body.guardianId,'guardianId'),businessId,'School guardian');return tx.schoolStudentGuardian.upsert({where:{businessId_studentId_guardianId:{businessId,studentId:body.studentId,guardianId:body.guardianId}},update:{isPrimary:body.isPrimary===true},create:{businessId,studentId:body.studentId,guardianId:body.guardianId,isPrimary:body.isPrimary===true}});}));}
export async function recordSchoolAttendance(businessId:string,body:any){const d=dateValue(body.attendanceDate);if(!d)throw new ApiError(400,'attendanceDate is required');d.setHours(0,0,0,0);return plain(await prisma.$transaction(async tx=>{await assertOwned(tx.schoolStudent,requireText(body.studentId,'studentId'),businessId,'School student');await assertOwned(tx.schoolClassSection,requireText(body.classSectionId,'classSectionId'),businessId,'School class');const enrolled=await tx.schoolEnrollment.findFirst({where:{businessId,studentId:body.studentId,classSectionId:body.classSectionId,status:'active'}});if(!enrolled)throw new ApiError(409,'Student is not actively enrolled in this class');return tx.schoolAttendance.upsert({where:{businessId_studentId_classSectionId_attendanceDate:{businessId,studentId:body.studentId,classSectionId:body.classSectionId,attendanceDate:d}},update:{status:requireText(body.status,'status'),note:cleanString(body.note)},create:{businessId,studentId:body.studentId,classSectionId:body.classSectionId,attendanceDate:d,status:requireText(body.status,'status'),note:cleanString(body.note)}});}));}
export async function createSchoolFeeHead(businessId:string,body:any){return plain(await prisma.schoolFeeHead.create({data:{businessId,code:requireText(body.code,'code'),name:requireText(body.name,'name')}}));}
export async function listSchoolFees(businessId:string,q:any){return plain(await prisma.schoolStudentFee.findMany({where:{businessId,...(cleanString(q?.status)?{status:cleanString(q.status)}:{})},include:{student:{select:{admissionNo:true,fullName:true}},feeHead:true,payments:true},orderBy:{dueDate:'asc'},...page(q)}));}
export async function createSchoolFee(businessId:string,body:any){return plain(await prisma.$transaction(async tx=>{await assertOwned(tx.schoolStudent,requireText(body.studentId,'studentId'),businessId,'School student');await assertOwned(tx.schoolFeeHead,requireText(body.feeHeadId,'feeHeadId'),businessId,'School fee head');const due=dateValue(body.dueDate);if(!due)throw new ApiError(400,'dueDate is required');return tx.schoolStudentFee.create({data:{businessId,studentId:body.studentId,feeHeadId:body.feeHeadId,dueDate:due,amount:numberValue(body.amount)}});}));}
export async function paySchoolFee(businessId:string,body:any,idempotencyKey?:string){return plain(await prisma.$transaction(async tx=>{if(idempotencyKey){const replay=await tx.schoolFeePayment.findFirst({where:{businessId,idempotencyKey}});if(replay)return replay;}const fee=await tx.schoolStudentFee.findFirst({where:{id:requireText(body.studentFeeId,'studentFeeId'),businessId}});if(!fee)throw new ApiError(404,'School fee not found');const amount=numberValue(body.amount);if(amount<=0)throw new ApiError(400,'Payment amount must be positive');const balance=Number(fee.amount)-Number(fee.paidAmount);if(amount>balance)throw new ApiError(409,'Payment exceeds outstanding fee balance');const nextPaid=Number(fee.paidAmount)+amount;await tx.schoolStudentFee.update({where:{id:fee.id},data:{paidAmount:nextPaid,status:nextPaid>=Number(fee.amount)?'paid':'partial',revision:{increment:1}}});return tx.schoolFeePayment.create({data:{businessId,studentFeeId:fee.id,amount,paymentMethod:requireText(body.paymentMethod,'paymentMethod'),reference:cleanString(body.reference),idempotencyKey:idempotencyKey||null}});}));}

export async function createClinicConsent(businessId:string,body:any){return plain(await prisma.$transaction(async tx=>{await assertOwned(tx.clinicPatient,requireText(body.patientId,'patientId'),businessId,'Clinic patient');return tx.clinicConsent.create({data:{businessId,patientId:body.patientId,consentType:requireText(body.consentType,'consentType'),confirmed:body.confirmed!==false,expiresAt:dateValue(body.expiresAt),note:cleanString(body.note)}});}));}
export async function listClinicQueue(businessId:string){return plain(await prisma.clinicQueueEntry.findMany({where:{businessId,status:{in:['waiting','called','in_service']}},include:{patient:{select:{patientNo:true,fullName:true}},practitioner:{select:{fullName:true}}},orderBy:{checkedInAt:'asc'}}));}
export async function clinicQueueCheckIn(businessId:string,body:any){return plain(await prisma.$transaction(async tx=>{await assertOwned(tx.clinicPatient,requireText(body.patientId,'patientId'),businessId,'Clinic patient');if(cleanString(body.practitionerId))await assertOwned(tx.clinicPractitioner,body.practitionerId,businessId,'Clinic practitioner');if(cleanString(body.appointmentId))await assertOwned(tx.clinicAppointment,body.appointmentId,businessId,'Clinic appointment');const start=new Date();start.setHours(0,0,0,0);const last=await tx.clinicQueueEntry.findFirst({where:{businessId,checkedInAt:{gte:start}},orderBy:{queueNo:'desc'}});return tx.clinicQueueEntry.create({data:{businessId,patientId:body.patientId,practitionerId:cleanString(body.practitionerId)||null,appointmentId:cleanString(body.appointmentId)||null,queueNo:(last?.queueNo||0)+1}});}));}
export async function updateClinicQueue(businessId:string,id:string,body:any){const current=await assertOwned(prisma.clinicQueueEntry,id,businessId,'Clinic queue entry');const status=requireText(body.status,'status');return plain(await prisma.clinicQueueEntry.update({where:{id:current.id},data:{status,calledAt:status==='called'?new Date():current.calledAt,completedAt:status==='completed'?new Date():current.completedAt}}));}
export async function listClinicServices(businessId:string){return plain(await prisma.clinicService.findMany({where:{businessId,active:true},orderBy:{name:'asc'}}));}
export async function createClinicService(businessId:string,body:any){return plain(await prisma.clinicService.create({data:{businessId,code:requireText(body.code,'code'),name:requireText(body.name,'name'),price:numberValue(body.price)}}));}
export async function listClinicFollowUps(businessId:string){return plain(await prisma.clinicFollowUp.findMany({where:{businessId,status:'pending'},include:{patient:{select:{patientNo:true,fullName:true}},practitioner:{select:{fullName:true}}},orderBy:{dueAt:'asc'}}));}
export async function createClinicFollowUp(businessId:string,body:any){return plain(await prisma.$transaction(async tx=>{await assertOwned(tx.clinicPatient,requireText(body.patientId,'patientId'),businessId,'Clinic patient');if(cleanString(body.practitionerId))await assertOwned(tx.clinicPractitioner,body.practitionerId,businessId,'Clinic practitioner');const due=dateValue(body.dueAt);if(!due)throw new ApiError(400,'dueAt is required');return tx.clinicFollowUp.create({data:{businessId,patientId:body.patientId,practitionerId:cleanString(body.practitionerId)||null,dueAt:due,reason:requireText(body.reason,'reason')}});}));}

// Release B checkpoint 3: remaining operational foundations
export async function listGymPrograms(businessId:string){return plain(await prisma.gymProgram.findMany({where:{businessId,active:true},orderBy:{name:'asc'}}));}
export async function createGymProgram(businessId:string,body:any){return plain(await prisma.gymProgram.create({data:{businessId,code:requireText(body.code,'code'),name:requireText(body.name,'name'),description:cleanString(body.description),durationWeeks:Math.max(1,numberValue(body.durationWeeks,4)),price:numberValue(body.price)}}));}
export async function enrollGymProgram(businessId:string,body:any){return plain(await prisma.$transaction(async tx=>{await assertOwned(tx.gymProgram,requireText(body.programId,'programId'),businessId,'Gym program');await assertOwned(tx.gymMember,requireText(body.memberId,'memberId'),businessId,'Gym member');if(cleanString(body.trainerId))await assertOwned(tx.gymTrainer,body.trainerId,businessId,'Gym trainer');const start=dateValue(body.startDate)||new Date();return tx.gymProgramEnrollment.create({data:{businessId,programId:body.programId,memberId:body.memberId,trainerId:cleanString(body.trainerId)||null,startDate:start,endDate:dateValue(body.endDate),notes:cleanString(body.notes)}});}));}
export async function listGymFacilities(businessId:string){return plain(await prisma.gymFacility.findMany({where:{businessId,active:true},orderBy:{name:'asc'}}));}
export async function createGymFacility(businessId:string,body:any){return plain(await prisma.gymFacility.create({data:{businessId,code:requireText(body.code,'code'),name:requireText(body.name,'name'),capacity:Math.max(1,numberValue(body.capacity,1))}}));}
export async function assignGymFacility(businessId:string,body:any){return plain(await prisma.$transaction(async tx=>{const f=await assertOwned(tx.gymFacility,requireText(body.facilityId,'facilityId'),businessId,'Gym facility');await assertOwned(tx.gymMember,requireText(body.memberId,'memberId'),businessId,'Gym member');const active=await tx.gymFacilityEnrollment.count({where:{businessId,facilityId:f.id,status:'active'}});if(active>=f.capacity)throw new ApiError(409,'Facility capacity has been reached');return tx.gymFacilityEnrollment.create({data:{businessId,facilityId:f.id,memberId:body.memberId,startDate:dateValue(body.startDate)||new Date(),endDate:dateValue(body.endDate)}});}));}
export async function assignGymTrainer(businessId:string,body:any){return plain(await prisma.$transaction(async tx=>{await assertOwned(tx.gymTrainer,requireText(body.trainerId,'trainerId'),businessId,'Gym trainer');await assertOwned(tx.gymMember,requireText(body.memberId,'memberId'),businessId,'Gym member');return tx.gymTrainerAssignment.create({data:{businessId,trainerId:body.trainerId,memberId:body.memberId,startDate:dateValue(body.startDate)||new Date(),endDate:dateValue(body.endDate),notes:cleanString(body.notes)}});}));}
export async function assignGymLocker(businessId:string,body:any){await assertOwned(prisma.gymMember,requireText(body.memberId,'memberId'),businessId,'Gym member');const existing=await prisma.gymLockerAssignment.findFirst({where:{businessId,lockerNo:requireText(body.lockerNo,'lockerNo'),status:'active'}});if(existing)throw new ApiError(409,'Locker is already assigned');return plain(await prisma.gymLockerAssignment.create({data:{businessId,memberId:body.memberId,lockerNo:body.lockerNo}}));}
export async function recordGymMeasurement(businessId:string,body:any){await assertOwned(prisma.gymMember,requireText(body.memberId,'memberId'),businessId,'Gym member');return plain(await prisma.gymMeasurement.create({data:{businessId,memberId:body.memberId,measuredAt:dateValue(body.measuredAt)||new Date(),weightKg:cleanString(body.weightKg)?numberValue(body.weightKg):null,heightCm:cleanString(body.heightCm)?numberValue(body.heightCm):null,bodyFatPct:cleanString(body.bodyFatPct)?numberValue(body.bodyFatPct):null,waistCm:cleanString(body.waistCm)?numberValue(body.waistCm):null,goalNote:cleanString(body.goalNote),recordedBy:cleanString(body.recordedBy)}}));}

export async function listSchoolApplicants(businessId:string){return plain(await prisma.schoolApplicant.findMany({where:{businessId},orderBy:{appliedAt:'desc'}}));}
export async function createSchoolApplicant(businessId:string,body:any){return plain(await prisma.schoolApplicant.create({data:{businessId,applicationNo:requireText(body.applicationNo,'applicationNo'),fullName:requireText(body.fullName,'fullName'),requestedGrade:cleanString(body.requestedGrade),guardianName:cleanString(body.guardianName),guardianPhone:cleanString(body.guardianPhone)}}));}
export async function createAcademicYear(businessId:string,body:any){const starts=dateValue(body.startsOn),ends=dateValue(body.endsOn);if(!starts||!ends||ends<=starts)throw new ApiError(400,'Valid academic-year dates are required');return plain(await prisma.academicYear.create({data:{businessId,name:requireText(body.name,'name'),startsOn:starts,endsOn:ends,active:body.active===true}}));}
export async function createAcademicTerm(businessId:string,body:any){await assertOwned(prisma.academicYear,requireText(body.academicYearId,'academicYearId'),businessId,'Academic year');const starts=dateValue(body.startsOn),ends=dateValue(body.endsOn);if(!starts||!ends||ends<=starts)throw new ApiError(400,'Valid term dates are required');return plain(await prisma.academicTerm.create({data:{businessId,academicYearId:body.academicYearId,name:requireText(body.name,'name'),startsOn:starts,endsOn:ends}}));}
export async function createSchoolSubject(businessId:string,body:any){return plain(await prisma.schoolSubject.create({data:{businessId,code:requireText(body.code,'code'),name:requireText(body.name,'name')}}));}
export async function createSchoolTeacher(businessId:string,body:any){return plain(await prisma.schoolTeacher.create({data:{businessId,employeeNo:cleanString(body.employeeNo),fullName:requireText(body.fullName,'fullName'),phone:cleanString(body.phone),email:cleanString(body.email)}}));}
export async function createSchoolRoom(businessId:string,body:any){return plain(await prisma.schoolRoom.create({data:{businessId,code:requireText(body.code,'code'),name:requireText(body.name,'name'),capacity:Math.max(1,numberValue(body.capacity,30))}}));}
export async function createTimetableEntry(businessId:string,body:any){return plain(await prisma.$transaction(async tx=>{for(const [model,id,label] of [[tx.schoolClassSection,body.classSectionId,'Class section'],[tx.schoolSubject,body.subjectId,'Subject'],[tx.schoolTeacher,body.teacherId,'Teacher'],[tx.schoolRoom,body.roomId,'Room']] as any[])await assertOwned(model,requireText(id,label),businessId,label);const weekday=Math.floor(numberValue(body.weekday));const start=Math.floor(numberValue(body.startMinute));const end=Math.floor(numberValue(body.endMinute));if(weekday<1||weekday>7||start<0||end<=start||end>1440)throw new ApiError(400,'Invalid timetable day or time');const conflict=await tx.schoolTimetableEntry.findFirst({where:{businessId,weekday,active:true,startMinute:{lt:end},endMinute:{gt:start},OR:[{teacherId:body.teacherId},{roomId:body.roomId},{classSectionId:body.classSectionId}]}});if(conflict)throw new ApiError(409,'Teacher, room, or class already has a timetable entry in this period');return tx.schoolTimetableEntry.create({data:{businessId,classSectionId:body.classSectionId,subjectId:body.subjectId,teacherId:body.teacherId,roomId:body.roomId,weekday,startMinute:start,endMinute:end}});}));}
export async function createSchoolAssessment(businessId:string,body:any){await assertOwned(prisma.schoolClassSection,requireText(body.classSectionId,'classSectionId'),businessId,'Class section');await assertOwned(prisma.schoolSubject,requireText(body.subjectId,'subjectId'),businessId,'Subject');return plain(await prisma.schoolAssessment.create({data:{businessId,classSectionId:body.classSectionId,subjectId:body.subjectId,termId:cleanString(body.termId)||null,name:requireText(body.name,'name'),maxMarks:numberValue(body.maxMarks,100),assessmentDate:dateValue(body.assessmentDate)}}));}
export async function recordSchoolResult(businessId:string,body:any){const assessment=await assertOwned(prisma.schoolAssessment,requireText(body.assessmentId,'assessmentId'),businessId,'Assessment');await assertOwned(prisma.schoolStudent,requireText(body.studentId,'studentId'),businessId,'Student');const marks=numberValue(body.marks);if(marks<0||marks>Number(assessment.maxMarks))throw new ApiError(400,'Marks must be within assessment maximum');return plain(await prisma.schoolResult.upsert({where:{businessId_assessmentId_studentId:{businessId,assessmentId:body.assessmentId,studentId:body.studentId}},create:{businessId,assessmentId:body.assessmentId,studentId:body.studentId,marks,grade:cleanString(body.grade),remarks:cleanString(body.remarks)},update:{marks,grade:cleanString(body.grade),remarks:cleanString(body.remarks)}}));}
export async function createSchoolEmployee(businessId:string,body:any){return plain(await prisma.schoolEmployee.create({data:{businessId,employeeNo:requireText(body.employeeNo,'employeeNo'),fullName:requireText(body.fullName,'fullName'),roleTitle:requireText(body.roleTitle,'roleTitle'),monthlySalary:numberValue(body.monthlySalary)}}));}

export async function createClinicSpecialty(businessId:string,body:any){return plain(await prisma.clinicSpecialty.create({data:{businessId,code:requireText(body.code,'code'),name:requireText(body.name,'name')}}));}
export async function createClinicEncounter(businessId:string,body:any){return plain(await prisma.$transaction(async tx=>{await assertOwned(tx.clinicPatient,requireText(body.patientId,'patientId'),businessId,'Clinic patient');await assertOwned(tx.clinicPractitioner,requireText(body.practitionerId,'practitionerId'),businessId,'Clinic practitioner');if(cleanString(body.appointmentId))await assertOwned(tx.clinicAppointment,body.appointmentId,businessId,'Clinic appointment');return tx.clinicEncounter.create({data:{businessId,patientId:body.patientId,practitionerId:body.practitionerId,appointmentId:cleanString(body.appointmentId)||null,practitionerNotes:cleanString(body.practitionerNotes),followUpRequired:body.followUpRequired===true}});}));}
export async function updateClinicEncounter(businessId:string,id:string,body:any){const current=await assertOwned(prisma.clinicEncounter,id,businessId,'Clinic encounter');if(current.revision!==revision(body))throw new ApiError(409,'Stale encounter revision',{currentRevision:current.revision});return plain(await prisma.clinicEncounter.update({where:{id},data:{practitionerNotes:cleanString(body.practitionerNotes),status:cleanString(body.status)||current.status,endedAt:body.status==='completed'?new Date():current.endedAt,followUpRequired:body.followUpRequired===true,revision:{increment:1}}}));}
export async function createClinicServiceRequest(businessId:string,body:any){await assertOwned(prisma.clinicEncounter,requireText(body.encounterId,'encounterId'),businessId,'Clinic encounter');const service=await assertOwned(prisma.clinicService,requireText(body.serviceId,'serviceId'),businessId,'Clinic service');return plain(await prisma.clinicServiceRequest.create({data:{businessId,encounterId:body.encounterId,serviceId:body.serviceId,quantity:numberValue(body.quantity,1),unitPrice:numberValue(body.unitPrice,Number(service.price))}}));}
export async function createClinicMedicationRequest(businessId:string,body:any,authorizedBy:string){await assertOwned(prisma.clinicEncounter,requireText(body.encounterId,'encounterId'),businessId,'Clinic encounter');if(!authorizedBy)throw new ApiError(403,'Authorized practitioner identity is required');return plain(await prisma.clinicMedicationRequest.create({data:{businessId,encounterId:body.encounterId,medicationText:requireText(body.medicationText,'medicationText'),instructions:cleanString(body.instructions),authorizedBy}}));}
export async function releaseBReports(businessId:string,industry:string){if(industry==='gym'){const [members,checkIns,programs]=await Promise.all([prisma.gymMember.count({where:{businessId,archivedAt:null}}),prisma.gymCheckIn.count({where:{businessId}}),prisma.gymProgramEnrollment.count({where:{businessId,status:'active'}})]);return {members,checkIns,activeProgramEnrollments:programs};}if(industry==='school'){const [students,fees,attendance]=await Promise.all([prisma.schoolStudent.count({where:{businessId,archivedAt:null}}),prisma.schoolStudentFee.aggregate({where:{businessId,status:{in:['due','partial']}},_sum:{amount:true,paidAmount:true}}),prisma.schoolAttendance.count({where:{businessId}})]);return plain({students,outstandingFees:Number(fees._sum.amount||0)-Number(fees._sum.paidAmount||0),attendanceRecords:attendance});}const [patients,encounters,followUps]=await Promise.all([prisma.clinicPatient.count({where:{businessId,archivedAt:null}}),prisma.clinicEncounter.count({where:{businessId}}),prisma.clinicFollowUp.count({where:{businessId,status:'pending'}})]);return {patients,encounters,pendingFollowUps:followUps};}
