import type { Request } from "express";
import { prisma } from "../db/prisma.js";
import { writeAudit } from "./audit.service.js";
import { nextEntityNumber } from "./numbering.service.js";
import { ApiError, cleanString, dateRange, dateValue, numberValue, plain, requireText, roundMoney, roundQty } from "../utils/http.js";

function normalizeItems(items: unknown): any[] {
  if (!Array.isArray(items) || !items.length) throw new ApiError(400, "At least one purchase item is required");
  return items.map((item: any, index) => {
    const qty = roundQty(numberValue(item.qty ?? item.quantity));
    const cost = roundMoney(numberValue(item.cost ?? item.rate ?? item.unitCost));
    if (qty <= 0) throw new ApiError(400, `Item ${index + 1} quantity must be greater than zero`);
    const discount = roundMoney(numberValue(item.discount));
    const taxRate = numberValue(item.taxRate);
    const base = roundMoney(qty * cost - discount);
    const tax = item.tax !== undefined ? roundMoney(numberValue(item.tax)) : roundMoney(base * taxRate / 100);
    return { productId: cleanString(item.productId) || null, sku: cleanString(item.sku) || null, barcode: cleanString(item.barcode) || null, name: requireText(item.name ?? item.productName, `Item ${index + 1} name`), qty, cost, discount, taxRate, tax, total: roundMoney(base + tax) };
  });
}
function calculateTotals(items:any[],input:any){const subtotal=roundMoney(items.reduce((s,i)=>s+i.qty*i.cost,0));const discount=roundMoney(numberValue(input.discount,items.reduce((s,i)=>s+i.discount,0)));const tax=roundMoney(numberValue(input.tax,items.reduce((s,i)=>s+i.tax,0)));const total=roundMoney(numberValue(input.total,subtotal-discount+tax));const paid=Math.min(total,Math.max(0,roundMoney(numberValue(input.paid))));return{subtotal,discount,tax,total,paid,balance:roundMoney(total-paid)};}
async function resolveSupplier(tx:any,businessId:string,input:any){const supplierId=cleanString(input.supplierId);if(supplierId){const row=await tx.supplier.findFirst({where:{id:supplierId,businessId,active:true}});if(!row)throw new ApiError(400,"Selected supplier is invalid");return row;}const name=requireText(input.supplierName,"Supplier");let row=await tx.supplier.findFirst({where:{businessId,name:{equals:name,mode:"insensitive"},active:true}});if(!row)row=await tx.supplier.create({data:{businessId,name,active:true}});return row;}
async function resolveWarehouse(tx:any,businessId:string,warehouseIdInput:any,branchId?:string|null){const id=cleanString(warehouseIdInput);if(id){const row=await tx.warehouse.findFirst({where:{id,businessId,active:true}});if(!row)throw new ApiError(400,"Selected warehouse is invalid");return row;}let row=await tx.warehouse.findFirst({where:{businessId,active:true,...(branchId?{OR:[{branchId},{branchId:null}]}:{})},orderBy:{createdAt:"asc"}});if(!row)row=await tx.warehouse.create({data:{businessId,name:"Main Warehouse",code:"MAIN",branchId:branchId||null,active:true}});return row;}
function formatPurchase(row:any){return plain({...row,status:String(row.status).toLowerCase(),purchaseDate:row.purchaseDate,items:row.items||[],amount:Number(row.total),paidAmount:Number(row.paid),balanceAmount:Number(row.balance)});}

export async function listPurchases(businessId:string,query:any){const where:any={businessId};if(cleanString(query.supplierId))where.supplierId=cleanString(query.supplierId);if(cleanString(query.status))where.status=String(query.status).toUpperCase();const {from,to}=dateRange(query.from,query.to,365);if(query.from||query.to)where.purchaseDate={gte:from,lte:to};const rows=await prisma.purchase.findMany({where,include:{items:true,goodsReceipts:{include:{items:true}},returns:{include:{items:true}}},orderBy:{purchaseDate:"desc"},take:Math.min(500,numberValue(query.limit,200))});return rows.map(formatPurchase);}
export async function getPurchase(businessId:string,id:string){const row=await prisma.purchase.findFirst({where:{businessId,OR:[{id},{purchaseNo:id}]},include:{items:true,goodsReceipts:{include:{items:true}},returns:{include:{items:true}}}});if(!row)throw new ApiError(404,"Purchase not found");return formatPurchase(row);}
export async function createPurchase(req:Request,businessId:string,userId:string|null,input:any){const items=normalizeItems(input.items);return prisma.$transaction(async tx=>{const supplier=await resolveSupplier(tx,businessId,input);const branchId=cleanString(input.branchId)||null;const warehouse=await resolveWarehouse(tx,businessId,input.warehouseId,branchId);const totals=calculateTotals(items,input);const purchaseNo=cleanString(input.purchaseNo)||await nextEntityNumber(tx,"purchase","purchaseNo",businessId,"PO");const status=String(input.status||"DRAFT").toUpperCase()==="POSTED"?"POSTED":"DRAFT";const row=await tx.purchase.create({data:{businessId,branchId,warehouseId:warehouse.id,purchaseNo,supplierId:supplier.id,supplierName:supplier.name,authorizedBy:cleanString(input.authorizedBy)||null,referenceNo:cleanString(input.referenceNo)||null,dueDate:dateValue(input.dueDate)||null,purchaseDate:dateValue(input.purchaseDate)||new Date(),...totals,status,metadata:input.metadata&&typeof input.metadata==="object"?input.metadata:undefined,items:{create:items.map(i=>({businessId,...i}))}},include:{items:true}});if(status==="POSTED")await postPurchaseStock(tx,req,businessId,userId,row,warehouse.id);await writeAudit(tx,req,{businessId,userId,action:"purchase.create",entityType:"Purchase",entityId:row.id,after:plain(row)});return formatPurchase(row);});}
export async function updatePurchase(req:Request,businessId:string,userId:string|null,id:string,input:any){return prisma.$transaction(async tx=>{const before=await tx.purchase.findFirst({where:{id,businessId},include:{items:true}});if(!before)throw new ApiError(404,"Purchase not found");if(before.status==="POSTED")throw new ApiError(409,"Posted purchase cannot be edited");const items=input.items?normalizeItems(input.items):before.items.map((i:any)=>({productId:i.productId,sku:i.sku,barcode:i.barcode,name:i.name,qty:Number(i.qty),cost:Number(i.cost),discount:Number(i.discount),taxRate:Number(i.taxRate),tax:Number(i.tax),total:Number(i.total)}));const supplier=input.supplierId||input.supplierName?await resolveSupplier(tx,businessId,input):null;const totals=calculateTotals(items,{...before,...input});await tx.purchaseItem.deleteMany({where:{purchaseId:id,businessId}});const row=await tx.purchase.update({where:{id},data:{...(supplier?{supplierId:supplier.id,supplierName:supplier.name}:{}),...(input.branchId!==undefined?{branchId:cleanString(input.branchId)||null}:{}),...(input.warehouseId!==undefined?{warehouseId:(await resolveWarehouse(tx,businessId,input.warehouseId,cleanString(input.branchId)||before.branchId)).id}:{}),...(input.referenceNo!==undefined?{referenceNo:cleanString(input.referenceNo)||null}:{}),...(input.dueDate!==undefined?{dueDate:dateValue(input.dueDate)||null}:{}),...(input.purchaseDate!==undefined?{purchaseDate:dateValue(input.purchaseDate)||before.purchaseDate}:{}),...totals,items:{create:items.map(i=>({businessId,...i}))}},include:{items:true}});await writeAudit(tx,req,{businessId,userId,action:"purchase.update",entityType:"Purchase",entityId:id,before:plain(before),after:plain(row)});return formatPurchase(row);});}
async function postPurchaseStock(tx:any,req:Request,businessId:string,userId:string|null,purchase:any,warehouseId:string){if(purchase.status==="POSTED"&&purchase.receivedAt)return;const items=purchase.items||await tx.purchaseItem.findMany({where:{purchaseId:purchase.id,businessId}});for(const item of items){if(!item.productId)continue;const product=await tx.product.findFirst({where:{id:item.productId,businessId,deleted:false}});if(!product)continue;const current=await tx.inventoryStock.findUnique({where:{businessId_productId_warehouseId:{businessId,productId:product.id,warehouseId}}});const beforeQty=Number(current?.qtyOnHand||0);const qty=Number(item.qty);await tx.inventoryStock.upsert({where:{businessId_productId_warehouseId:{businessId,productId:product.id,warehouseId}},create:{businessId,productId:product.id,warehouseId,qtyOnHand:qty},update:{qtyOnHand:{increment:qty}}});await tx.product.update({where:{id:product.id},data:{currentStock:{increment:qty},costPrice:Number(item.cost)}});await tx.stockMovement.create({data:{businessId,movementNo:await nextEntityNumber(tx,"stockMovement","movementNo",businessId,"MOV"),productId:product.id,sku:product.sku,productName:product.name,warehouseId,direction:"IN",movementType:"PURCHASE_RECEIPT",referenceNo:purchase.purchaseNo,qty,beforeQty,afterQty:beforeQty+qty,source:"purchases",metadata:{purchaseId:purchase.id}}});}
await tx.purchase.update({where:{id:purchase.id},data:{status:"POSTED",receivedAt:new Date(),warehouseId}});if(purchase.supplierId)await tx.supplier.update({where:{id:purchase.supplierId},data:{balance:{increment:Number(purchase.balance)}}});await writeAudit(tx,req,{businessId,userId,action:"purchase.receive",entityType:"Purchase",entityId:purchase.id,after:{warehouseId,total:Number(purchase.total)}});}
export async function receivePurchase(req:Request,businessId:string,userId:string|null,id:string,input:any){return prisma.$transaction(async tx=>{const purchase=await tx.purchase.findFirst({where:{businessId,OR:[{id},{purchaseNo:id}]},include:{items:true}});if(!purchase)throw new ApiError(404,"Purchase not found");if(purchase.status==="POSTED"&&purchase.receivedAt)return formatPurchase(purchase);const warehouse=await resolveWarehouse(tx,businessId,input.warehouseId||purchase.warehouseId,purchase.branchId);await postPurchaseStock(tx,req,businessId,userId,purchase,warehouse.id);const row=await tx.purchase.findUnique({where:{id:purchase.id},include:{items:true,goodsReceipts:{include:{items:true}}}});const receiptNo=cleanString(input.receiptNo)||await nextEntityNumber(tx,"goodsReceipt","receiptNo",businessId,"GRN");const existing=await tx.goodsReceipt.findFirst({where:{businessId,purchaseId:purchase.id}});if(!existing){await tx.goodsReceipt.create({data:{businessId,purchaseId:purchase.id,receiptNo,warehouseId:warehouse.id,receivedByUserId:userId,notes:cleanString(input.notes)||null,items:{create:purchase.items.map((i:any)=>({businessId,productId:i.productId,sku:i.sku,productName:i.name,qty:i.qty,cost:i.cost}))}}});}return formatPurchase(row);});}
export async function cancelPurchase(req:Request,businessId:string,userId:string|null,id:string){return prisma.$transaction(async tx=>{const before=await tx.purchase.findFirst({where:{id,businessId}});if(!before)throw new ApiError(404,"Purchase not found");if(before.status==="POSTED")throw new ApiError(409,"Received purchase cannot be cancelled from this endpoint");const row=await tx.purchase.update({where:{id},data:{status:"CANCELLED"}});await writeAudit(tx,req,{businessId,userId,action:"purchase.cancel",entityType:"Purchase",entityId:id,before:plain(before),after:plain(row)});return formatPurchase(row);});}

export async function listPurchaseRequests(businessId:string){return plain(await prisma.purchaseRequest.findMany({where:{businessId},orderBy:{createdAt:"desc"}}));}
export async function createPurchaseRequest(req:Request,businessId:string,userId:string|null,input:any){return prisma.$transaction(async tx=>{const row=await tx.purchaseRequest.create({data:{businessId,requestNo:cleanString(input.requestNo)||await nextEntityNumber(tx,"purchaseRequest","requestNo",businessId,"PR"),itemName:requireText(input.itemName||input.item,"Item"),qty:Math.max(.001,numberValue(input.qty,1)),requestedByUserId:userId,notes:cleanString(input.notes)||null}});await writeAudit(tx,req,{businessId,userId,action:"purchase_request.create",entityType:"PurchaseRequest",entityId:row.id,after:plain(row)});return plain(row);});}
export async function convertPurchaseRequest(req:Request,businessId:string,userId:string|null,id:string,input:any){return prisma.$transaction(async tx=>{const request=await tx.purchaseRequest.findFirst({where:{id,businessId}});if(!request)throw new ApiError(404,"Purchase request not found");if(request.purchaseId){const existing=await tx.purchase.findFirst({where:{id:request.purchaseId,businessId},include:{items:true}});return formatPurchase(existing);}
const supplier=await resolveSupplier(tx,businessId,{supplierId:input.supplierId,supplierName:input.supplierName||"Unassigned Supplier"});const warehouse=await resolveWarehouse(tx,businessId,input.warehouseId,null);let product=null;if(cleanString(input.productId))product=await tx.product.findFirst({where:{id:cleanString(input.productId),businessId}});if(!product)product=await tx.product.findFirst({where:{businessId,name:{contains:request.itemName,mode:"insensitive"},deleted:false}});const item={productId:product?.id||null,sku:product?.sku||null,barcode:product?.barcode||null,name:request.itemName,qty:Number(request.qty),cost:numberValue(input.cost,Number(product?.costPrice||0)),discount:0,taxRate:0,tax:0,total:roundMoney(Number(request.qty)*numberValue(input.cost,Number(product?.costPrice||0)))};const total=item.total;const purchase=await tx.purchase.create({data:{businessId,warehouseId:warehouse.id,purchaseNo:await nextEntityNumber(tx,"purchase","purchaseNo",businessId,"PO"),supplierId:supplier.id,supplierName:supplier.name,subtotal:total,total,balance:total,status:"DRAFT",items:{create:{businessId,...item}}},include:{items:true}});await tx.purchaseRequest.update({where:{id},data:{status:"converted",purchaseId:purchase.id}});await writeAudit(tx,req,{businessId,userId,action:"purchase_request.convert",entityType:"PurchaseRequest",entityId:id,after:{purchaseId:purchase.id,purchaseNo:purchase.purchaseNo}});return formatPurchase(purchase);});}
export async function listGoodsReceipts(businessId:string){return plain(await prisma.goodsReceipt.findMany({where:{businessId},include:{items:true,purchase:true},orderBy:{receivedAt:"desc"}}));}

export async function listSupplierPayments(businessId:string,query:any){return plain(await prisma.supplierPayment.findMany({where:{businessId,...(cleanString(query.supplierId)?{supplierId:cleanString(query.supplierId)}:{})},orderBy:{paymentDate:"desc"},take:300}));}
export async function createSupplierPayment(req:Request,businessId:string,userId:string|null,input:any){const amount=roundMoney(numberValue(input.amount));if(amount<=0)throw new ApiError(400,"Payment amount must be greater than zero");return prisma.$transaction(async tx=>{const supplier=await resolveSupplier(tx,businessId,input);const allocations=Array.isArray(input.allocations)?input.allocations:[];let allocated=0;const normalized=[];for(const a of allocations){const purchaseId=cleanString(a.purchaseId||a.id);const pay=roundMoney(numberValue(a.amount||a.payNow));if(!purchaseId||pay<=0)continue;const purchase=await tx.purchase.findFirst({where:{id:purchaseId,businessId,supplierId:supplier.id}});if(!purchase)throw new ApiError(400,"One selected purchase does not belong to this supplier");const applied=Math.min(pay,Number(purchase.balance));if(applied<=0)continue;await tx.purchase.update({where:{id:purchase.id},data:{paid:{increment:applied},balance:{decrement:applied}}});allocated=roundMoney(allocated+applied);normalized.push({purchaseId:purchase.id,purchaseNo:purchase.purchaseNo,amount:applied});}
const voucherNo=cleanString(input.voucherNo)||await nextEntityNumber(tx,"supplierPayment","voucherNo",businessId,"SPAY");const row=await tx.supplierPayment.create({data:{businessId,voucherNo,supplierId:supplier.id,supplierName:supplier.name,amount,method:cleanString(input.method)||null,accountId:cleanString(input.accountId)||null,referenceNo:cleanString(input.referenceNo)||null,allocation:{allocations:normalized,allocated,unallocated:roundMoney(amount-allocated)},paymentDate:dateValue(input.paymentDate)||new Date()}});await tx.supplier.update({where:{id:supplier.id},data:{balance:{decrement:amount}}});if(cleanString(input.accountId)){const account=await tx.account.findFirst({where:{id:cleanString(input.accountId),businessId}});if(account){await tx.account.update({where:{id:account.id},data:{currentBalance:{decrement:amount}}});await tx.accountTransaction.create({data:{businessId,accountId:account.id,type:"debit",amount,referenceNo:voucherNo,description:`Supplier payment to ${supplier.name}`,transactionDate:dateValue(input.paymentDate)||new Date(),sourceType:"supplier_payment",sourceId:row.id,createdByUserId:userId}});}}
await writeAudit(tx,req,{businessId,userId,action:"supplier_payment.create",entityType:"SupplierPayment",entityId:row.id,after:plain(row)});return plain(row);});}
export async function supplierStatement(businessId:string,supplierId:string,query:any){const supplier=await prisma.supplier.findFirst({where:{id:supplierId,businessId}});if(!supplier)throw new ApiError(404,"Supplier not found");const {from,to}=dateRange(query.from,query.to,365);const [purchases,payments]=await Promise.all([prisma.purchase.findMany({where:{businessId,supplierId,status:"POSTED",purchaseDate:{gte:from,lte:to}},orderBy:{purchaseDate:"asc"}}),prisma.supplierPayment.findMany({where:{businessId,supplierId,paymentDate:{gte:from,lte:to}},orderBy:{paymentDate:"asc"}})]);const entries=[...purchases.map(p=>({date:p.purchaseDate,ref:p.purchaseNo,debit:0,credit:Number(p.total),type:"purchase"})),...payments.map(p=>({date:p.paymentDate,ref:p.voucherNo,debit:Number(p.amount),credit:0,type:"payment"}))].sort((a,b)=>a.date.getTime()-b.date.getTime());let balance=Number(supplier.openingBalance);const rows=entries.map(e=>{balance=roundMoney(balance+e.credit-e.debit);return{...e,balance};});return plain({supplier,from,to,rows,totals:{debit:roundMoney(rows.reduce((s,r)=>s+r.debit,0)),credit:roundMoney(rows.reduce((s,r)=>s+r.credit,0)),closingBalance:balance}});}

export async function createPurchaseReturn(req:Request,businessId:string,userId:string|null,input:any){const items=normalizeItems(input.items||[{name:input.item||"Returned items",qty:input.qty||1,cost:input.cost||0,productId:input.productId,sku:input.sku}]);return prisma.$transaction(async tx=>{const purchaseId=cleanString(input.purchaseId)||null;const purchase=purchaseId?await tx.purchase.findFirst({where:{id:purchaseId,businessId}}):null;const supplier=await resolveSupplier(tx,businessId,{supplierId:input.supplierId||purchase?.supplierId,supplierName:input.supplierName||purchase?.supplierName||"Supplier"});const warehouse=await resolveWarehouse(tx,businessId,input.warehouseId||purchase?.warehouseId,purchase?.branchId);const total=roundMoney(items.reduce((s,i)=>s+i.total,0));const row=await tx.purchaseReturn.create({data:{businessId,purchaseId:purchase?.id||null,returnNo:cleanString(input.returnNo)||await nextEntityNumber(tx,"purchaseReturn","returnNo",businessId,"PRET"),supplierId:supplier.id,supplierName:supplier.name,warehouseId:warehouse.id,total,reason:cleanString(input.reason)||null,createdByUserId:userId,items:{create:items.map(i=>({businessId,productId:i.productId,sku:i.sku,productName:i.name,qty:i.qty,cost:i.cost,total:i.total}))}},include:{items:true}});for(const item of items){if(!item.productId)continue;const stock=await tx.inventoryStock.findUnique({where:{businessId_productId_warehouseId:{businessId,productId:item.productId,warehouseId:warehouse.id}}});const before=Number(stock?.qtyOnHand||0);if(before<item.qty)throw new ApiError(409,`Insufficient stock to return ${item.name}`);await tx.inventoryStock.update({where:{businessId_productId_warehouseId:{businessId,productId:item.productId,warehouseId:warehouse.id}},data:{qtyOnHand:{decrement:item.qty}}});await tx.product.update({where:{id:item.productId},data:{currentStock:{decrement:item.qty}}});await tx.stockMovement.create({data:{businessId,movementNo:await nextEntityNumber(tx,"stockMovement","movementNo",businessId,"MOV"),productId:item.productId,sku:item.sku,productName:item.name,warehouseId:warehouse.id,direction:"OUT",movementType:"PURCHASE_RETURN",referenceNo:row.returnNo,qty:item.qty,beforeQty:before,afterQty:before-item.qty,source:"purchase_return",metadata:{purchaseReturnId:row.id}}});}await tx.supplier.update({where:{id:supplier.id},data:{balance:{decrement:total}}});await writeAudit(tx,req,{businessId,userId,action:"purchase_return.create",entityType:"PurchaseReturn",entityId:row.id,after:plain(row)});return plain(row);});}
export async function listPurchaseReturns(businessId:string){return plain(await prisma.purchaseReturn.findMany({where:{businessId},include:{items:true},orderBy:{returnDate:"desc"}}));}
