-- Release C checkpoint 2 additive operational tables
CREATE TABLE "restaurant_reservations" ("id" TEXT PRIMARY KEY,"business_id" TEXT NOT NULL,"reservation_no" TEXT NOT NULL,"table_id" TEXT,"customer_name" TEXT NOT NULL,"phone" TEXT,"party_size" INTEGER NOT NULL,"reserved_at" TIMESTAMP(3) NOT NULL,"status" TEXT NOT NULL DEFAULT 'booked',"notes" TEXT,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "restaurant_reservations_business_id_reservation_no_key" ON "restaurant_reservations"("business_id","reservation_no"); CREATE INDEX "restaurant_reservations_business_id_reserved_at_status_idx" ON "restaurant_reservations"("business_id","reserved_at","status");
CREATE TABLE "restaurant_modifier_groups" ("id" TEXT PRIMARY KEY,"business_id" TEXT NOT NULL,"name" TEXT NOT NULL,"required" BOOLEAN NOT NULL DEFAULT false,"min_select" INTEGER NOT NULL DEFAULT 0,"max_select" INTEGER NOT NULL DEFAULT 1,"active" BOOLEAN NOT NULL DEFAULT true); CREATE UNIQUE INDEX "restaurant_modifier_groups_business_id_name_key" ON "restaurant_modifier_groups"("business_id","name");
CREATE TABLE "restaurant_modifiers" ("id" TEXT PRIMARY KEY,"business_id" TEXT NOT NULL,"group_id" TEXT NOT NULL,"name" TEXT NOT NULL,"price_delta" DECIMAL(14,2) NOT NULL DEFAULT 0,"active" BOOLEAN NOT NULL DEFAULT true); CREATE UNIQUE INDEX "restaurant_modifiers_business_id_group_id_name_key" ON "restaurant_modifiers"("business_id","group_id","name");
CREATE TABLE "restaurant_recipes" ("id" TEXT PRIMARY KEY,"business_id" TEXT NOT NULL,"menu_item_id" TEXT NOT NULL,"yield_quantity" DECIMAL(14,3) NOT NULL DEFAULT 1,"active" BOOLEAN NOT NULL DEFAULT true); CREATE UNIQUE INDEX "restaurant_recipes_business_id_menu_item_id_key" ON "restaurant_recipes"("business_id","menu_item_id");
CREATE TABLE "restaurant_recipe_ingredients" ("id" TEXT PRIMARY KEY,"business_id" TEXT NOT NULL,"recipe_id" TEXT NOT NULL,"product_id" TEXT NOT NULL,"quantity" DECIMAL(14,4) NOT NULL,"unit" TEXT NOT NULL); CREATE UNIQUE INDEX "restaurant_recipe_ingredients_business_id_recipe_id_product_id_key" ON "restaurant_recipe_ingredients"("business_id","recipe_id","product_id");
CREATE TABLE "restaurant_wastage" ("id" TEXT PRIMARY KEY,"business_id" TEXT NOT NULL,"product_id" TEXT NOT NULL,"quantity" DECIMAL(14,3) NOT NULL,"unit" TEXT NOT NULL,"reason" TEXT NOT NULL,"posted_by" TEXT,"posted_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"reversed_at" TIMESTAMP(3),"idempotency_key" TEXT); CREATE UNIQUE INDEX "restaurant_wastage_business_id_idempotency_key_key" ON "restaurant_wastage"("business_id","idempotency_key"); CREATE INDEX "restaurant_wastage_business_id_posted_at_idx" ON "restaurant_wastage"("business_id","posted_at");
CREATE TABLE "hardware_quotations" ("id" TEXT PRIMARY KEY,"business_id" TEXT NOT NULL,"quotation_no" TEXT NOT NULL,"customer_id" TEXT NOT NULL,"project_id" TEXT,"lpo_no" TEXT,"subtotal" DECIMAL(14,2) NOT NULL DEFAULT 0,"discount" DECIMAL(14,2) NOT NULL DEFAULT 0,"total" DECIMAL(14,2) NOT NULL DEFAULT 0,"status" TEXT NOT NULL DEFAULT 'draft',"valid_until" TIMESTAMP(3),"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"idempotency_key" TEXT); CREATE UNIQUE INDEX "hardware_quotations_business_id_quotation_no_key" ON "hardware_quotations"("business_id","quotation_no"); CREATE UNIQUE INDEX "hardware_quotations_business_id_idempotency_key_key" ON "hardware_quotations"("business_id","idempotency_key"); CREATE INDEX "hardware_quotations_business_id_status_created_at_idx" ON "hardware_quotations"("business_id","status","created_at");
CREATE TABLE "hardware_quotation_items" ("id" TEXT PRIMARY KEY,"business_id" TEXT NOT NULL,"quotation_id" TEXT NOT NULL,"product_id" TEXT NOT NULL,"description" TEXT NOT NULL,"quantity" DECIMAL(14,3) NOT NULL,"unit" TEXT NOT NULL,"cut_length" DECIMAL(14,3),"unit_price" DECIMAL(14,2) NOT NULL,"line_total" DECIMAL(14,2) NOT NULL); CREATE INDEX "hardware_quotation_items_business_id_quotation_id_idx" ON "hardware_quotation_items"("business_id","quotation_id");
CREATE TABLE "hardware_delivery_items" ("id" TEXT PRIMARY KEY,"business_id" TEXT NOT NULL,"delivery_id" TEXT NOT NULL,"product_id" TEXT NOT NULL,"ordered_quantity" DECIMAL(14,3) NOT NULL,"delivered_quantity" DECIMAL(14,3) NOT NULL DEFAULT 0,"unit" TEXT NOT NULL); CREATE INDEX "hardware_delivery_items_business_id_delivery_id_idx" ON "hardware_delivery_items"("business_id","delivery_id");
CREATE TABLE "hardware_warranty_records" ("id" TEXT PRIMARY KEY,"business_id" TEXT NOT NULL,"product_id" TEXT NOT NULL,"customer_id" TEXT NOT NULL,"serial_no" TEXT,"invoice_no" TEXT,"starts_at" TIMESTAMP(3) NOT NULL,"expires_at" TIMESTAMP(3) NOT NULL,"status" TEXT NOT NULL DEFAULT 'active',"notes" TEXT); CREATE INDEX "hardware_warranty_records_business_id_status_expires_at_idx" ON "hardware_warranty_records"("business_id","status","expires_at");
CREATE TABLE "paint_component_stock" ("id" TEXT PRIMARY KEY,"business_id" TEXT NOT NULL,"component_code" TEXT NOT NULL,"component_name" TEXT NOT NULL,"quantity_on_hand" DECIMAL(16,4) NOT NULL DEFAULT 0,"unit" TEXT NOT NULL,"average_cost" DECIMAL(14,4) NOT NULL DEFAULT 0,"minimum_stock" DECIMAL(16,4) NOT NULL DEFAULT 0,"active" BOOLEAN NOT NULL DEFAULT true); CREATE UNIQUE INDEX "paint_component_stock_business_id_component_code_key" ON "paint_component_stock"("business_id","component_code");
CREATE TABLE "paint_mix_labels" ("id" TEXT PRIMARY KEY,"business_id" TEXT NOT NULL,"mix_job_id" TEXT NOT NULL,"label_no" TEXT NOT NULL,"printed_at" TIMESTAMP(3),"print_count" INTEGER NOT NULL DEFAULT 0); CREATE UNIQUE INDEX "paint_mix_labels_business_id_label_no_key" ON "paint_mix_labels"("business_id","label_no"); CREATE UNIQUE INDEX "paint_mix_labels_business_id_mix_job_id_key" ON "paint_mix_labels"("business_id","mix_job_id");
CREATE TABLE "release_c_notification_rules" ("id" TEXT PRIMARY KEY,"business_id" TEXT NOT NULL,"industry" TEXT NOT NULL,"event_key" TEXT NOT NULL,"channel" TEXT NOT NULL DEFAULT 'in_app',"days_before" INTEGER NOT NULL DEFAULT 0,"active" BOOLEAN NOT NULL DEFAULT true); CREATE UNIQUE INDEX "release_c_notification_rules_business_id_industry_event_key_channel_key" ON "release_c_notification_rules"("business_id","industry","event_key","channel"); CREATE INDEX "release_c_notification_rules_business_id_industry_active_idx" ON "release_c_notification_rules"("business_id","industry","active");
