import type { Request } from "express";
import { prisma } from "../db/prisma.js";
import { writeAudit } from "./audit.service.js";
import { ApiError, booleanValue, cleanString, numberValue, plain, requireText } from "../utils/http.js";

export async function listSuppliers(businessId: string, query: any) {
  const q=cleanString(query.q); const active=query.active===undefined?undefined:booleanValue(query.active,true);
  const rows=await prisma.supplier.findMany({where:{businessId,...(active===undefined?{}:{active}),...(q?{OR:[{name:{contains:q,mode:"insensitive"}},{company:{contains:q,mode:"insensitive"}},{phone:{contains:q,mode:"insensitive"}},{email:{contains:q,mode:"insensitive"}}]}:{})},orderBy:{name:"asc"}});
  return plain(rows);
}
export async function getSupplier(businessId:string,id:string){const row=await prisma.supplier.findFirst({where:{id,businessId}});if(!row)throw new ApiError(404,"Supplier not found");return plain(row);}
export async function createSupplier(req:Request,businessId:string,userId:string|null,input:any){return prisma.$transaction(async tx=>{const row=await tx.supplier.create({data:{businessId,name:requireText(input.name,"Supplier name"),company:cleanString(input.company)||null,phone:cleanString(input.phone)||null,email:cleanString(input.email)||null,address:cleanString(input.address)||null,creditDays:Math.max(0,Math.floor(numberValue(input.creditDays,30))),openingBalance:numberValue(input.openingBalance),balance:numberValue(input.balance,input.openingBalance),active:booleanValue(input.active,true)}});await writeAudit(tx,req,{businessId,userId,action:"supplier.create",entityType:"Supplier",entityId:row.id,after:plain(row)});return plain(row);});}
export async function updateSupplier(req:Request,businessId:string,userId:string|null,id:string,input:any){return prisma.$transaction(async tx=>{const before=await tx.supplier.findFirst({where:{id,businessId}});if(!before)throw new ApiError(404,"Supplier not found");const row=await tx.supplier.update({where:{id},data:{...(input.name!==undefined?{name:requireText(input.name,"Supplier name")}:{}) ,...(input.company!==undefined?{company:cleanString(input.company)||null}:{}),...(input.phone!==undefined?{phone:cleanString(input.phone)||null}:{}),...(input.email!==undefined?{email:cleanString(input.email)||null}:{}),...(input.address!==undefined?{address:cleanString(input.address)||null}:{}),...(input.creditDays!==undefined?{creditDays:Math.max(0,Math.floor(numberValue(input.creditDays,30)))}:{}),...(input.openingBalance!==undefined?{openingBalance:numberValue(input.openingBalance)}:{}),...(input.balance!==undefined?{balance:numberValue(input.balance)}:{}),...(input.active!==undefined?{active:booleanValue(input.active,before.active)}:{})}});await writeAudit(tx,req,{businessId,userId,action:"supplier.update",entityType:"Supplier",entityId:id,before:plain(before),after:plain(row)});return plain(row);});}
export async function deleteSupplier(req:Request,businessId:string,userId:string|null,id:string){return prisma.$transaction(async tx=>{const before=await tx.supplier.findFirst({where:{id,businessId}});if(!before)throw new ApiError(404,"Supplier not found");const row=await tx.supplier.update({where:{id},data:{active:false}});await writeAudit(tx,req,{businessId,userId,action:"supplier.deactivate",entityType:"Supplier",entityId:id,before:plain(before),after:plain(row)});return plain(row);});}
