import type { Request } from "express";
import { prisma } from "../db/prisma.js";
import { writeAudit } from "./audit.service.js";
import { nextEntityNumber } from "./numbering.service.js";
import { ApiError, booleanValue, cleanString, dateRange, numberValue, plain, requireText, roundMoney, roundQty } from "../utils/http.js";
import { assertUsageLimit } from "./entitlements.service.js";

async function findProduct(tx:any,businessId:string,input:any){const id=cleanString(input.productId);let p=id?await tx.product.findFirst({where:{id,businessId,deleted:false}}):null;const q=cleanString(input.sku||input.barcode||input.q||input.product);if(!p&&q)p=await tx.product.findFirst({where:{businessId,deleted:false,OR:[{sku:{equals:q,mode:"insensitive"}},{barcode:q},{qrCode:q},{name:{contains:q,mode:"insensitive"}}]}});if(!p)throw new ApiError(404,"Product not found");return p;}
async function findWarehouse(tx:any,businessId:string,value:any){const id=cleanString(value);if(!id)throw new ApiError(400,"Warehouse is required");const row=await tx.warehouse.findFirst({where:{businessId,OR:[{id},{name:{equals:id,mode:"insensitive"}}],active:true}});if(!row)throw new ApiError(404,"Warehouse not found");return row;}
async function stockQty(tx:any,businessId:string,productId:string,warehouseId:string){const row=await tx.inventoryStock.findUnique({where:{businessId_productId_warehouseId:{businessId,productId,warehouseId}}});return Number(row?.qtyOnHand||0);}
async function applyDelta(tx:any,businessId:string,product:any,warehouseId:string,delta:number){const before=await stockQty(tx,businessId,product.id,warehouseId);const after=roundQty(before+delta);if(after<0)throw new ApiError(409,`Insufficient stock for ${product.name}`);await tx.inventoryStock.upsert({where:{businessId_productId_warehouseId:{businessId,productId:product.id,warehouseId}},create:{businessId,productId:product.id,warehouseId,qtyOnHand:after},update:{qtyOnHand:after}});await tx.product.update({where:{id:product.id},data:{currentStock:{increment:delta}}});return{before,after};}

export async function listWarehouses(businessId:string,query:any){return plain(await prisma.warehouse.findMany({where:{businessId,...(query.active===undefined?{}:{active:booleanValue(query.active,true)}),...(cleanString(query.branchId)?{branchId:cleanString(query.branchId)}:{})},include:{branch:true},orderBy:{name:"asc"}}));}
export async function createWarehouse(req:Request,businessId:string,userId:string|null,input:any){return prisma.$transaction(async tx=>{await assertUsageLimit(tx,businessId,"warehouses");const branchId=cleanString(input.branchId)||null;if(branchId&&!await tx.branch.findFirst({where:{id:branchId,businessId}}))throw new ApiError(400,"Invalid branch");const row=await tx.warehouse.create({data:{businessId,branchId,name:requireText(input.name,"Warehouse name"),code:cleanString(input.code)||null,address:cleanString(input.address||input.location)||null,mapUrl:cleanString(input.mapUrl)||null,active:booleanValue(input.active,true)}});await writeAudit(tx,req,{businessId,userId,action:"warehouse.create",entityType:"Warehouse",entityId:row.id,after:plain(row)});return plain(row);});}
export async function updateWarehouse(req:Request,businessId:string,userId:string|null,id:string,input:any){return prisma.$transaction(async tx=>{const before=await tx.warehouse.findFirst({where:{id,businessId}});if(!before)throw new ApiError(404,"Warehouse not found");const branchId=input.branchId===undefined?before.branchId:cleanString(input.branchId)||null;if(branchId&&!await tx.branch.findFirst({where:{id:branchId,businessId}}))throw new ApiError(400,"Invalid branch");const row=await tx.warehouse.update({where:{id},data:{...(input.name!==undefined?{name:requireText(input.name,"Warehouse name")}:{}) ,...(input.code!==undefined?{code:cleanString(input.code)||null}:{}),...(input.address!==undefined||input.location!==undefined?{address:cleanString(input.address||input.location)||null}:{}),...(input.mapUrl!==undefined?{mapUrl:cleanString(input.mapUrl)||null}:{}),...(input.branchId!==undefined?{branchId}:{}),...(input.active!==undefined?{active:booleanValue(input.active,before.active)}:{})}});await writeAudit(tx,req,{businessId,userId,action:"warehouse.update",entityType:"Warehouse",entityId:id,before:plain(before),after:plain(row)});return plain(row);});}
export async function deleteWarehouse(req:Request,businessId:string,userId:string|null,id:string){return prisma.$transaction(async tx=>{const before=await tx.warehouse.findFirst({where:{id,businessId}});if(!before)throw new ApiError(404,"Warehouse not found");const nonzero=await tx.inventoryStock.count({where:{businessId,warehouseId:id,qtyOnHand:{not:0}}});if(nonzero)throw new ApiError(409,"Warehouse has stock and cannot be deactivated");const row=await tx.warehouse.update({where:{id},data:{active:false}});await writeAudit(tx,req,{businessId,userId,action:"warehouse.deactivate",entityType:"Warehouse",entityId:id,before:plain(before),after:plain(row)});return plain(row);});}

export async function listStock(businessId:string,query:any){const warehouseId=cleanString(query.warehouseId);const productWhere:any={businessId,deleted:false,active:true};const q=cleanString(query.q);if(q)productWhere.OR=[{name:{contains:q,mode:"insensitive"}},{sku:{contains:q,mode:"insensitive"}},{barcode:{contains:q,mode:"insensitive"}}];const products=await prisma.product.findMany({where:productWhere,orderBy:{name:"asc"},take:500});const ids=products.map(p=>p.id);const stocks=ids.length?await prisma.inventoryStock.findMany({where:{businessId,productId:{in:ids},...(warehouseId?{warehouseId}:{})}}):[];const warehouses=await prisma.warehouse.findMany({where:{businessId},select:{id:true,name:true}});const warehouseMap=new Map(warehouses.map(w=>[w.id,w.name]));const byProduct=new Map<string,any[]>();stocks.forEach(s=>{const arr=byProduct.get(s.productId)||[];arr.push(s);byProduct.set(s.productId,arr);});return plain(products.map(p=>{const rows=byProduct.get(p.id)||[];const qty=rows.reduce((sum,s)=>sum+Number(s.qtyOnHand),0);return{...p,currentStock:qty,stockValue:roundMoney(qty*Number(p.costPrice)),warehouses:rows.map(s=>({warehouseId:s.warehouseId,warehouseName:warehouseMap.get(s.warehouseId)||s.warehouseId,qtyOnHand:Number(s.qtyOnHand),qtyReserved:Number(s.qtyReserved) })),lowStock:qty<=Number(p.minStock)};}));}
export async function ledger(businessId:string,query:any){const{from,to}=dateRange(query.from,query.to,90);const where:any={businessId,movementDate:{gte:from,lte:to}};if(cleanString(query.productId))where.productId=cleanString(query.productId);if(cleanString(query.warehouseId))where.OR=[{warehouseId:cleanString(query.warehouseId)},{toWarehouseId:cleanString(query.warehouseId)}];return plain(await prisma.stockMovement.findMany({where,orderBy:{movementDate:"desc"},take:500}));}
export async function adjust(req:Request,businessId:string,userId:string|null,input:any){return prisma.$transaction(async tx=>{const product=await findProduct(tx,businessId,input);const warehouse=await findWarehouse(tx,businessId,input.warehouseId||input.warehouse);const current=await stockQty(tx,businessId,product.id,warehouse.id);const mode=String(input.type||input.mode||"add").toLowerCase();const qty=roundQty(numberValue(input.qty||input.quantity));if(qty<0)throw new ApiError(400,"Quantity cannot be negative");let delta=mode==="set"?qty-current:mode==="subtract"||mode==="out"?-qty:qty;const applied=await applyDelta(tx,businessId,product,warehouse.id,delta);const movement=await tx.stockMovement.create({data:{businessId,movementNo:await nextEntityNumber(tx,"stockMovement","movementNo",businessId,"MOV"),productId:product.id,sku:product.sku,productName:product.name,warehouseId:warehouse.id,direction:delta>=0?"IN":"OUT",movementType:"ADJUSTMENT",referenceNo:cleanString(input.referenceNo)||null,qty:Math.abs(delta),beforeQty:applied.before,afterQty:applied.after,source:"inventory_adjustment",movementDate:input.date?new Date(input.date):new Date(),metadata:{reason:cleanString(input.reason)||null,mode}}});await writeAudit(tx,req,{businessId,userId,action:"inventory.adjust",entityType:"StockMovement",entityId:movement.id,before:{qty:applied.before},after:{qty:applied.after}});return plain(movement);});}
export async function transfer(req:Request,businessId:string,userId:string|null,input:any){return prisma.$transaction(async tx=>{const product=await findProduct(tx,businessId,input);const from=await findWarehouse(tx,businessId,input.fromWarehouseId||input.from);const to=await findWarehouse(tx,businessId,input.toWarehouseId||input.to);if(from.id===to.id)throw new ApiError(400,"Source and destination warehouses must be different");const qty=roundQty(numberValue(input.qty||input.quantity));if(qty<=0)throw new ApiError(400,"Transfer quantity must be greater than zero");const out=await applyDelta(tx,businessId,product,from.id,-qty);const into=await applyDelta(tx,businessId,product,to.id,qty);const movement=await tx.stockMovement.create({data:{businessId,movementNo:await nextEntityNumber(tx,"stockMovement","movementNo",businessId,"TRF"),productId:product.id,sku:product.sku,productName:product.name,warehouseId:from.id,toWarehouseId:to.id,direction:"TRANSFER",movementType:"WAREHOUSE_TRANSFER",referenceNo:cleanString(input.referenceNo)||null,qty,beforeQty:out.before,afterQty:out.after,source:"inventory_transfer",metadata:{fromBefore:out.before,fromAfter:out.after,toBefore:into.before,toAfter:into.after}}});await writeAudit(tx,req,{businessId,userId,action:"inventory.transfer",entityType:"StockMovement",entityId:movement.id,after:plain(movement)});return plain({...movement,fromWarehouse:from.name,toWarehouse:to.name});});}
export async function valuation(businessId:string,query:any){const rows=await listStock(businessId,query);const total=roundMoney(rows.reduce((s:number,r:any)=>s+r.stockValue,0));return{total,rows};}
export async function lowStock(businessId:string,query:any){const rows=await listStock(businessId,query);return rows.filter((r:any)=>r.lowStock).map((r:any)=>({...r,suggestedQty:Math.max(1,Math.ceil(Number(r.minStock)*2-Number(r.currentStock)))}));}
export async function stockCountSheet(businessId:string,warehouseIdInput:string){const warehouse=await prisma.warehouse.findFirst({where:{businessId,OR:[{id:warehouseIdInput},{name:{equals:warehouseIdInput,mode:"insensitive"}}]}});if(!warehouse)throw new ApiError(404,"Warehouse not found");const products=await prisma.product.findMany({where:{businessId,deleted:false,active:true},orderBy:{name:"asc"}});const stocks=await prisma.inventoryStock.findMany({where:{businessId,warehouseId:warehouse.id}});const map=new Map(stocks.map(s=>[s.productId,Number(s.qtyOnHand)]));return plain({warehouse,items:products.map(p=>({productId:p.id,sku:p.sku,productName:p.name,systemQty:map.get(p.id)||0,countedQty:map.get(p.id)||0,difference:0}))});}
export async function approveStockCount(req:Request,businessId:string,userId:string|null,input:any){if(!Array.isArray(input.items)||!input.items.length)throw new ApiError(400,"Stock count items are required");return prisma.$transaction(async tx=>{const warehouse=await findWarehouse(tx,businessId,input.warehouseId);const count=await tx.stockCount.create({data:{businessId,warehouseId:warehouse.id,countNo:cleanString(input.countNo)||await nextEntityNumber(tx,"stockCount","countNo",businessId,"SC"),status:"approved",countedByUserId:userId,approvedByUserId:userId,approvedAt:new Date(),notes:cleanString(input.notes)||null}});for(const raw of input.items){const product=await findProduct(tx,businessId,raw);const system=await stockQty(tx,businessId,product.id,warehouse.id);const counted=roundQty(numberValue(raw.countedQty,system));const diff=roundQty(counted-system);await applyDelta(tx,businessId,product,warehouse.id,diff);await tx.stockCountItem.create({data:{businessId,stockCountId:count.id,productId:product.id,sku:product.sku,productName:product.name,systemQty:system,countedQty:counted,difference:diff}});if(diff!==0)await tx.stockMovement.create({data:{businessId,movementNo:await nextEntityNumber(tx,"stockMovement","movementNo",businessId,"MOV"),productId:product.id,sku:product.sku,productName:product.name,warehouseId:warehouse.id,direction:"ADJUSTMENT",movementType:"STOCK_COUNT",referenceNo:count.countNo,qty:Math.abs(diff),beforeQty:system,afterQty:counted,source:"stock_count",metadata:{stockCountId:count.id}}});}await writeAudit(tx,req,{businessId,userId,action:"stock_count.approve",entityType:"StockCount",entityId:count.id,after:{countNo:count.countNo,warehouseId:warehouse.id,lines:input.items.length}});return plain(await tx.stockCount.findUnique({where:{id:count.id},include:{items:true}}));});}
export async function listStockCounts(businessId:string){return plain(await prisma.stockCount.findMany({where:{businessId},include:{items:true},orderBy:{countedAt:"desc"},take:100}));}
