const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const root=path.join(__dirname,'../demo-static');
const pages=['grocery-dashboard.html','grocery-terminal.html','grocery-products.html','grocery-batches.html','grocery-expiry.html','grocery-receiving.html','grocery-waste.html','grocery-recalls.html','grocery-reports.html','grocery-settings.html'];
for(const file of pages){
  const html=fs.readFileSync(path.join(root,file),'utf8');
  assert.match(html,/grocery-app\.js/);
  assert.match(html,/data-page=/);
  assert.doesNotMatch(html,/industry\.html\?module=/);
}
const dashboardHtml=fs.readFileSync(path.join(root,'grocery-dashboard.html'),'utf8');
const terminalHtml=fs.readFileSync(path.join(root,'grocery-terminal.html'),'utf8');
const settingsHtml=fs.readFileSync(path.join(root,'grocery-settings.html'),'utf8');
const reportsHtml=fs.readFileSync(path.join(root,'grocery-reports.html'),'utf8');
assert.match(dashboardHtml,/grocery-report-sync\.js/);
assert.match(dashboardHtml,/grocery-production-readiness\.js/);
assert.match(terminalHtml,/grocery-production-readiness\.js/);
assert.match(settingsHtml,/grocery-production-readiness\.js/);
assert.match(reportsHtml,/grocery-report-sync\.js/);
assert.match(reportsHtml,/data-page="reports"/);
const app=fs.readFileSync(path.join(root,'js/grocery-app.js'),'utf8');
const readiness=fs.readFileSync(path.join(root,'js/grocery-production-readiness.js'),'utf8');
const reporting=fs.readFileSync(path.join(root,'js/grocery-report-sync.js'),'utf8');
assert.match(app,/\/api\/v1\/industry\/registry/);
assert.match(app,/\/api\/v1\/industry\/batches/);
assert.match(app,/\/api\/v1\/industry\/records/);
assert.match(app,/\/api\/v1\/sales-documents/);
assert.match(app,/Idempotency-Key/);
assert.match(app,/Grocery tenants/);
assert.match(app,/grocery_fefo_terminal/);
assert.match(app,/inventoryBatchId/);
assert.match(readiness,/POS Terminal/);
assert.match(readiness,/Sales & Returns/);
assert.match(readiness,/Users \/ Roles/);
assert.match(readiness,/Barcode \/ Scale Labels/);
assert.match(readiness,/parseScaleBarcode/);
assert.match(readiness,/weightKg/);
assert.match(readiness,/axtor:grocery:terminal:view/);
assert.match(readiness,/A4/);
assert.match(readiness,/Thermal 80mm/);
assert.match(readiness,/Thermal 58mm/);
assert.match(readiness,/Invoice & Print/);
assert.match(readiness,/Template: Modern A4 Invoice/);
assert.match(readiness,/blockCrossIndustryLinks/);
assert.match(reporting,/reportPath\("daily-sales"/);
assert.match(reporting,/sale-products/);
assert.match(reporting,/profit-loss/);
assert.match(reporting,/\/api\/v1\/reports\/options/);
assert.match(reporting,/Export CSV/);
assert.doesNotMatch(reporting,/JSON\.stringify\(report,\s*null,\s*2\)/);
console.log('PASS: Grocery branch navigation, FEFO terminal, scale parsing, persistent views, invoice output and reporting readiness');
