const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const root=path.join(__dirname,'../demo-static');
const html=fs.readFileSync(path.join(root,'invoice-view.html'),'utf8');
const routing=fs.readFileSync(path.join(root,'js/grocery-document-routing.js'),'utf8');
const settings=fs.readFileSync(path.join(root,'js/grocery-print-settings-backend.js'),'utf8');
const adapter=fs.readFileSync(path.join(root,'js/grocery-invoice-print-reconciliation.js'),'utf8');
const backend=fs.readFileSync(path.join(root,'js/invoice-view-backend.js'),'utf8');

assert.match(html,/data-industry="grocery"/);
assert.match(html,/Loading saved Grocery document/);
assert.match(html,/invoice-view-backend\.js\?v=20260804-grocery-document1/);
assert.match(html,/grocery-invoice-print-reconciliation\.js\?v=20260804-grocery-document1/);
assert.match(html,/grocery-tenant-locale\.js\?v=20260804-grocery-document1/);
assert.doesNotMatch(html,/js\/main\.js/);
assert.doesNotMatch(html,/js\/app-data\.js/);
assert.doesNotMatch(html,/js\/retail-advanced\.js/);
assert.doesNotMatch(html,/selected demo invoice template|Module Ready/);

assert.match(routing,/profile/);
assert.match(routing,/print/);
assert.match(settings,/Thermal 80mm/);
assert.match(settings,/Thermal 58mm/);
assert.match(settings,/defaultPrintSize/);
assert.match(adapter,/dedicatedGroceryPage/);
assert.match(adapter,/A4 Invoice/);
assert.match(adapter,/Thermal 80 mm/);
assert.match(adapter,/Thermal 58 mm/);
assert.match(adapter,/Counter/);
assert.match(adapter,/Terminal/);
assert.match(adapter,/Shift/);
assert.match(adapter,/Cashier/);
assert.match(adapter,/Payment/);
assert.match(adapter,/Batch:/);
assert.match(adapter,/Expiry:/);
assert.match(adapter,/sales-documents\/context/);
assert.match(adapter,/groceryDocumentReady/);
assert.match(adapter,/profile\.label/);
assert.doesNotMatch(adapter,/">" \+ profile\.label/);
assert.match(backend,/invoiceNo: documentData\.documentNo/);
assert.match(backend,/\/api\/v1\/sales-documents\//);
assert.doesNotMatch(adapter,/Demo business|Sample Product|Customer Ready Mode/);
console.log('PASS: Grocery persisted invoices render through dedicated A4, 80 mm and 58 mm document runtime');
