const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const root=path.join(__dirname,'../demo-static');
const pages=['grocery-dashboard.html','grocery-terminal.html','grocery-products.html','grocery-batches.html','grocery-expiry.html','grocery-receiving.html','grocery-waste.html','grocery-recalls.html','grocery-reports.html','grocery-settings.html'];
for(const file of pages){
  const html=fs.readFileSync(path.join(root,file),'utf8');
  assert.match(html,/grocery-app\.js/);
  assert.match(html,/data-page=/);
  assert.doesNotMatch(html,/industry\.html\?module=/);
}
const dashboardHtml=fs.readFileSync(path.join(root,'grocery-dashboard.html'),'utf8');
const reportsHtml=fs.readFileSync(path.join(root,'grocery-reports.html'),'utf8');
assert.match(dashboardHtml,/grocery-report-sync\.js/);
assert.match(reportsHtml,/grocery-report-sync\.js/);
assert.match(reportsHtml,/data-page="reports"/);
const app=fs.readFileSync(path.join(root,'js/grocery-app.js'),'utf8');
const reporting=fs.readFileSync(path.join(root,'js/grocery-report-sync.js'),'utf8');
assert.match(app,/\/api\/v1\/industry\/registry/);
assert.match(app,/\/api\/v1\/industry\/batches/);
assert.match(app,/\/api\/v1\/industry\/records/);
assert.match(app,/\/api\/v1\/sales-documents/);
assert.match(app,/Idempotency-Key/);
assert.match(app,/Grocery tenants/);
assert.match(app,/grocery_fefo_terminal/);
assert.match(app,/inventoryBatchId/);
assert.match(app,/grocery_waste/);
assert.match(app,/grocery_recall/);
assert.match(reporting,/reportPath\("daily-sales"/);
assert.match(reporting,/sale-products/);
assert.match(reporting,/profit-loss/);
assert.match(reporting,/salesman-commission/);
assert.match(reporting,/\/api\/v1\/reports\/options/);
assert.match(reporting,/Margin %/);
assert.match(reporting,/Achievement %/);
assert.match(reporting,/Payout %/);
assert.match(reporting,/Percentage basis:/);
assert.match(reporting,/Dashboard and Reports are synchronized/);
assert.match(reporting,/Export CSV/);
assert.match(reporting,/grocery-expiry-risk/);
assert.match(reporting,/grocery-waste-share/);
assert.match(reporting,/grocery-recall-share/);
assert.doesNotMatch(reporting,/JSON\.stringify\(report,\s*null,\s*2\)/);
console.log(`PASS: ${pages.length} purpose-built Grocery pages with reconciled reports, percentages and salesman commission`);