const fs=require('node:fs');
const assert=require('node:assert/strict');
const html=fs.readFileSync('demo-static/grocery-terminal.html','utf8');
const js=fs.readFileSync('demo-static/js/grocery-terminal-reconciliation.js','utf8');
assert.match(html,/grocery-terminal-reconciliation\.js/);
assert.ok(html.indexOf('grocery-terminal-reconciliation.js')<html.indexOf('grocery-app.js'));
assert.match(js,/\/api\/v1\/customers\?active=true/);
assert.match(js,/\/api\/v1\/sales-documents\/context/);
assert.match(js,/salesPersonId/);
assert.match(js,/counterId/);
assert.match(js,/terminalId/);
assert.match(js,/shiftId/);
assert.match(js,/dueDate/);
assert.match(js,/Please select a due date for the credit invoice/);
assert.match(js,/Idempotency-Key/);
assert.match(js,/invoice-view\.html/);
assert.match(js,/View \/ Print/);
assert.doesNotMatch(js,/Demo Customer|Sample Salesperson/);
console.log('PASS: Grocery terminal uses saved customers, register context, credit due date and idempotent print flow');
