const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const root=path.join(__dirname,'../demo-static');
const dashboard=fs.readFileSync(path.join(root,'retail-dashboard.html'),'utf8');
const index=fs.readFileSync(path.join(root,'index.html'),'utf8');
const app=fs.readFileSync(path.join(root,'js/retail-app.js'),'utf8');
const reports=fs.readFileSync(path.join(root,'reports.html'),'utf8');
const reportsApp=fs.readFileSync(path.join(root,'js/reports-backend.js'),'utf8');
const terminal=fs.readFileSync(path.join(root,'terminal.html'),'utf8');
const terminalGuard=fs.readFileSync(path.join(root,'js/retail-terminal-regression.js'),'utf8');
const transactionGuard=fs.readFileSync(path.join(root,'js/retail-terminal-transaction-guard.js'),'utf8');
const returnGuard=fs.readFileSync(path.join(root,'js/retail-return-reconciliation.js'),'utf8');
const returnsBackend=fs.readFileSync(path.join(root,'js/returns-backend.js'),'utf8');
const bootstrap=fs.readFileSync(path.join(root,'js/salesmen-bootstrap.js'),'utf8');
const invoiceView=fs.readFileSync(path.join(root,'invoice-view.html'),'utf8');
const invoiceViewBackend=fs.readFileSync(path.join(root,'js/invoice-view-backend.js'),'utf8');

assert.match(index,/retail-dashboard\.html/);
assert.match(dashboard,/GENERAL RETAIL/);
assert.match(dashboard,/terminal\.html/);
assert.match(dashboard,/sales\.html/);
assert.match(dashboard,/products\.html/);
assert.doesNotMatch(dashboard,/industry\.html\?module=/);
assert.match(app,/\/api\/v1\/industry\/registry/);
assert.match(app,/General Retail tenants/);
assert.match(app,/\/api\/v1\/auth\/me/);
assert.match(app,/canViewFinancialReports/);
assert.match(app,/canViewCustomers/);
assert.match(app,/setReportVisibility/);
assert.match(app,/setCustomerVisibility/);
assert.match(app,/renderRestrictedDashboard/);
assert.match(app,/Requests outside this role's permissions were not sent/);
assert.match(app,/async function loadOperationalDashboard\(session\)[\s\S]*customerAccess = canViewCustomers\(session\)[\s\S]*\/api\/v1\/dashboard\/summary[\s\S]*\/api\/v1\/products\?active=true[\s\S]*customerAccess[\s\S]*\/api\/v1\/customers\?active=true[\s\S]*Promise\.resolve\(\{ customers: \[\] \}\)/);
const operationalLoader=app.match(/async function loadOperationalDashboard\(session\)[\s\S]*?\n  }/)[0];
assert.doesNotMatch(operationalLoader,/\/api\/v1\/reports\//);
assert.match(operationalLoader,/customerAccess: customerAccess/);
assert.match(app,/\["owner", "admin", "manager", "accountant", "auditor", "cashier", "salesperson"\]/);
assert.doesNotMatch(app.match(/function canViewCustomers\(session\)[\s\S]*?\n  }/)[0],/storekeeper/);
assert.match(app,/if \(canViewFinancialReports\(session\)\)[\s\S]*renderReportDashboard\(operational\)[\s\S]*renderRestrictedDashboard\(session, operational\)/);
assert.match(app,/\/api\/v1\/reports\//);
assert.match(app,/daily-sales/);
assert.match(app,/sale-products/);
assert.match(app,/profit-loss/);
assert.match(dashboard,/data-report-access="required"/);
assert.match(dashboard,/data-customer-access="required"/);
assert.match(dashboard,/Financial report data is loaded only for roles authorized/);
assert.match(dashboard,/retail-app\.js\?v=20260804-storekeeper1/);
assert.match(dashboard,/id="monthlySales"/);
assert.match(dashboard,/id="monthlyGrossProfit"/);
assert.match(dashboard,/id="monthlyGrossMargin"/);
assert.match(dashboard,/id="topProductsBody"/);

assert.match(reports,/<title>Reports · Axtor POS Cloud<\/title>/);
assert.match(reports,/Retail Reports/);
assert.match(reports,/href="reports\.html" aria-current="page"/);
assert.match(reports,/reports-backend\.js/);
assert.match(reports,/Percentage basis/);
assert.match(reports,/Export CSV/);
assert.doesNotMatch(reports,/customers-backend\.js/);
assert.doesNotMatch(reports,/<h2>Customers<\/h2>/);
assert.match(reportsApp,/\/api\/v1\/reports/);
assert.match(reportsApp,/exportCsv/);
assert.match(reportsApp,/isPercentColumn/);
assert.match(reportsApp,/Gross profit ÷ product sales/);
assert.match(reportsApp,/Amount paid ÷ customer sales/);
assert.match(reportsApp,/Paid amount ÷ invoice total/);
assert.match(reportsApp,/Gross Profit is the gross margin/);

assert.match(terminal,/id="terminalCustomer"/);
assert.match(terminal,/id="saleSmId"/);
assert.match(terminal,/salesmen-bootstrap\.js/);
assert.match(bootstrap,/retail-terminal-regression\.js/);
assert.match(bootstrap,/retail-terminal-transaction-guard\.js/);
assert.match(bootstrap,/retail-return-reconciliation\.js/);
assert.match(terminalGuard,/\/api\/v1\/customers\?limit=500/);
assert.match(terminalGuard,/\/api\/v1\/salesmen\?month=/);
assert.match(terminalGuard,/Walk-in Customer/);
assert.match(terminalGuard,/Select Salesman \(optional\)/);
assert.match(terminalGuard,/Promise\.allSettled/);
assert.match(terminalGuard,/axtor:salesmen-migrated/);
assert.match(transactionGuard,/cannot exceed the invoice total/);
assert.match(transactionGuard,/Credit amount must equal the remaining invoice balance/);
assert.match(transactionGuard,/already being posted/);
assert.match(transactionGuard,/retryKeys/);
assert.match(transactionGuard,/idempotencyKey/);
assert.match(transactionGuard,/stableFingerprint/);
assert.match(transactionGuard,/stopImmediatePropagation/);
assert.match(returnGuard,/previouslyReturnedQty/);
assert.match(returnGuard,/returnedByLine/);
assert.match(returnGuard,/Math\.max\(0, item\.__originalSoldQty - item\.previouslyReturnedQty\)/);
assert.match(returnGuard,/data-previous-return-note/);
assert.match(returnsBackend,/Math\.min\(toNumber\(doc\.returnedAmount\),toNumber\(doc\.paidAmount\)\)-toNumber\(doc\.refundedAmount\)/);
assert.match(returnsBackend,/state\.refundIdempotencyKey/);

assert.match(invoiceView,/thermal80:'thermal-80'/);
assert.match(invoiceView,/thermal58:'thermal-58'/);
assert.match(invoiceView,/Print-ready invoice, quotation, delivery note, return, refund, or receipt/);
assert.match(invoiceView,/No document data was supplied/);
assert.doesNotMatch(invoiceView,/demo invoice template/i);
assert.match(invoiceViewBackend,/virtualProfile\("thermal-80"/);
assert.match(invoiceViewBackend,/virtualProfile\("thermal-58"/);
assert.match(invoiceViewBackend,/\/api\/v1\/sales-documents\//);
assert.match(invoiceViewBackend,/counterName/);
assert.match(invoiceViewBackend,/shiftReference/);
assert.match(invoiceViewBackend,/cashier/);
assert.match(invoiceViewBackend,/salesman/);

console.log('PASS: isolated General Retail frontend, permission-aware dashboard data, guarded transaction flows and unified A4\/80mm\/58mm printing');
