const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const root=path.join(__dirname,'../demo-static');
const dashboard=fs.readFileSync(path.join(root,'retail-dashboard.html'),'utf8');
const index=fs.readFileSync(path.join(root,'index.html'),'utf8');
const app=fs.readFileSync(path.join(root,'js/retail-app.js'),'utf8');
const reports=fs.readFileSync(path.join(root,'reports.html'),'utf8');
const reportsApp=fs.readFileSync(path.join(root,'js/reports-backend.js'),'utf8');

assert.match(index,/retail-dashboard\.html/);
assert.match(dashboard,/GENERAL RETAIL/);
assert.match(dashboard,/terminal\.html/);
assert.match(dashboard,/sales\.html/);
assert.match(dashboard,/products\.html/);
assert.doesNotMatch(dashboard,/industry\.html\?module=/);
assert.match(app,/\/api\/v1\/industry\/registry/);
assert.match(app,/General Retail tenants/);
assert.match(app,/\/api\/v1\/reports\//);
assert.match(app,/daily-sales/);
assert.match(app,/sale-products/);
assert.match(app,/profit-loss/);
assert.match(dashboard,/id="monthlySales"/);
assert.match(dashboard,/id="monthlyGrossProfit"/);
assert.match(dashboard,/id="monthlyGrossMargin"/);
assert.match(dashboard,/id="topProductsBody"/);
assert.match(dashboard,/same report endpoints/i);

assert.match(reports,/<title>Reports · Axtor POS Cloud<\/title>/);
assert.match(reports,/Retail Reports/);
assert.match(reports,/href="reports\.html" aria-current="page"/);
assert.match(reports,/reports-backend\.js/);
assert.match(reports,/Percentage basis/);
assert.match(reports,/Export CSV/);
assert.doesNotMatch(reports,/customers-backend\.js/);
assert.doesNotMatch(reports,/<h2>Customers<\/h2>/);
assert.match(reportsApp,/\/api\/v1\/reports/);
assert.match(reportsApp,/exportCsv/);
assert.match(reportsApp,/isPercentColumn/);
assert.match(reportsApp,/Gross profit ÷ product sales/);
assert.match(reportsApp,/Amount paid ÷ customer sales/);
assert.match(reportsApp,/Amount paid ÷ invoice total/);
assert.match(reportsApp,/Gross Profit is the gross margin/);

console.log('PASS: isolated General Retail frontend, accessible reports, percentage columns and dashboard reconciliation');
