const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const service=fs.readFileSync(path.join(__dirname,'../src/services/frontend-handoff.service.ts'),'utf8');
const controller=fs.readFileSync(path.join(__dirname,'../src/controllers/auth.controller.ts'),'utf8');
const routes=fs.readFileSync(path.join(__dirname,'../src/routes/auth.routes.ts'),'utf8');
assert.match(routes,/post\("\/handoff", requireAuth/);
assert.match(routes,/post\("\/exchange", exchangeHandoff/);
assert.match(service,/frontend_handoff/);
assert.match(service,/HANDOFF_TTL_SECONDS = 120/);
assert.match(service,/targetOrigin/);
assert.match(service,/tokenHash: hashToken\(code\)/);
assert.match(service,/revokedAt: null/);
assert.match(service,/consumed\.count !== 1/);
assert.match(service,/issueAuthToken/);
assert.match(service,/\.vercel\.app/);
assert.match(controller,/frontendHandoff/);
assert.match(controller,/exchangeHandoff/);
console.log('PASS: one-time target-bound frontend handoff is wired');
