CREATE TABLE "gym_membership_payments" ("id" TEXT PRIMARY KEY,"business_id" TEXT NOT NULL,"membership_id" TEXT NOT NULL,"amount" DECIMAL(14,2) NOT NULL,"payment_method" TEXT NOT NULL,"reference" TEXT,"paid_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"idempotency_key" TEXT,"recorded_by" TEXT);
CREATE UNIQUE INDEX "gym_membership_payments_business_id_idempotency_key_key" ON "gym_membership_payments"("business_id","idempotency_key");
CREATE INDEX "gym_membership_payments_business_id_membership_id_paid_at_idx" ON "gym_membership_payments"("business_id","membership_id","paid_at");
CREATE TABLE "school_fee_adjustments" ("id" TEXT PRIMARY KEY,"business_id" TEXT NOT NULL,"student_fee_id" TEXT NOT NULL,"adjustment_type" TEXT NOT NULL,"amount" DECIMAL(14,2) NOT NULL,"reason" TEXT NOT NULL,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"created_by" TEXT);
CREATE INDEX "school_fee_adjustments_business_id_student_fee_id_created_at_idx" ON "school_fee_adjustments"("business_id","student_fee_id","created_at");
CREATE TABLE "school_payroll_runs" ("id" TEXT PRIMARY KEY,"business_id" TEXT NOT NULL,"period" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'draft',"gross_amount" DECIMAL(14,2) NOT NULL DEFAULT 0,"paid_amount" DECIMAL(14,2) NOT NULL DEFAULT 0,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"posted_at" TIMESTAMP(3),"idempotency_key" TEXT);
CREATE UNIQUE INDEX "school_payroll_runs_business_id_period_key" ON "school_payroll_runs"("business_id","period");
CREATE UNIQUE INDEX "school_payroll_runs_business_id_idempotency_key_key" ON "school_payroll_runs"("business_id","idempotency_key");
CREATE INDEX "school_payroll_runs_business_id_status_idx" ON "school_payroll_runs"("business_id","status");
CREATE TABLE "clinic_invoices" ("id" TEXT PRIMARY KEY,"business_id" TEXT NOT NULL,"invoice_no" TEXT NOT NULL,"patient_id" TEXT NOT NULL,"encounter_id" TEXT,"subtotal" DECIMAL(14,2) NOT NULL DEFAULT 0,"discount" DECIMAL(14,2) NOT NULL DEFAULT 0,"total" DECIMAL(14,2) NOT NULL DEFAULT 0,"paid_amount" DECIMAL(14,2) NOT NULL DEFAULT 0,"status" TEXT NOT NULL DEFAULT 'due',"issued_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"revision" INTEGER NOT NULL DEFAULT 1,"idempotency_key" TEXT);
CREATE UNIQUE INDEX "clinic_invoices_business_id_invoice_no_key" ON "clinic_invoices"("business_id","invoice_no");
CREATE UNIQUE INDEX "clinic_invoices_business_id_idempotency_key_key" ON "clinic_invoices"("business_id","idempotency_key");
CREATE INDEX "clinic_invoices_business_id_patient_id_status_idx" ON "clinic_invoices"("business_id","patient_id","status");
CREATE TABLE "clinic_invoice_items" ("id" TEXT PRIMARY KEY,"business_id" TEXT NOT NULL,"invoice_id" TEXT NOT NULL,"service_id" TEXT,"description" TEXT NOT NULL,"quantity" DECIMAL(10,2) NOT NULL DEFAULT 1,"unit_price" DECIMAL(14,2) NOT NULL,"line_total" DECIMAL(14,2) NOT NULL);
CREATE INDEX "clinic_invoice_items_business_id_invoice_id_idx" ON "clinic_invoice_items"("business_id","invoice_id");
CREATE TABLE "clinic_payments" ("id" TEXT PRIMARY KEY,"business_id" TEXT NOT NULL,"invoice_id" TEXT NOT NULL,"amount" DECIMAL(14,2) NOT NULL,"payment_method" TEXT NOT NULL,"reference" TEXT,"paid_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"idempotency_key" TEXT,"recorded_by" TEXT);
CREATE UNIQUE INDEX "clinic_payments_business_id_idempotency_key_key" ON "clinic_payments"("business_id","idempotency_key");
CREATE INDEX "clinic_payments_business_id_invoice_id_paid_at_idx" ON "clinic_payments"("business_id","invoice_id","paid_at");
CREATE TABLE "release_b_notification_rules" ("id" TEXT PRIMARY KEY,"business_id" TEXT NOT NULL,"industry" TEXT NOT NULL,"event_key" TEXT NOT NULL,"days_before" INTEGER NOT NULL DEFAULT 0,"channel" TEXT NOT NULL DEFAULT 'in_app',"active" BOOLEAN NOT NULL DEFAULT true);
CREATE UNIQUE INDEX "release_b_notification_rules_business_id_industry_event_key_channel_key" ON "release_b_notification_rules"("business_id","industry","event_key","channel");
CREATE INDEX "release_b_notification_rules_business_id_industry_active_idx" ON "release_b_notification_rules"("business_id","industry","active");
