import { prisma } from "../db/prisma.js";
import { ApiError, cleanString, roundMoney } from "../utils/http.js";

const db: any = prisma;
const INVALID_SALE_STATUSES = ["DRAFT", "CANCELLED", "VOID"];
const DAY = 86_400_000;

export type GroceryReportDefinition = { id: string; title: string; family: string; description: string };

const SALES = [
  ["grocery-sales-summary","Sales Summary"],["grocery-sales-detail","Sales Detail"],["grocery-sales-product","Sales by Product"],
  ["grocery-sales-category","Sales by Category"],["grocery-sales-brand","Sales by Brand"],["grocery-sales-customer","Sales by Customer"],
  ["grocery-sales-salesperson","Sales by Salesperson"],["grocery-sales-cashier","Sales by Cashier"],["grocery-sales-counter","Sales by Counter"],
  ["grocery-sales-branch","Sales by Branch"],["grocery-sales-warehouse","Sales by Warehouse"],["grocery-sales-van","Sales by Van"],
  ["grocery-sales-payment-method","Sales by Payment Method"],["grocery-sales-hour","Sales by Hour"],["grocery-sales-day","Sales by Day"],
  ["grocery-sales-week","Sales by Week"],["grocery-sales-month","Sales by Month"],["grocery-sales-tax","Sales by Tax"],
  ["grocery-sales-discount","Discount Report"],["grocery-sales-void","Void / Cancelled Sales"],["grocery-sales-held","Held Sales"],
  ["grocery-sales-credit","Credit Sales"],["grocery-sales-cash","Cash Sales"],["grocery-sales-mixed","Mixed-Payment Sales"],
  ["grocery-sales-returns","Sales Return Report"],
] as const;
const PRODUCTS = [
  ["grocery-product-sales","Product Sales"],["grocery-product-profitability","Product Profitability"],["grocery-product-quantity","Product Quantity Sold"],
  ["grocery-product-fast","Fast Moving Products"],["grocery-product-slow","Slow Moving Products"],["grocery-product-nonmoving","Non-Moving Products"],
  ["grocery-product-dead","Dead Stock"],["grocery-product-low","Low Stock"],["grocery-product-out","Out of Stock"],
  ["grocery-product-return-rate","Product Return Rate"],["grocery-product-discount","Product Discount Report"],
  ["grocery-product-price-history","Product Price History"],["grocery-product-cost-history","Product Cost History"],
] as const;
const CUSTOMERS = [
  ["grocery-customer-sales","Customer Sales"],["grocery-customer-profitability","Customer Profitability"],["grocery-customer-ledger","Customer Ledger"],
  ["grocery-customer-statement-v2","Customer Statement"],["grocery-customer-outstanding","Customer Outstanding"],["grocery-customer-ageing","Customer Ageing"],
  ["grocery-customer-payment-history","Customer Payment History"],["grocery-customer-frequency","Customer Purchase Frequency"],
  ["grocery-customer-average-basket","Customer Average Basket"],["grocery-customer-top","Top Customers"],["grocery-customer-inactive","Inactive Customers"],
  ["grocery-customer-credit-utilization","Credit Limit Utilization"],
] as const;
const PAYMENTS = [
  ["grocery-payment-summary","Payment Method Summary"],["grocery-payment-cash","Cash Collections"],["grocery-payment-card","Card Collections"],
  ["grocery-payment-bank","Bank Transfer"],["grocery-payment-cheques","Cheques"],["grocery-payment-digital","Digital Payments"],
  ["grocery-payment-credit-sales","Credit Sales"],["grocery-payment-mixed","Mixed Payments"],["grocery-payment-refunds","Refunds"],
  ["grocery-payment-reconciliation","Payment Reconciliation"],
] as const;
const PURCHASES = [
  ["grocery-purchase-summary","Purchase Summary"],["grocery-purchase-detail","Purchase Detail"],["grocery-purchase-product","Purchases by Product"],
  ["grocery-purchase-supplier","Purchases by Supplier"],["grocery-purchase-category","Purchases by Category"],["grocery-purchase-branch","Purchases by Branch"],
  ["grocery-purchase-warehouse","Purchases by Warehouse"],["grocery-purchase-status","Purchase Order Status"],["grocery-purchase-pending","Pending PO"],
  ["grocery-purchase-partial","Partial PO"],["grocery-purchase-grn","GRN Report"],["grocery-purchase-returns","Purchase Returns"],
  ["grocery-purchase-cost-variance","Purchase Cost Variance"],["grocery-purchase-due","Purchase Due Report"],["grocery-purchase-supplier-payments","Supplier Payment Report"],
] as const;
const INVENTORY = [
  ["grocery-inventory-on-hand","Stock on Hand"],["grocery-inventory-warehouse","Stock by Warehouse"],["grocery-inventory-branch","Stock by Branch"],
  ["grocery-inventory-van","Stock by Van"],["grocery-inventory-valuation","Stock Valuation"],["grocery-inventory-movement","Stock Movement"],
  ["grocery-inventory-adjustment","Stock Adjustment"],["grocery-inventory-transfer","Stock Transfer"],["grocery-inventory-count-variance","Inventory Count Variance"],
  ["grocery-inventory-low","Low Stock"],["grocery-inventory-out","Out of Stock"],["grocery-inventory-excess","Excess Stock"],
  ["grocery-inventory-dead","Dead Stock"],["grocery-inventory-expired","Expired Inventory"],["grocery-inventory-near-expiry","Near Expiry"],
  ["grocery-inventory-damaged","Damaged Inventory"],["grocery-inventory-batch","Batch Stock"],["grocery-inventory-ageing","Inventory Ageing"],
] as const;

export const GROCERY_21_30_REPORTS: GroceryReportDefinition[] = [
  ...SALES.map(([id,title])=>({id,title,family:"sales",description:"Grocery sales reporting"})),
  ...PRODUCTS.map(([id,title])=>({id,title,family:"product",description:"Grocery product reporting"})),
  ...CUSTOMERS.map(([id,title])=>({id,title,family:"customer",description:"Grocery customer reporting"})),
  ...PAYMENTS.map(([id,title])=>({id,title,family:"payment",description:"Grocery payment reporting"})),
  ...PURCHASES.map(([id,title])=>({id,title,family:"purchase",description:"Grocery purchasing reporting"})),
  ...INVENTORY.map(([id,title])=>({id,title,family:"inventory",description:"Grocery inventory reporting"})),
  { id:"grocery-profit-loss", title:"Profit & Loss", family:"accounting", description:"Ledger-based Grocery Profit & Loss statement" },
];
const IDS = new Set(GROCERY_21_30_REPORTS.map(x=>x.id));

const money = (v: unknown) => roundMoney(Number(v || 0));
const qty = (v: unknown) => Number(Number(v || 0).toFixed(3));
const pct = (v: unknown, total: unknown) => Math.abs(Number(total || 0)) < 0.0000001 ? 0 : roundMoney(Number(v || 0) / Number(total || 0) * 100);
const text = (v: unknown) => String(v ?? "").trim();
const json = (v: unknown): Record<string, any> => v && typeof v === "object" && !Array.isArray(v) ? v as Record<string, any> : {};

function qatarDay(date = new Date()) { return new Date(date.getTime() + 3 * 3600000).toISOString().slice(0,10); }
function atQatarDay(s: string, end = false) { return new Date(`${s}T${end?"23:59:59.999":"00:00:00.000"}+03:00`); }
function startOfWeek(d: Date) { const x = new Date(d); const day = (x.getDay()+6)%7; x.setDate(x.getDate()-day); x.setHours(0,0,0,0); return x; }
function presetRange(q: any) {
  const now = new Date(); const today = qatarDay(now); const p = text(q.period).toLowerCase();
  if (text(q.from) && text(q.to) && /^\d{4}-\d{2}-\d{2}$/.test(text(q.from)) && /^\d{4}-\d{2}-\d{2}$/.test(text(q.to))) return { from: atQatarDay(text(q.from)), to: atQatarDay(text(q.to),true), preset:"custom" };
  if (p === "today") return { from: atQatarDay(today), to: atQatarDay(today,true), preset:p };
  if (p === "yesterday") { const d = new Date(atQatarDay(today).getTime()-DAY); const s=qatarDay(d); return {from:atQatarDay(s),to:atQatarDay(s,true),preset:p}; }
  if (p === "this-week" || p === "last-week") { const start=startOfWeek(now); if(p==="last-week") start.setDate(start.getDate()-7); const end=new Date(start.getTime()+7*DAY-1); return{from:start,to:p==="this-week"?now:end,preset:p}; }
  if (["this-month","last-month","this-quarter","this-year"].includes(p)) {
    let y=now.getFullYear(),m=now.getMonth(),from:Date,to:Date;
    if(p==="last-month"){m-=1;if(m<0){m=11;y-=1;}from=new Date(y,m,1);to=new Date(y,m+1,1);return{from,to:new Date(to.getTime()-1),preset:p};}
    if(p==="this-quarter"){m=Math.floor(m/3)*3;from=new Date(y,m,1);return{from,to:now,preset:p};}
    if(p==="this-year"){from=new Date(y,0,1);return{from,to:now,preset:p};}
    from=new Date(y,m,1);return{from,to:now,preset:p};
  }
  const from = new Date(now.getTime()-30*DAY); return { from, to: now, preset:p||"last-30-days" };
}
function comparisonRange(from: Date, to: Date) { const duration=Math.max(DAY,to.getTime()-from.getTime()+1); const comparisonTo=new Date(from.getTime()-1); return {from:new Date(comparisonTo.getTime()-duration+1),to:comparisonTo}; }
async function requireGrocery(businessId: string) { const row=await db.businessIndustry.findUnique({where:{businessId},include:{industry:{select:{code:true}}}}); if(text(row?.industry?.code).toLowerCase()!=="grocery") throw new ApiError(403,"Grocery report access requires a Grocery tenant"); }

function finalize(title:string, columns:any[], rawRows:any[], summary:any[], q:any, extra:any={}) {
  let rows=[...rawRows]; const search=text(q.search).toLowerCase();
  if(search) rows=rows.filter(r=>Object.values(r).some(v=>String(v??"").toLowerCase().includes(search)));
  const sortBy=text(q.sortBy); const sortDir=text(q.sortDir).toLowerCase()==="asc"?1:-1;
  if(sortBy) rows.sort((a,b)=>{const av=a[sortBy],bv=b[sortBy]; if(typeof av==="number"&&typeof bv==="number")return(av-bv)*sortDir;return String(av??"").localeCompare(String(bv??""))*sortDir;});
  const totalRows=rows.length; const page=Math.max(1,Math.trunc(Number(q.page||1))); const pageSize=Math.max(10,Math.min(500,Math.trunc(Number(q.pageSize||100))));
  rows=rows.slice((page-1)*pageSize,page*pageSize);
  return { title, columns, rows, summary, meta:{page,pageSize,totalRows,search:search||null,sortBy:sortBy||null,sortDir:sortDir===1?"asc":"desc",groupBy:text(q.groupBy)||null,comparisonPeriod:Boolean(q.comparison),...extra}, exports:["csv","xlsx","pdf","print"] };
}

function salesWhere(businessId:string,q:any,includeInvalid=false){const r=presetRange(q);const w:any={businessId,documentType:"INVOICE",createdAt:{gte:r.from,lte:r.to}};if(!includeInvalid)w.status={notIn:INVALID_SALE_STATUSES};if(text(q.branchId))w.branchId=text(q.branchId);if(text(q.warehouseId))w.warehouseId=text(q.warehouseId);if(text(q.counterId))w.counterId=text(q.counterId);if(text(q.customerId))w.customerId=text(q.customerId);if(text(q.salesmanId))w.salesmanId=text(q.salesmanId);if(text(q.cashierId)||text(q.userId))w.createdByUserId=text(q.cashierId||q.userId);return{where:w,range:r};}
async function salesDocs(businessId:string,q:any,includeInvalid=false){const {where,range}=salesWhere(businessId,q,includeInvalid);let docs=await db.salesDocument.findMany({where,include:{items:true},orderBy:{createdAt:"desc"}});if(text(q.paymentMethod))docs=docs.filter((d:any)=>text(d.paymentMethod).toLowerCase()===text(q.paymentMethod).toLowerCase());if(text(q.vanId))docs=docs.filter((d:any)=>text(json(d.metadata).vanId)===text(q.vanId));return{docs,range};}

async function dimensionMaps(businessId:string,docs:any[]){const productIds=[...new Set(docs.flatMap(d=>(d.items||[]).map((i:any)=>i.productId).filter(Boolean)))];const [products,branches,warehouses,counters,users,salesmen,vans]=await Promise.all([
  productIds.length?db.product.findMany({where:{businessId,id:{in:productIds}}}):[],db.branch.findMany({where:{businessId}}),db.warehouse.findMany({where:{businessId}}),db.counter.findMany({where:{businessId}}),db.user.findMany({where:{businessId}}),db.salesman.findMany({where:{businessId}}),db.industryRecord.findMany({where:{businessId,industryCode:"grocery",entityType:"grocery_van",archivedAt:null}})
]);const map=(a:any[])=>new Map(a.map(x=>[String(x.id),x]));return{products:map(products),branches:map(branches),warehouses:map(warehouses),counters:map(counters),users:map(users),salesmen:map(salesmen),vans:map(vans)};}
function saleCost(doc:any,products:Map<string,any>){const snap=json(doc.metadata).groceryCostSnapshot;if(snap&&Number.isFinite(Number(snap.totalCogs)))return Number(snap.totalCogs);return(doc.items||[]).reduce((s:number,i:any)=>s+Number(i.qty||0)*Number(products.get(String(i.productId))?.costPrice||0),0);}
function salesSummaryRows(docs:any[],maps:any,group:(d:any,i?:any)=>{key:string;label:string}){const g=new Map<string,any>();for(const d of docs){const items=d.items?.length?d.items:[null];for(const i of items){const x=group(d,i);const r=g.get(x.key)||{label:x.label,invoices:new Set<string>(),quantity:0,grossSales:0,discounts:0,returns:0,tax:0,cost:0};r.invoices.add(d.id);r.quantity+=i?Number(i.qty||0):0;r.grossSales+=i?Number(i.total||0):Number(d.total||0);r.discounts+=i?Number(i.discount||0):Number(d.discount||0);r.returns+=i?0:Number(d.returnedAmount||0);r.tax+=i?Number(i.tax||0):Number(d.tax||0);r.cost+=i?Number(i.qty||0)*Number(maps.products.get(String(i.productId))?.costPrice||0):saleCost(d,maps.products);g.set(x.key,r);}}
 const total=[...g.values()].reduce((s,r)=>s+r.grossSales-r.returns,0);const totalQty=[...g.values()].reduce((s,r)=>s+r.quantity,0);const totalProfit=[...g.values()].reduce((s,r)=>s+(r.grossSales-r.returns-r.cost),0);
 return [...g.values()].map(r=>{const net=r.grossSales-r.returns;const profit=net-r.cost;return{group:r.label,invoices:r.invoices.size,quantity:qty(r.quantity),grossSales:money(r.grossSales),discounts:money(r.discounts),returns:money(r.returns),netSales:money(net),tax:money(r.tax),cost:money(r.cost),grossProfit:money(profit),marginPct:pct(profit,net),contributionPct:pct(net,total),unitsPct:pct(r.quantity,totalQty),profitPct:pct(profit,totalProfit)}}).sort((a,b)=>b.netSales-a.netSales);}

async function salesReport(businessId:string,id:string,q:any){
  if(id==="grocery-sales-held"){const r=presetRange(q);const held=await db.industryRecord.findMany({where:{businessId,industryCode:"grocery",entityType:"grocery_held_sale",createdAt:{gte:r.from,lte:r.to}},orderBy:{createdAt:"desc"}});const rows=held.map((x:any)=>({date:x.createdAt,reference:x.referenceNo,name:x.displayName,status:x.status,amount:money(x.amount),customerId:x.relatedEntityId||null}));return finalize("Held Sales",[{key:"date",label:"Date"},{key:"reference",label:"Reference"},{key:"name",label:"Held Sale"},{key:"status",label:"Status"},{key:"amount",label:"Amount"}],rows,[{label:"Held Sales",value:rows.length},{label:"Amount",value:money(rows.reduce((s,r)=>s+r.amount,0))}],q,{period:r.preset});}
  if(id==="grocery-sales-returns"){const r=presetRange(q);const list=await db.salesReturn.findMany({where:{businessId,returnDate:{gte:r.from,lte:r.to},status:{notIn:["CANCELLED","VOID"]}},include:{items:true,sourceSalesDocument:{select:{documentNo:true}}},orderBy:{returnDate:"desc"}});const total=list.reduce((s:number,x:any)=>s+Number(x.total||0),0);const rows=list.map((x:any)=>({date:x.returnDate,returnNo:x.returnNo,invoice:x.sourceSalesDocument?.documentNo||"-",customer:x.customerName,quantity:qty((x.items||[]).reduce((s:number,i:any)=>s+Number(i.returnQty||0),0)),amount:money(x.total),sharePct:pct(x.total,total),status:x.status}));return finalize("Sales Return Report",Object.keys(rows[0]||{date:0,returnNo:0,invoice:0,customer:0,quantity:0,amount:0,sharePct:0,status:0}).map(k=>({key:k,label:k.replace(/([A-Z])/g," $1")})),rows,[{label:"Returns",value:rows.length},{label:"Return Amount",value:money(total)}],q,{period:r.preset});}
  const includeInvalid=id==="grocery-sales-void";const {docs,range}=await salesDocs(businessId,q,includeInvalid);const maps=await dimensionMaps(businessId,docs);
  let filtered=docs;if(id==="grocery-sales-void")filtered=docs.filter((d:any)=>["CANCELLED","VOID"].includes(text(d.status).toUpperCase()));if(id==="grocery-sales-credit")filtered=docs.filter((d:any)=>Number(d.balance||0)>0);if(id==="grocery-sales-cash")filtered=docs.filter((d:any)=>text(d.paymentMethod).toLowerCase()==="cash");if(id==="grocery-sales-mixed")filtered=docs.filter((d:any)=>text(d.paymentMethod).toLowerCase()==="mixed"||Array.isArray(json(d.metadata).paymentLines)&&json(d.metadata).paymentLines.length>1);
  if(id==="grocery-sales-detail"||id==="grocery-sales-summary"||id==="grocery-sales-credit"||id==="grocery-sales-cash"||id==="grocery-sales-mixed"||id==="grocery-sales-discount"||id==="grocery-sales-void"){
    const total=filtered.reduce((s:any,d:any)=>s+Number(d.total||0),0);const rows=filtered.map((d:any)=>{const cost=saleCost(d,maps.products),profit=Number(d.total||0)-Number(d.returnedAmount||0)-cost;return{date:d.issuedAt||d.createdAt,invoice:d.documentNo,customer:d.customerName,status:d.status,paymentMethod:d.paymentMethod||"-",grossSales:money(d.total),discount:money(d.discount),returns:money(d.returnedAmount),netSales:money(Number(d.total||0)-Number(d.returnedAmount||0)),tax:money(d.tax),cost:money(cost),grossProfit:money(profit),marginPct:pct(profit,Number(d.total||0)-Number(d.returnedAmount||0)),contributionPct:pct(d.total,total),balance:money(d.balance)}});
    const cols=Object.keys(rows[0]||{date:0,invoice:0,customer:0,status:0,paymentMethod:0,grossSales:0,discount:0,returns:0,netSales:0,tax:0,cost:0,grossProfit:0,marginPct:0,contributionPct:0,balance:0}).map(k=>({key:k,label:k.replace(/([A-Z])/g," $1")}));return finalize(GROCERY_21_30_REPORTS.find(x=>x.id===id)?.title||"Sales",cols,rows,[{label:"Invoices",value:rows.length},{label:"Gross Sales",value:money(total)},{label:"Net Sales",value:money(rows.reduce((s,r)=>s+r.netSales,0))},{label:"Gross Profit",value:money(rows.reduce((s,r)=>s+r.grossProfit,0))}],q,{period:range.preset});
  }
  const groupers:any={
    "grocery-sales-product":(d:any,i:any)=>({key:String(i?.productId||i?.sku||"unknown"),label:i?.name||"Unknown Product"}),
    "grocery-sales-category":(_d:any,i:any)=>{const p=maps.products.get(String(i?.productId));return{key:text(p?.category)||"Unassigned",label:text(p?.category)||"Unassigned Category"}},
    "grocery-sales-brand":(_d:any,i:any)=>{const p=maps.products.get(String(i?.productId));return{key:text(p?.brand)||"Unassigned",label:text(p?.brand)||"Unassigned Brand"}},
    "grocery-sales-customer":(d:any)=>({key:String(d.customerId||d.customerName),label:d.customerName||"Walk-in"}),
    "grocery-sales-salesperson":(d:any)=>({key:String(d.salesmanId||"none"),label:d.salesmanName||maps.salesmen.get(String(d.salesmanId))?.name||"Unassigned"}),
    "grocery-sales-cashier":(d:any)=>({key:String(d.createdByUserId||"none"),label:maps.users.get(String(d.createdByUserId))?.name||"Unassigned Cashier"}),
    "grocery-sales-counter":(d:any)=>({key:String(d.counterId||"none"),label:maps.counters.get(String(d.counterId))?.name||"Unassigned Counter"}),
    "grocery-sales-branch":(d:any)=>({key:String(d.branchId||"none"),label:maps.branches.get(String(d.branchId))?.name||"Unassigned Branch"}),
    "grocery-sales-warehouse":(d:any)=>({key:String(d.warehouseId||"none"),label:maps.warehouses.get(String(d.warehouseId))?.name||"Unassigned Warehouse"}),
    "grocery-sales-van":(d:any)=>{const id=text(json(d.metadata).vanId);return{key:id||"none",label:maps.vans.get(id)?.displayName||"Non-Van Sales"}},
    "grocery-sales-payment-method":(d:any)=>({key:text(d.paymentMethod)||"unspecified",label:text(d.paymentMethod)||"Unspecified"}),
    "grocery-sales-hour":(d:any)=>{const h=new Date(d.createdAt).getHours();return{key:String(h).padStart(2,"0"),label:`${String(h).padStart(2,"0")}:00`}},
    "grocery-sales-day":(d:any)=>{const x=new Date(d.createdAt).toISOString().slice(0,10);return{key:x,label:x}},
    "grocery-sales-week":(d:any)=>{const x=startOfWeek(new Date(d.createdAt)).toISOString().slice(0,10);return{key:x,label:`Week of ${x}`}},
    "grocery-sales-month":(d:any)=>{const x=new Date(d.createdAt).toISOString().slice(0,7);return{key:x,label:x}},
    "grocery-sales-tax":(d:any)=>({key:String(Number(d.tax||0)>0?"Taxable":"Zero/No Tax"),label:Number(d.tax||0)>0?"Taxable":"Zero / No Tax"}),
  };
  const rows=salesSummaryRows(filtered,maps,groupers[id]||groupers["grocery-sales-payment-method"]);const cols=[{key:"group",label:"Group"},{key:"invoices",label:"Invoices"},{key:"quantity",label:"Quantity"},{key:"grossSales",label:"Gross Sales"},{key:"discounts",label:"Discounts"},{key:"returns",label:"Returns"},{key:"netSales",label:"Net Sales"},{key:"tax",label:"Tax"},{key:"cost",label:"Cost"},{key:"grossProfit",label:"Gross Profit"},{key:"marginPct",label:"Margin %"},{key:"contributionPct",label:"% of Total Sales"},{key:"unitsPct",label:"% of Units Sold"},{key:"profitPct",label:"% of Total Gross Profit"}];return finalize(GROCERY_21_30_REPORTS.find(x=>x.id===id)?.title||"Sales Report",cols,rows,[{label:"Net Sales",value:money(rows.reduce((s,r)=>s+r.netSales,0))},{label:"Gross Profit",value:money(rows.reduce((s,r)=>s+r.grossProfit,0))},{label:"Invoices",value:filtered.length}],q,{period:range.preset});
}

async function productReport(businessId:string,id:string,q:any){const {docs,range}=await salesDocs(businessId,q);const products=await db.product.findMany({where:{businessId,deleted:false,...(text(q.productId)?{id:text(q.productId)}:{})}});const productMap=new Map(products.map((p:any)=>[String(p.id),p]));const ag=new Map<string,any>();for(const p of products)ag.set(String(p.id),{productId:p.id,sku:p.sku,product:p.name,category:p.category||"-",brand:p.brand||"-",quantity:0,sales:0,discount:0,cost:0,returnsQty:0,returnsValue:0,lastSale:null,currentStock:Number(p.currentStock||0),reorderLevel:Number(p.minStock||0),price:Number(p.price||0),costPrice:Number(p.costPrice||0),createdAt:p.createdAt});for(const d of docs)for(const i of d.items||[]){const r=ag.get(String(i.productId));if(!r)continue;r.quantity+=Number(i.qty||0);r.sales+=Number(i.total||0);r.discount+=Number(i.discount||0);r.cost+=Number(i.qty||0)*Number(productMap.get(String(i.productId))?.costPrice||0);const dt=new Date(d.createdAt);if(!r.lastSale||dt>r.lastSale)r.lastSale=dt;}
 const returns=await db.salesReturn.findMany({where:{businessId,returnDate:{gte:range.from,lte:range.to},status:{notIn:["CANCELLED","VOID"]}},include:{items:true}});for(const ret of returns)for(const i of ret.items||[]){const r=ag.get(String(i.productId));if(r){r.returnsQty+=Number(i.returnQty||0);r.returnsValue+=Number(i.total||0);}}
 let rows=[...ag.values()].map(r=>{const profit=r.sales-r.cost;return{...r,quantity:qty(r.quantity),sales:money(r.sales),discount:money(r.discount),cost:money(r.cost),profit:money(profit),marginPct:pct(profit,r.sales),returnRatePct:pct(r.returnsQty,r.quantity),returnsQty:qty(r.returnsQty),returnsValue:money(r.returnsValue),daysSinceSale:r.lastSale?Math.max(0,Math.floor((Date.now()-r.lastSale.getTime())/DAY)):null,stockValue:money(r.currentStock*r.costPrice)}});
 const totalSales=rows.reduce((s,r)=>s+r.sales,0),totalQty=rows.reduce((s,r)=>s+r.quantity,0),totalProfit=rows.reduce((s,r)=>s+r.profit,0),totalStock=rows.reduce((s,r)=>s+r.stockValue,0);rows=rows.map(r=>({...r,salesPct:pct(r.sales,totalSales),unitsPct:pct(r.quantity,totalQty),profitPct:pct(r.profit,totalProfit),inventoryValuePct:pct(r.stockValue,totalStock)}));
 if(id==="grocery-product-fast")rows=rows.filter(r=>r.quantity>0).sort((a,b)=>b.quantity-a.quantity);if(id==="grocery-product-slow")rows=rows.filter(r=>r.quantity>0).sort((a,b)=>a.quantity-b.quantity);if(id==="grocery-product-nonmoving")rows=rows.filter(r=>r.quantity===0&&r.currentStock>0);if(id==="grocery-product-dead")rows=rows.filter(r=>r.currentStock>0&&(r.daysSinceSale===null||r.daysSinceSale>=Math.max(30,Number(q.deadDays||90))));if(id==="grocery-product-low")rows=rows.filter(r=>r.currentStock>0&&r.currentStock<=r.reorderLevel);if(id==="grocery-product-out")rows=rows.filter(r=>r.currentStock<=0);if(id==="grocery-product-return-rate")rows=rows.filter(r=>r.returnsQty>0).sort((a,b)=>b.returnRatePct-a.returnRatePct);if(id==="grocery-product-discount")rows=rows.filter(r=>r.discount>0).sort((a,b)=>b.discount-a.discount);
 if(id==="grocery-product-price-history"||id==="grocery-product-cost-history"){const logs=await db.auditLog.findMany({where:{businessId,entityType:"Product",createdAt:{gte:range.from,lte:range.to}},orderBy:{createdAt:"desc"},take:10000});const field=id.endsWith("price-history")?"price":"costPrice";const h=logs.flatMap((l:any)=>{const before=json(l.before),after=json(l.after);if(before[field]===undefined&&after[field]===undefined)return[];return[{date:l.createdAt,productId:l.entityId,oldValue:money(before[field]),newValue:money(after[field]),difference:money(Number(after[field]||0)-Number(before[field]||0)),changedBy:l.userId,action:l.action}]});return finalize(GROCERY_21_30_REPORTS.find(x=>x.id===id)!.title,[{key:"date",label:"Date"},{key:"productId",label:"Product ID"},{key:"oldValue",label:"Old Value"},{key:"newValue",label:"New Value"},{key:"difference",label:"Difference"},{key:"changedBy",label:"Changed By"},{key:"action",label:"Action"}],h,[{label:"Changes",value:h.length}],q,{period:range.preset});}
 const cols=[{key:"sku",label:"SKU"},{key:"product",label:"Product"},{key:"quantity",label:"Quantity"},{key:"unitsPct",label:"% of Units Sold"},{key:"sales",label:"Revenue"},{key:"salesPct",label:"% of Total Sales"},{key:"cost",label:"Cost"},{key:"profit",label:"Gross Profit"},{key:"profitPct",label:"% of Total Gross Profit"},{key:"marginPct",label:"Margin %"},{key:"returnsQty",label:"Returned Qty"},{key:"returnRatePct",label:"Return Rate %"},{key:"currentStock",label:"Stock"},{key:"stockValue",label:"Stock Value"},{key:"inventoryValuePct",label:"% of Inventory Value"}];return finalize(GROCERY_21_30_REPORTS.find(x=>x.id===id)?.title||"Product Report",cols,rows,[{label:"Products",value:rows.length},{label:"Sales",value:money(totalSales)},{label:"Gross Profit",value:money(totalProfit)},{label:"Stock Value",value:money(totalStock)}],q,{period:range.preset});}

async function customerReport(businessId:string,id:string,q:any){const {docs,range}=await salesDocs(businessId,q);const customers=await db.customer.findMany({where:{businessId,active:true,...(text(q.customerId)?{id:text(q.customerId)}:{})}});const pay=await db.customerPayment.findMany({where:{businessId,paymentDate:{gte:range.from,lte:range.to},...(text(q.customerId)?{customerId:text(q.customerId)}:{})},orderBy:{paymentDate:"desc"}});const maps=await dimensionMaps(businessId,docs);const grouped=new Map<string,any>();for(const c of customers)grouped.set(String(c.id),{customerId:c.id,customer:c.name,invoices:0,sales:0,cost:0,paid:0,outstanding:Number(c.balance||0),creditLimit:Number(c.creditLimit||0),lastPurchase:null});for(const d of docs){if(!d.customerId)continue;const r=grouped.get(String(d.customerId));if(!r)continue;r.invoices++;r.sales+=Number(d.total||0);r.cost+=saleCost(d,maps.products);r.paid+=Number(d.paid||0);const dt=new Date(d.createdAt);if(!r.lastPurchase||dt>r.lastPurchase)r.lastPurchase=dt;}
 let rows=[...grouped.values()].map(r=>{const profit=r.sales-r.cost;return{...r,sales:money(r.sales),cost:money(r.cost),profit:money(profit),marginPct:pct(profit,r.sales),outstanding:money(r.outstanding),creditLimit:money(r.creditLimit),creditUtilizationPct:pct(r.outstanding,r.creditLimit),averageBasket:money(r.invoices?r.sales/r.invoices:0),purchaseFrequency:r.invoices,daysInactive:r.lastPurchase?Math.floor((Date.now()-r.lastPurchase.getTime())/DAY):null}});const totalSales=rows.reduce((s,r)=>s+r.sales,0),totalProfit=rows.reduce((s,r)=>s+r.profit,0),totalAR=rows.reduce((s,r)=>s+r.outstanding,0);rows=rows.map(r=>({...r,salesPct:pct(r.sales,totalSales),profitPct:pct(r.profit,totalProfit),receivablePct:pct(r.outstanding,totalAR)}));
 if(id==="grocery-customer-top")rows.sort((a,b)=>b.sales-a.sales);if(id==="grocery-customer-inactive")rows=rows.filter(r=>r.daysInactive===null||r.daysInactive>=Math.max(30,Number(q.inactiveDays||90))).sort((a,b)=>(b.daysInactive||999999)-(a.daysInactive||999999));if(id==="grocery-customer-outstanding"||id==="grocery-customer-ageing")rows=rows.filter(r=>r.outstanding>0).sort((a,b)=>b.outstanding-a.outstanding);if(id==="grocery-customer-credit-utilization")rows=rows.filter(r=>r.creditLimit>0).sort((a,b)=>b.creditUtilizationPct-a.creditUtilizationPct);
 if(id==="grocery-customer-payment-history"){const total=pay.reduce((s:number,p:any)=>s+Number(p.baseAmount||p.amount||0),0);const r=pay.map((p:any)=>({date:p.paymentDate,receiptNo:p.receiptNo,customer:p.customerName,method:p.method,reference:p.referenceNo||"-",amount:money(p.baseAmount||p.amount),sharePct:pct(p.baseAmount||p.amount,total)}));return finalize("Customer Payment History",[{key:"date",label:"Date"},{key:"receiptNo",label:"Receipt"},{key:"customer",label:"Customer"},{key:"method",label:"Method"},{key:"reference",label:"Reference"},{key:"amount",label:"Amount"},{key:"sharePct",label:"% of Collections"}],r,[{label:"Collections",value:money(total)},{label:"Receipts",value:r.length}],q,{period:range.preset});}
 if(id==="grocery-customer-ledger"||id==="grocery-customer-statement-v2"){const target=text(q.customerId);if(!target)throw new ApiError(422,"customerId is required for customer ledger/statement");const inv=docs.filter((d:any)=>String(d.customerId)===target).map((d:any)=>({date:d.createdAt,type:"Invoice",reference:d.documentNo,debit:money(d.total),credit:0}));const rec=pay.filter((p:any)=>String(p.customerId)===target).map((p:any)=>({date:p.paymentDate,type:"Receipt",reference:p.receiptNo,debit:0,credit:money(p.baseAmount||p.amount)}));const ledger=[...inv,...rec].sort((a,b)=>new Date(a.date).getTime()-new Date(b.date).getTime());let running=0;const r=ledger.map(x=>({...x,balance:money(running+=x.debit-x.credit)}));return finalize(id.endsWith("ledger")?"Customer Ledger":"Customer Statement",[{key:"date",label:"Date"},{key:"type",label:"Type"},{key:"reference",label:"Reference"},{key:"debit",label:"Debit"},{key:"credit",label:"Credit"},{key:"balance",label:"Running Balance"}],r,[{label:"Debits",value:money(r.reduce((s,x)=>s+x.debit,0))},{label:"Credits",value:money(r.reduce((s,x)=>s+x.credit,0))},{label:"Closing",value:money(r.at(-1)?.balance||0)}],q,{period:range.preset});}
 const cols=[{key:"customer",label:"Customer"},{key:"invoices",label:"Invoices"},{key:"sales",label:"Sales"},{key:"salesPct",label:"% of Total Sales"},{key:"cost",label:"Cost"},{key:"profit",label:"Profit"},{key:"profitPct",label:"% of Total Profit"},{key:"marginPct",label:"Margin %"},{key:"averageBasket",label:"Average Basket"},{key:"purchaseFrequency",label:"Purchase Frequency"},{key:"outstanding",label:"Outstanding"},{key:"receivablePct",label:"% of Total Receivable"},{key:"creditLimit",label:"Credit Limit"},{key:"creditUtilizationPct",label:"Credit Used %"},{key:"daysInactive",label:"Days Inactive"}];return finalize(GROCERY_21_30_REPORTS.find(x=>x.id===id)?.title||"Customer Report",cols,rows,[{label:"Customers",value:rows.length},{label:"Sales",value:money(totalSales)},{label:"Profit",value:money(totalProfit)},{label:"Receivables",value:money(totalAR)}],q,{period:range.preset});}

async function paymentReport(businessId:string,id:string,q:any){const range=presetRange(q);const [receipts,payments,expenses,cheques]=await Promise.all([db.customerPayment.findMany({where:{businessId,paymentDate:{gte:range.from,lte:range.to}}}),db.supplierPayment.findMany({where:{businessId,paymentDate:{gte:range.from,lte:range.to}}}),db.expense.findMany({where:{businessId,expenseDate:{gte:range.from,lte:range.to}}}),db.industryRecord.findMany({where:{businessId,industryCode:"grocery",entityType:"grocery_cheque",createdAt:{gte:range.from,lte:range.to},archivedAt:null}})]);const events:any[]=[];for(const x of receipts)events.push({date:x.paymentDate,direction:"received",type:"customer_payment",method:text(x.method).toLowerCase(),reference:x.receiptNo,party:x.customerName,amount:money(x.baseAmount||x.amount)});for(const x of payments)events.push({date:x.paymentDate,direction:"paid",type:"supplier_payment",method:text(x.method).toLowerCase(),reference:x.voucherNo,party:x.supplierName,amount:money(x.baseAmount||x.amount)});for(const x of expenses)events.push({date:x.expenseDate,direction:"paid",type:"expense",method:text(json(x.metadata).paymentMethod||"cash").toLowerCase(),reference:x.expenseNo||x.id,party:x.payee||x.category,amount:money(x.baseAmount||x.amount)});for(const x of cheques){const d=json(x.data);events.push({date:x.createdAt,direction:text(d.direction)==="outward"?"paid":"received",type:"cheque",method:"cheque",reference:d.chequeNumber||x.referenceNo,party:d.partyName||x.displayName,amount:money(x.amount),status:x.status});}
 let rows=events;const match=(m:string,...keys:string[])=>keys.some(k=>m.includes(k));if(id==="grocery-payment-cash")rows=rows.filter(x=>x.method==="cash");if(id==="grocery-payment-card")rows=rows.filter(x=>match(x.method,"card","credit_card","debit_card"));if(id==="grocery-payment-bank")rows=rows.filter(x=>match(x.method,"bank","transfer"));if(id==="grocery-payment-cheques")rows=rows.filter(x=>x.method==="cheque");if(id==="grocery-payment-digital")rows=rows.filter(x=>match(x.method,"wallet","digital","mobile"));if(text(q.paymentMethod))rows=rows.filter(x=>x.method===text(q.paymentMethod).toLowerCase());
 if(id==="grocery-payment-credit-sales"||id==="grocery-payment-mixed"||id==="grocery-payment-refunds"){const {docs}=await salesDocs(businessId,q);if(id==="grocery-payment-credit-sales")rows=docs.filter((d:any)=>Number(d.balance||0)>0).map((d:any)=>({date:d.createdAt,direction:"receivable",type:"credit_sale",method:"customer_credit",reference:d.documentNo,party:d.customerName,amount:money(d.balance),status:d.status}));if(id==="grocery-payment-mixed")rows=docs.filter((d:any)=>text(d.paymentMethod).toLowerCase()==="mixed"||json(d.metadata).paymentLines?.length>1).map((d:any)=>({date:d.createdAt,direction:"received",type:"mixed_sale",method:"mixed",reference:d.documentNo,party:d.customerName,amount:money(d.paid),status:d.status}));if(id==="grocery-payment-refunds")rows=docs.filter((d:any)=>Number(d.refundedAmount||0)>0).map((d:any)=>({date:d.createdAt,direction:"paid",type:"refund",method:text(d.paymentMethod)||"original method",reference:d.documentNo,party:d.customerName,amount:money(d.refundedAmount),status:d.returnStatus||d.status}));}
 const total=rows.reduce((s,r)=>s+Number(r.amount||0),0);const received=rows.filter(r=>r.direction==="received").reduce((s,r)=>s+r.amount,0),paid=rows.filter(r=>r.direction==="paid").reduce((s,r)=>s+r.amount,0);const grouped=new Map<string,any>();for(const r of rows){const key=r.method||"unspecified",g=grouped.get(key)||{paymentMethod:key,transactions:0,received:0,paid:0,amount:0};g.transactions++;g.amount+=r.amount;if(r.direction==="received")g.received+=r.amount;if(r.direction==="paid")g.paid+=r.amount;grouped.set(key,g);}if(id==="grocery-payment-summary"||id==="grocery-payment-reconciliation"){const out=[...grouped.values()].map(g=>({...g,received:money(g.received),paid:money(g.paid),amount:money(g.amount),transactionPct:pct(g.transactions,rows.length),collectionPct:pct(g.received,received)}));return finalize(GROCERY_21_30_REPORTS.find(x=>x.id===id)!.title,[{key:"paymentMethod",label:"Payment Method"},{key:"transactions",label:"Transactions"},{key:"transactionPct",label:"% of Transactions"},{key:"received",label:"Received"},{key:"paid",label:"Paid"},{key:"amount",label:"Movement"},{key:"collectionPct",label:"% of Collections"}],out,[{label:"Received",value:money(received)},{label:"Paid",value:money(paid)},{label:"Net Movement",value:money(received-paid)},{label:"Transactions",value:rows.length}],q,{period:range.preset});}
 const out=rows.map(r=>({...r,sharePct:pct(r.amount,total)}));return finalize(GROCERY_21_30_REPORTS.find(x=>x.id===id)?.title||"Payment Report",[{key:"date",label:"Date"},{key:"direction",label:"Direction"},{key:"type",label:"Type"},{key:"method",label:"Payment Method"},{key:"reference",label:"Reference"},{key:"party",label:"Party"},{key:"amount",label:"Amount"},{key:"sharePct",label:"% of Total"},{key:"status",label:"Status"}],out,[{label:"Amount",value:money(total)},{label:"Transactions",value:out.length}],q,{period:range.preset});}

async function purchaseReport(businessId:string,id:string,q:any){const range=presetRange(q);const where:any={businessId,purchaseDate:{gte:range.from,lte:range.to},status:{not:"CANCELLED"}};if(text(q.supplierId))where.supplierId=text(q.supplierId);if(text(q.branchId))where.branchId=text(q.branchId);if(text(q.warehouseId))where.warehouseId=text(q.warehouseId);let purchases=await db.purchase.findMany({where,include:{items:true,goodsReceipts:{include:{items:true}}},orderBy:{purchaseDate:"desc"}});if(id==="grocery-purchase-pending")purchases=purchases.filter((p:any)=>["DRAFT","APPROVED","ORDERED"].includes(text(json(p.metadata).workflowStatus||p.status).toUpperCase()));if(id==="grocery-purchase-partial")purchases=purchases.filter((p:any)=>text(json(p.metadata).workflowStatus).toUpperCase()==="PARTIALLY_RECEIVED");
 if(id==="grocery-purchase-grn"){const r=purchases.flatMap((p:any)=>(p.goodsReceipts||[]).map((g:any)=>({date:g.createdAt,receiptNo:g.receiptNo,purchaseNo:p.purchaseNo,supplier:p.supplierName,warehouseId:g.warehouseId,items:(g.items||[]).length,quantity:qty((g.items||[]).reduce((s:number,i:any)=>s+Number(i.qty||0),0)),value:money((g.items||[]).reduce((s:number,i:any)=>s+Number(i.qty||0)*Number(i.cost||0),0))})));const total=r.reduce((s,x)=>s+x.value,0);return finalize("GRN Report",[{key:"date",label:"Date"},{key:"receiptNo",label:"GRN"},{key:"purchaseNo",label:"PO"},{key:"supplier",label:"Supplier"},{key:"warehouseId",label:"Warehouse"},{key:"items",label:"Items"},{key:"quantity",label:"Quantity"},{key:"value",label:"Value"}],r,[{label:"GRNs",value:r.length},{label:"Value",value:money(total)}],q,{period:range.preset});}
 if(id==="grocery-purchase-returns"){const ret=await db.purchaseReturn.findMany({where:{businessId,returnDate:{gte:range.from,lte:range.to}},include:{items:true},orderBy:{returnDate:"desc"}});const total=ret.reduce((s:number,x:any)=>s+Number(x.total||0),0);const r=ret.map((x:any)=>({date:x.returnDate,returnNo:x.returnNo,supplier:x.supplierName,items:(x.items||[]).length,quantity:qty((x.items||[]).reduce((s:number,i:any)=>s+Number(i.qty||i.returnQty||0),0)),amount:money(x.total),sharePct:pct(x.total,total),status:x.status}));return finalize("Purchase Returns",[{key:"date",label:"Date"},{key:"returnNo",label:"Return No"},{key:"supplier",label:"Supplier"},{key:"items",label:"Items"},{key:"quantity",label:"Quantity"},{key:"amount",label:"Amount"},{key:"sharePct",label:"% of Returns"},{key:"status",label:"Status"}],r,[{label:"Return Amount",value:money(total)},{label:"Returns",value:r.length}],q,{period:range.preset});}
 if(id==="grocery-purchase-supplier-payments"){const pays=await db.supplierPayment.findMany({where:{businessId,paymentDate:{gte:range.from,lte:range.to},...(text(q.supplierId)?{supplierId:text(q.supplierId)}:{})},orderBy:{paymentDate:"desc"}});const total=pays.reduce((s:number,x:any)=>s+Number(x.baseAmount||x.amount||0),0);const r=pays.map((x:any)=>({date:x.paymentDate,voucherNo:x.voucherNo,supplier:x.supplierName,method:x.method,reference:x.referenceNo||"-",amount:money(x.baseAmount||x.amount),sharePct:pct(x.baseAmount||x.amount,total)}));return finalize("Supplier Payment Report",[{key:"date",label:"Date"},{key:"voucherNo",label:"Voucher"},{key:"supplier",label:"Supplier"},{key:"method",label:"Method"},{key:"reference",label:"Reference"},{key:"amount",label:"Amount"},{key:"sharePct",label:"% of Payments"}],r,[{label:"Paid",value:money(total)},{label:"Payments",value:r.length}],q,{period:range.preset});}
 const products=await db.product.findMany({where:{businessId,deleted:false}});const pm=new Map(products.map((p:any)=>[String(p.id),p]));const branches=new Map((await db.branch.findMany({where:{businessId}})).map((x:any)=>[String(x.id),x]));const warehouses=new Map((await db.warehouse.findMany({where:{businessId}})).map((x:any)=>[String(x.id),x]));
 if(["grocery-purchase-product","grocery-purchase-supplier","grocery-purchase-category","grocery-purchase-branch","grocery-purchase-warehouse","grocery-purchase-status"].includes(id)){const group=new Map<string,any>();for(const p of purchases){const lines=id==="grocery-purchase-product"||id==="grocery-purchase-category"?(p.items||[]):[null];for(const i of lines){let key="",label="";if(id==="grocery-purchase-product"){key=String(i.productId||i.sku);label=i.name;}else if(id==="grocery-purchase-category"){const pr=pm.get(String(i.productId));key=text(pr?.category)||"Unassigned";label=key;}else if(id==="grocery-purchase-supplier"){key=String(p.supplierId||p.supplierName);label=p.supplierName;}else if(id==="grocery-purchase-branch"){key=String(p.branchId||"none");label=branches.get(key)?.name||"Unassigned Branch";}else if(id==="grocery-purchase-warehouse"){key=String(p.warehouseId||"none");label=warehouses.get(key)?.name||"Unassigned Warehouse";}else{key=text(json(p.metadata).workflowStatus||p.status);label=key;}const g=group.get(key)||{group:label,documents:new Set<string>(),quantity:0,purchases:0,payable:0};g.documents.add(p.id);g.quantity+=i?Number(i.qty||0):0;g.purchases+=i?Number(i.total||0):Number(p.total||0);g.payable+=i?0:Number(p.balance||0);group.set(key,g);}}const total=[...group.values()].reduce((s,g)=>s+g.purchases,0),payable=[...group.values()].reduce((s,g)=>s+g.payable,0);const r=[...group.values()].map(g=>({group:g.group,documents:g.documents.size,quantity:qty(g.quantity),purchaseAmount:money(g.purchases),purchasePct:pct(g.purchases,total),payable:money(g.payable),payablePct:pct(g.payable,payable)})).sort((a,b)=>b.purchaseAmount-a.purchaseAmount);return finalize(GROCERY_21_30_REPORTS.find(x=>x.id===id)!.title,[{key:"group",label:"Group"},{key:"documents",label:"Documents"},{key:"quantity",label:"Quantity"},{key:"purchaseAmount",label:"Purchase Amount"},{key:"purchasePct",label:"% of Total Purchases"},{key:"payable",label:"Payable"},{key:"payablePct",label:"% of Total Payables"}],r,[{label:"Purchases",value:money(total)},{label:"Payables",value:money(payable)},{label:"Documents",value:purchases.length}],q,{period:range.preset});}
 const total=purchases.reduce((s:number,p:any)=>s+Number(p.total||0),0);const r=purchases.map((p:any)=>{const extra=json(p.metadata);const lastCosts=(p.items||[]).map((i:any)=>({current:Number(i.cost||0),standard:Number(pm.get(String(i.productId))?.costPrice||0)}));const variance=lastCosts.reduce((s:number,x:any)=>s+(x.current-x.standard),0);return{date:p.purchaseDate,purchaseNo:p.purchaseNo,supplier:p.supplierName,status:extra.workflowStatus||p.status,warehouseId:p.warehouseId,total:money(p.total),paid:money(p.paid),balance:money(p.balance),paidPct:pct(p.paid,p.total),purchasePct:pct(p.total,total),dueDate:p.dueDate,costVariance:money(variance)}});let out=r;if(id==="grocery-purchase-due")out=r.filter(x=>x.balance>0).sort((a,b)=>new Date(a.dueDate||0).getTime()-new Date(b.dueDate||0).getTime());if(id==="grocery-purchase-cost-variance")out=r.filter(x=>Math.abs(x.costVariance)>.001).sort((a,b)=>Math.abs(b.costVariance)-Math.abs(a.costVariance));return finalize(GROCERY_21_30_REPORTS.find(x=>x.id===id)?.title||"Purchase Report",Object.keys(r[0]||{date:0,purchaseNo:0,supplier:0,status:0,warehouseId:0,total:0,paid:0,balance:0,paidPct:0,purchasePct:0,dueDate:0,costVariance:0}).map(k=>({key:k,label:k.replace(/([A-Z])/g," $1")})),out,[{label:"Purchases",value:money(total)},{label:"Paid",value:money(r.reduce((s,x)=>s+x.paid,0))},{label:"Payable",value:money(r.reduce((s,x)=>s+x.balance,0))}],q,{period:range.preset});}

async function inventoryReport(businessId:string,id:string,q:any){const range=presetRange(q);const [stocks,products,warehouses,branches,vans]=await Promise.all([db.inventoryStock.findMany({where:{businessId,...(text(q.warehouseId)?{warehouseId:text(q.warehouseId)}:{})}}),db.product.findMany({where:{businessId,deleted:false}}),db.warehouse.findMany({where:{businessId}}),db.branch.findMany({where:{businessId}}),db.industryRecord.findMany({where:{businessId,industryCode:"grocery",entityType:"grocery_van",archivedAt:null}})]);const pm=new Map(products.map((p:any)=>[String(p.id),p])),wm=new Map(warehouses.map((w:any)=>[String(w.id),w])),bm=new Map(branches.map((b:any)=>[String(b.id),b]));
 if(id==="grocery-inventory-van"){const vanMap=new Map(vans.map((v:any)=>[String(v.id),v]));const vs=await db.industryRecord.findMany({where:{businessId,industryCode:"grocery",entityType:"grocery_van_stock",archivedAt:null,...(text(q.vanId)?{relatedEntityId:text(q.vanId)}:{})}});const total=vs.reduce((s:number,x:any)=>{const d=json(x.data),p=pm.get(String(d.productId));return s+Number(d.qty||0)*Number(p?.costPrice||0)},0);const r=vs.map((x:any)=>{const d=json(x.data),p=pm.get(String(d.productId)),value=Number(d.qty||0)*Number(p?.costPrice||0);return{van:vanMap.get(String(x.relatedEntityId))?.displayName||x.relatedEntityId,sku:p?.sku||d.sku,product:p?.name||d.productName,quantity:qty(d.qty),unitCost:money(p?.costPrice),stockValue:money(value),valuePct:pct(value,total)}});return finalize("Stock by Van",[{key:"van",label:"Van"},{key:"sku",label:"SKU"},{key:"product",label:"Product"},{key:"quantity",label:"Quantity"},{key:"unitCost",label:"Unit Cost"},{key:"stockValue",label:"Stock Value"},{key:"valuePct",label:"% of Inventory Value"}],r,[{label:"Stock Value",value:money(total)},{label:"Lines",value:r.length}],q);}
 if(["grocery-inventory-movement","grocery-inventory-adjustment","grocery-inventory-damaged"].includes(id)){let movements=await db.stockMovement.findMany({where:{businessId,createdAt:{gte:range.from,lte:range.to},...(text(q.warehouseId)?{warehouseId:text(q.warehouseId)}:{})},orderBy:{createdAt:"desc"},take:20000});if(id==="grocery-inventory-adjustment")movements=movements.filter((m:any)=>text(m.movementType).toLowerCase().includes("adjust"));if(id==="grocery-inventory-damaged")movements=movements.filter((m:any)=>/damage|waste|spoil/i.test(text(m.movementType)));const total=movements.reduce((s:number,m:any)=>s+Math.abs(Number(m.qty||0))*Number(pm.get(String(m.productId))?.costPrice||0),0);const r=movements.map((m:any)=>{const p=pm.get(String(m.productId)),value=Math.abs(Number(m.qty||0))*Number(p?.costPrice||0);return{date:m.createdAt,movementNo:m.movementNo,type:m.movementType,direction:m.direction,product:m.productName,sku:m.sku,warehouse:wm.get(String(m.warehouseId))?.name||m.warehouseId,quantity:qty(m.qty),beforeQty:qty(m.beforeQty),afterQty:qty(m.afterQty),reference:m.referenceNo||"-",value:money(value),valuePct:pct(value,total)}});return finalize(GROCERY_21_30_REPORTS.find(x=>x.id===id)!.title,[{key:"date",label:"Date"},{key:"movementNo",label:"Movement"},{key:"type",label:"Type"},{key:"direction",label:"Direction"},{key:"product",label:"Product"},{key:"sku",label:"SKU"},{key:"warehouse",label:"Warehouse"},{key:"quantity",label:"Quantity"},{key:"beforeQty",label:"Before"},{key:"afterQty",label:"After"},{key:"reference",label:"Reference"},{key:"value",label:"Value"},{key:"valuePct",label:"% of Movement Value"}],r,[{label:"Movements",value:r.length},{label:"Value",value:money(total)}],q,{period:range.preset});}
 if(id==="grocery-inventory-transfer"){const tr=await db.stockTransfer.findMany({where:{businessId,createdAt:{gte:range.from,lte:range.to}},include:{items:true},orderBy:{createdAt:"desc"}}).catch(()=>[]);const r=tr.map((x:any)=>({date:x.createdAt,transferNo:x.transferNo||x.referenceNo||x.id,status:x.status,fromWarehouse:wm.get(String(x.fromWarehouseId))?.name||x.fromWarehouseId,toWarehouse:wm.get(String(x.toWarehouseId))?.name||x.toWarehouseId,items:(x.items||[]).length,quantity:qty((x.items||[]).reduce((s:number,i:any)=>s+Number(i.qty||i.quantity||0),0))}));return finalize("Stock Transfer",[{key:"date",label:"Date"},{key:"transferNo",label:"Transfer"},{key:"status",label:"Status"},{key:"fromWarehouse",label:"From"},{key:"toWarehouse",label:"To"},{key:"items",label:"Items"},{key:"quantity",label:"Quantity"}],r,[{label:"Transfers",value:r.length}],q,{period:range.preset});}
 if(id==="grocery-inventory-count-variance"){const counts=await db.inventoryCount.findMany({where:{businessId,createdAt:{gte:range.from,lte:range.to}},include:{items:true},orderBy:{createdAt:"desc"}}).catch(()=>[]);const r=counts.flatMap((c:any)=>(c.items||[]).map((i:any)=>({date:c.createdAt,countNo:c.countNo||c.referenceNo||c.id,status:c.status,warehouse:wm.get(String(c.warehouseId))?.name||c.warehouseId,product:i.productName||pm.get(String(i.productId))?.name,systemQty:qty(i.systemQty),physicalQty:qty(i.physicalQty),varianceQty:qty(Number(i.physicalQty||0)-Number(i.systemQty||0)),varianceValue:money(i.varianceValue||0)})));const total=Math.abs(r.reduce((s:number,x:any)=>s+Number(x.varianceValue||0),0));return finalize("Inventory Count Variance",[{key:"date",label:"Date"},{key:"countNo",label:"Count"},{key:"status",label:"Status"},{key:"warehouse",label:"Warehouse"},{key:"product",label:"Product"},{key:"systemQty",label:"System Qty"},{key:"physicalQty",label:"Physical Qty"},{key:"varianceQty",label:"Variance Qty"},{key:"varianceValue",label:"Variance Value"}],r,[{label:"Variance Value",value:money(total)},{label:"Lines",value:r.length}],q,{period:range.preset});}
 if(["grocery-inventory-expired","grocery-inventory-near-expiry","grocery-inventory-batch","grocery-inventory-ageing"].includes(id)){let batches=await db.inventoryBatch.findMany({where:{businessId,qtyOnHandBase:{gt:0},...(text(q.warehouseId)?{warehouseId:text(q.warehouseId)}:{})},orderBy:{expiryDate:"asc"}});const now=new Date();if(id==="grocery-inventory-expired")batches=batches.filter((b:any)=>b.expiryDate&&new Date(b.expiryDate)<now);if(id==="grocery-inventory-near-expiry"){const days=Math.max(1,Number(q.expiryDays||30));batches=batches.filter((b:any)=>b.expiryDate&&new Date(b.expiryDate)>=now&&new Date(b.expiryDate).getTime()<=now.getTime()+days*DAY);}const total=batches.reduce((s:number,b:any)=>s+Number(b.qtyOnHandBase||0)*Number(b.costPerBaseUnit||0),0);const r=batches.map((b:any)=>{const p=pm.get(String(b.productId)),value=Number(b.qtyOnHandBase||0)*Number(b.costPerBaseUnit||0);return{batch:b.batchNo,product:p?.name||b.productId,sku:p?.sku||"-",warehouse:wm.get(String(b.warehouseId))?.name||b.warehouseId,quantity:qty(b.qtyOnHandBase),unitCost:money(b.costPerBaseUnit),stockValue:money(value),valuePct:pct(value,total),productionDate:b.productionDate,expiryDate:b.expiryDate,ageDays:Math.max(0,Math.floor((now.getTime()-new Date(b.createdAt).getTime())/DAY)),daysToExpiry:b.expiryDate?Math.floor((new Date(b.expiryDate).getTime()-now.getTime())/DAY):null,status:b.status}});return finalize(GROCERY_21_30_REPORTS.find(x=>x.id===id)!.title,[{key:"batch",label:"Batch"},{key:"product",label:"Product"},{key:"sku",label:"SKU"},{key:"warehouse",label:"Warehouse"},{key:"quantity",label:"Quantity"},{key:"unitCost",label:"Unit Cost"},{key:"stockValue",label:"Stock Value"},{key:"valuePct",label:"% of Inventory Value"},{key:"productionDate",label:"Production"},{key:"expiryDate",label:"Expiry"},{key:"ageDays",label:"Age Days"},{key:"daysToExpiry",label:"Days to Expiry"},{key:"status",label:"Status"}],r,[{label:"Stock Value",value:money(total)},{label:"Batches",value:r.length}],q);}
 const raw=stocks.map((s:any)=>{const p=pm.get(String(s.productId)),w=wm.get(String(s.warehouseId)),branch=bm.get(String(w?.branchId));const quantity=Number(s.qtyOnHand||0),value=quantity*Number(p?.costPrice||0);return{sku:p?.sku||"-",product:p?.name||"Unknown",category:p?.category||"-",brand:p?.brand||"-",warehouse:w?.name||s.warehouseId,branch:branch?.name||"Unassigned",quantity:qty(quantity),reorderLevel:Number(p?.minStock||0),maxStock:Number(json(p?.customFields).grocery?.maxStock||0),unitCost:money(p?.costPrice),stockValue:money(value)}});const total=raw.reduce((s,r)=>s+r.stockValue,0);let rows=raw.map(r=>({...r,valuePct:pct(r.stockValue,total)}));if(id==="grocery-inventory-low")rows=rows.filter(r=>r.quantity>0&&r.quantity<=r.reorderLevel);if(id==="grocery-inventory-out")rows=rows.filter(r=>r.quantity<=0);if(id==="grocery-inventory-excess")rows=rows.filter(r=>r.maxStock>0&&r.quantity>r.maxStock);if(id==="grocery-inventory-dead"){const {docs}=await salesDocs(businessId,{...q,from:q.from||new Date(Date.now()-90*DAY).toISOString().slice(0,10),to:q.to||qatarDay()});const sold=new Set(docs.flatMap((d:any)=>(d.items||[]).map((i:any)=>String(i.productId))));rows=rows.filter(r=>r.quantity>0&&!sold.has(String(products.find((p:any)=>p.sku===r.sku)?.id)));}if(id==="grocery-inventory-warehouse")rows.sort((a,b)=>a.warehouse.localeCompare(b.warehouse));if(id==="grocery-inventory-branch")rows.sort((a,b)=>a.branch.localeCompare(b.branch));return finalize(GROCERY_21_30_REPORTS.find(x=>x.id===id)?.title||"Inventory Report",[{key:"sku",label:"SKU"},{key:"product",label:"Product"},{key:"category",label:"Category"},{key:"brand",label:"Brand"},{key:"warehouse",label:"Warehouse"},{key:"branch",label:"Branch"},{key:"quantity",label:"Quantity"},{key:"reorderLevel",label:"Reorder Level"},{key:"maxStock",label:"Max Stock"},{key:"unitCost",label:"Unit Cost"},{key:"stockValue",label:"Stock Value"},{key:"valuePct",label:"% of Total Inventory Value"}],rows,[{label:"Stock Value",value:money(total)},{label:"Lines",value:rows.length}],q);}

async function pnlPeriod(businessId:string,from:Date,to:Date){const [txns,docs]=await Promise.all([db.accountTransaction.findMany({where:{businessId,transactionDate:{gte:from,lte:to}},include:{account:true}}),db.salesDocument.findMany({where:{businessId,documentType:"INVOICE",createdAt:{gte:from,lte:to},status:{notIn:INVALID_SALE_STATUSES}},select:{discount:true,returnedAmount:true}})]);let netRevenue=0,cogs=0,operatingExpenses=0,otherIncome=0,otherExpenses=0;for(const t of txns){const a=t.account||{},type=text(a.type).toLowerCase(),system=text(json(a.metadata).systemCode).toLowerCase(),amount=Number(t.amount||0),signedIncome=text(t.type).toLowerCase()==="credit"?amount:-amount,signedExpense=text(t.type).toLowerCase()==="debit"?amount:-amount;if(type==="income"){if(system.includes("other"))otherIncome+=signedIncome;else netRevenue+=signedIncome;}else if(type==="cogs")cogs+=signedExpense;else if(type==="expense"){if(system.includes("other"))otherExpenses+=signedExpense;else operatingExpenses+=signedExpense;}}const discounts=docs.reduce((s:number,d:any)=>s+Number(d.discount||0),0),returns=docs.reduce((s:number,d:any)=>s+Number(d.returnedAmount||0),0),contra=discounts+returns,revenue=netRevenue+contra,grossProfit=netRevenue-cogs,operatingProfit=grossProfit-operatingExpenses,netProfit=operatingProfit+otherIncome-otherExpenses;return{revenue,contra,netRevenue,cogs,grossProfit,operatingExpenses,operatingProfit,otherIncome,otherExpenses,netProfit};}
async function pnlReport(businessId:string,q:any){const range=presetRange(q),compare=comparisonRange(range.from,range.to);const [cur,prev]=await Promise.all([pnlPeriod(businessId,range.from,range.to),pnlPeriod(businessId,compare.from,compare.to)]);const lines:[string,keyof typeof cur][]=[["Revenue","revenue"],["Less: Sales Returns / Discounts","contra"],["Net Revenue","netRevenue"],["Cost of Goods Sold","cogs"],["Gross Profit","grossProfit"],["Operating Expenses","operatingExpenses"],["Operating Profit","operatingProfit"],["Other Income","otherIncome"],["Other Expenses","otherExpenses"],["Net Profit","netProfit"]];const rows=lines.map(([label,key])=>{const amount=money(cur[key]),comparisonAmount=money(prev[key]),difference=money(amount-comparisonAmount);return{line:label,amount,comparisonAmount,difference,changePct:pct(difference,Math.abs(comparisonAmount)),revenuePct:pct(amount,cur.netRevenue||cur.revenue)}});return finalize("Profit & Loss",[{key:"line",label:"P&L Line"},{key:"amount",label:"Amount"},{key:"comparisonAmount",label:"Comparison Period"},{key:"difference",label:"Difference"},{key:"changePct",label:"% Change"},{key:"revenuePct",label:"% of Revenue"}],rows,[{label:"Net Revenue",value:money(cur.netRevenue)},{label:"Gross Profit",value:money(cur.grossProfit)},{label:"Operating Profit",value:money(cur.operatingProfit)},{label:"Net Profit",value:money(cur.netProfit)},{label:"Net Margin %",value:pct(cur.netProfit,cur.netRevenue),format:"percent"}],q,{period:range.preset,from:range.from,to:range.to,comparisonFrom:compare.from,comparisonTo:compare.to,accountingBasis:"accrual-ledger"});}

export function isGrocery21To30Report(id:string){return IDS.has(id);}
export function grocery21To30Catalog(){return GROCERY_21_30_REPORTS;}
export async function runGrocery21To30Report(businessId:string,id:string,q:any={}){if(!IDS.has(id))throw new ApiError(404,"Grocery report not found");await requireGrocery(businessId);const family=GROCERY_21_30_REPORTS.find(x=>x.id===id)?.family;if(family==="sales")return salesReport(businessId,id,q);if(family==="product")return productReport(businessId,id,q);if(family==="customer")return customerReport(businessId,id,q);if(family==="payment")return paymentReport(businessId,id,q);if(family==="purchase")return purchaseReport(businessId,id,q);if(family==="inventory")return inventoryReport(businessId,id,q);return pnlReport(businessId,q);}
