import crypto from "node:crypto";
import type { Request } from "express";
import { prisma } from "../db/prisma.js";
import { writeAudit } from "./audit.service.js";
import { nextEntityNumber } from "./numbering.service.js";
import { readGroceryProductProfile } from "../controllers/grocery-product-uom.controller.js";
import { assertGrocery } from "./grocery-41-50-valuation.service.js";

const db:any=prisma;
const IMPORT_TYPES=["products","categories","customers","suppliers","opening_stock","product_pricing"] as const;
const text=(v:unknown)=>String(v??"").trim();
const num=(v:unknown,f=0)=>{const n=Number(v);return Number.isFinite(n)?n:f;};
const qty=(v:unknown)=>Math.round((num(v)+Number.EPSILON)*1000)/1000;
const json=(v:unknown):Record<string,any>=>v&&typeof v==="object"&&!Array.isArray(v)?v as Record<string,any>:{};
const bool=(v:unknown,f=false)=>v===undefined||v===null||v===""?f:typeof v==="boolean"?v:["1","true","yes","on"].includes(String(v).toLowerCase());
const pageOf=(v:unknown)=>Math.max(1,Math.trunc(num(v,1))),limitOf=(v:unknown,d=50,max=250)=>Math.max(1,Math.min(max,Math.trunc(num(v,d))));
function stableRowsHash(entityType:string,rows:any[]){return crypto.createHash("sha256").update(JSON.stringify({entityType,rows})).digest("hex");}

async function validateImportRows(businessId:string,entityType:string,rows:any[],context:any={}){
 if(!(IMPORT_TYPES as readonly string[]).includes(entityType))throw new Error("Unsupported import entity type");if(!Array.isArray(rows)||!rows.length)throw new Error("Import rows are required");if(rows.length>5000)throw new Error("One import job is limited to 5,000 rows");
 const errors:any[]=[],accepted:any[]=[],seen=new Set<string>(),skuList=rows.map(r=>text(r?.sku)).filter(Boolean),products:any[]=skuList.length?await db.product.findMany({where:{businessId,sku:{in:[...new Set(skuList)]}}}):[],bySku=new Map<string,any>(products.map(p=>[text(p.sku).toLowerCase(),p])),warehouseId=text(context.warehouseId),warehouse=warehouseId?await db.warehouse.findFirst({where:{id:warehouseId,businessId,active:true}}):null;
 const openingProductIds=entityType==="opening_stock"?products.map(p=>String(p.id)):[],movementCounts=new Map<string,number>();if(openingProductIds.length){const grouped:any[]=await db.stockMovement.groupBy({by:["productId"],where:{businessId,productId:{in:openingProductIds}},_count:{_all:true}});for(const g of grouped)movementCounts.set(String(g.productId),Number(g._count?._all||0));}
 for(let index=0;index<rows.length;index++){const r=json(rows[index]),row=index+1,fail=(reason:string)=>errors.push({row,reason});
  if(entityType==="products"){const sku=text(r.sku),name=text(r.name),k=sku.toLowerCase();if(!sku||!name){fail("SKU and name are required");continue;}if(seen.has(k)){fail("Duplicate SKU in import");continue;}seen.add(k);if(num(r.price)<0||num(r.costPrice)<0){fail("Price and cost cannot be negative");continue;}accepted.push({row,data:{...r,sku,name}});}
  else if(entityType==="categories"){const name=text(r.name),k=name.toLowerCase();if(!name){fail("Category name is required");continue;}if(seen.has(k)){fail("Duplicate category in import");continue;}seen.add(k);accepted.push({row,data:{name,active:r.active===undefined?true:bool(r.active)}});}
  else if(entityType==="customers"){const name=text(r.name);if(!name){fail("Customer name is required");continue;}if(num(r.creditLimit)<0||num(r.creditDays)<0){fail("Credit values cannot be negative");continue;}accepted.push({row,data:{...r,name}});}
  else if(entityType==="suppliers"){const name=text(r.name);if(!name){fail("Supplier name is required");continue;}if(num(r.creditDays)<0){fail("Credit days cannot be negative");continue;}accepted.push({row,data:{...r,name}});}
  else if(entityType==="opening_stock"){const sku=text(r.sku),amount=qty(r.quantity??r.qty),p=bySku.get(sku.toLowerCase());if(!warehouse){fail("A valid warehouse is required for opening stock");continue;}if(!sku||!p){fail("Existing product SKU is required");continue;}if(amount<0){fail("Opening quantity cannot be negative");continue;}if((movementCounts.get(String(p.id))||0)>0||Math.abs(num(p.currentStock))>.0001){fail("Opening stock can only be imported before stock movements exist");continue;}accepted.push({row,data:{...r,productId:String(p.id),warehouseId:String(warehouse.id),quantity:amount}});}
  else if(entityType==="product_pricing"){const sku=text(r.sku),p=bySku.get(sku.toLowerCase());if(!sku||!p){fail("Existing product SKU is required");continue;}if(["retailPrice","wholesalePrice","memberPrice","promotionalPrice","minimumSellingPrice"].some(k=>r[k]!==undefined&&num(r[k])<0)){fail("Prices cannot be negative");continue;}accepted.push({row,data:{...r,productId:String(p.id)}});}
 }
 return{accepted,errors};
}

export async function previewImport(req:Request,businessId:string,userId:string|null,input:any){await assertGrocery(businessId);const entityType=text(input.entityType).toLowerCase(),rows=Array.isArray(input.rows)?input.rows:[],validation=await validateImportRows(businessId,entityType,rows,input),hash=stableRowsHash(entityType,rows),job=await db.dataImportJob.create({data:{businessId,entityType,status:"preview",fileName:text(input.fileName)||null,totalRows:rows.length,validRows:validation.accepted.length,errorRows:validation.errors.length,errors:{rowErrors:validation.errors,previewHash:hash,context:{warehouseId:text(input.warehouseId)||null}},createdByUserId:userId}});await writeAudit(db,req,{businessId,userId,action:"grocery.import.preview",entityType:"DataImportJob",entityId:job.id,after:{entityType,totalRows:rows.length,validRows:validation.accepted.length,errorRows:validation.errors.length}});return{jobId:job.id,entityType,totalRows:rows.length,acceptedRows:validation.accepted.map(x=>x.row),rejectedRows:validation.errors,canCommit:validation.errors.length===0,previewHash:hash};}

export async function commitImport(req:Request,businessId:string,userId:string|null,input:any){
 await assertGrocery(businessId);const job=await db.dataImportJob.findFirst({where:{id:text(input.jobId),businessId,status:"preview"}});if(!job)throw new Error("Preview import job not found or already committed");const entityType=text(job.entityType),rows=Array.isArray(input.rows)?input.rows:[],meta=json(job.errors);if(stableRowsHash(entityType,rows)!==text(meta.previewHash))throw new Error("Import rows changed after preview; preview the exact dataset again");const validation=await validateImportRows(businessId,entityType,rows,{warehouseId:meta.context?.warehouseId});if(validation.errors.length)throw new Error("Import contains rejected rows and cannot be committed");
 return db.$transaction(async(tx:any)=>{let committed=0;for(const wrapped of validation.accepted){const r=json(wrapped.data);
  if(entityType==="categories"){const existing=await tx.productCategory.findFirst({where:{businessId,name:r.name}});if(existing)await tx.productCategory.update({where:{id:existing.id},data:{active:r.active!==false}});else await tx.productCategory.create({data:{businessId,name:r.name,active:r.active!==false}});committed++;}
  else if(entityType==="products"){const existing=await tx.product.findUnique({where:{businessId_sku:{businessId,sku:r.sku}}}),data:any={name:r.name,barcode:text(r.barcode)||null,qrCode:text(r.qrCode)||null,code:text(r.code)||null,itemCode:text(r.itemCode)||null,productCode:text(r.productCode)||null,category:text(r.category)||null,brand:text(r.brand)||null,unit:text(r.unit)||"PCS",price:Math.max(0,num(r.price)),costPrice:Math.max(0,num(r.costPrice)),minStock:Math.max(0,num(r.minStock)),active:r.active===undefined?true:bool(r.active),deleted:false};if(existing)await tx.product.update({where:{id:existing.id},data});else await tx.product.create({data:{businessId,sku:r.sku,openingStock:0,currentStock:0,...data}});committed++;}
  else if(entityType==="customers"){const code=text(r.code),existing=code?await tx.customer.findFirst({where:{businessId,code}}):null,data:any={name:r.name,code:code||null,company:text(r.company)||null,phone:text(r.phone)||null,email:text(r.email).toLowerCase()||null,type:text(r.type)||"Retail",address:text(r.address)||null,creditLimit:Math.max(0,num(r.creditLimit)),creditDays:Math.max(0,Math.trunc(num(r.creditDays,30))),active:r.active===undefined?true:bool(r.active),status:r.active===false?"inactive":"active"};if(existing)await tx.customer.update({where:{id:existing.id},data});else await tx.customer.create({data:{businessId,openingBalance:num(r.openingBalance),balance:num(r.openingBalance),...data}});committed++;}
  else if(entityType==="suppliers"){const company=text(r.company)||null,existing=await tx.supplier.findFirst({where:{businessId,name:r.name,company}}),data:any={name:r.name,company,phone:text(r.phone)||null,email:text(r.email)||null,address:text(r.address)||null,creditDays:Math.max(0,Math.trunc(num(r.creditDays,30))),active:r.active===undefined?true:bool(r.active)};if(existing)await tx.supplier.update({where:{id:existing.id},data});else await tx.supplier.create({data:{businessId,openingBalance:num(r.openingBalance),balance:num(r.openingBalance),...data}});committed++;}
  else if(entityType==="opening_stock"){const p=await tx.product.findFirst({where:{id:r.productId,businessId}});if(!p)throw new Error("Product disappeared during opening-stock import");const amount=qty(r.quantity),cost=Math.max(0,num(r.costPrice,p.costPrice)),existingStock=await tx.inventoryStock.findUnique({where:{businessId_productId_warehouseId:{businessId,productId:p.id,warehouseId:r.warehouseId}}});if(existingStock&&Math.abs(num(existingStock.qtyOnHand))>.0001)throw new Error(`${p.sku}: warehouse already contains stock`);await tx.inventoryStock.upsert({where:{businessId_productId_warehouseId:{businessId,productId:p.id,warehouseId:r.warehouseId}},create:{businessId,productId:p.id,warehouseId:r.warehouseId,qtyOnHand:amount},update:{qtyOnHand:amount}});await tx.product.update({where:{id:p.id},data:{openingStock:amount,currentStock:amount,costPrice:cost}});if(amount>0){const batch=await tx.inventoryBatch.create({data:{businessId,productId:p.id,warehouseId:r.warehouseId,batchNo:text(r.batchNo)||`OPEN-${p.sku}`,qtyOnHandBase:amount,qtyReservedBase:0,costPerBaseUnit:cost,status:"available",createdByUserId:userId,updatedByUserId:userId}});await tx.stockMovement.create({data:{businessId,movementNo:await nextEntityNumber(tx,"stockMovement","movementNo",businessId,"MOV"),productId:p.id,sku:p.sku,productName:p.name,warehouseId:r.warehouseId,direction:"IN",movementType:"OPENING_STOCK",referenceNo:job.id,qty:amount,beforeQty:0,afterQty:amount,source:"grocery_bulk_import",metadata:{importJobId:job.id,inventoryBatchId:batch.id,costPerBaseUnit:cost}}});}committed++;}
  else if(entityType==="product_pricing"){const p=await tx.product.findFirst({where:{id:r.productId,businessId}});if(!p)throw new Error("Product disappeared during pricing import");const before=readGroceryProductProfile(p),cf=json(p.customFields),next={...before,...(r.retailPrice!==undefined?{retailPrice:Math.max(0,num(r.retailPrice))}:{}),...(r.wholesalePrice!==undefined?{wholesalePrice:Math.max(0,num(r.wholesalePrice))}:{}),...(r.memberPrice!==undefined?{memberPrice:Math.max(0,num(r.memberPrice))}:{}),...(r.promotionalPrice!==undefined?{promotionalPrice:Math.max(0,num(r.promotionalPrice))}:{}),...(r.minimumSellingPrice!==undefined?{minimumSellingPrice:Math.max(0,num(r.minimumSellingPrice))}:{})};await tx.product.update({where:{id:p.id},data:{price:next.retailPrice,customFields:{...cf,grocery:next}}});const changed=["retailPrice","wholesalePrice","memberPrice","promotionalPrice","minimumSellingPrice"].filter(k=>Number((before as any)[k]||0)!==Number((next as any)[k]||0));if(changed.length)await tx.industryRecord.create({data:{businessId,industryCode:"grocery",entityType:"grocery_price_history",referenceNo:`PRICE-${p.id}-${Date.now()}-${wrapped.row}`,displayName:`${p.name} price change`,relatedEntityId:p.id,status:"posted",startAt:new Date(),data:{productId:p.id,sku:p.sku,productName:p.name,previous:Object.fromEntries(changed.map(k=>[k,(before as any)[k]])),next:Object.fromEntries(changed.map(k=>[k,(next as any)[k]])),changedFields:changed,reason:"Bulk product pricing import",importJobId:job.id},createdByUserId:userId,updatedByUserId:userId}});committed++;}
 }
 await tx.dataImportJob.update({where:{id:job.id},data:{status:"completed",completedAt:new Date(),validRows:committed,errorRows:0}});await writeAudit(tx,req,{businessId,userId,action:"grocery.import.commit",entityType:"DataImportJob",entityId:job.id,after:{entityType,committed}});return{jobId:job.id,entityType,committed};});
}

export async function exportDataset(businessId:string,entityType:string,query:any={}){await assertGrocery(businessId);entityType=text(entityType).toLowerCase();if(!(IMPORT_TYPES as readonly string[]).includes(entityType))throw new Error("Unsupported export entity type");const page=pageOf(query.page),limit=limitOf(query.limit??query.pageSize,500,5000),skip=(page-1)*limit;let rows:any[]=[],total=0;
 if(entityType==="products"){[rows,total]=await Promise.all([db.product.findMany({where:{businessId,deleted:false},orderBy:{sku:"asc"},skip,take:limit}),db.product.count({where:{businessId,deleted:false}})]);rows=rows.map(p=>({sku:p.sku,name:p.name,barcode:p.barcode,category:p.category,brand:p.brand,unit:p.unit,price:Number(p.price),costPrice:Number(p.costPrice),minStock:Number(p.minStock),currentStock:Number(p.currentStock)}));}
 else if(entityType==="categories"){[rows,total]=await Promise.all([db.productCategory.findMany({where:{businessId},orderBy:{name:"asc"},skip,take:limit}),db.productCategory.count({where:{businessId}})]);}
 else if(entityType==="customers"){[rows,total]=await Promise.all([db.customer.findMany({where:{businessId},orderBy:{name:"asc"},skip,take:limit}),db.customer.count({where:{businessId}})]);}
 else if(entityType==="suppliers"){[rows,total]=await Promise.all([db.supplier.findMany({where:{businessId},orderBy:{name:"asc"},skip,take:limit}),db.supplier.count({where:{businessId}})]);}
 else if(entityType==="opening_stock"){[rows,total]=await Promise.all([db.inventoryStock.findMany({where:{businessId},skip,take:limit}),db.inventoryStock.count({where:{businessId}})]);}
 else{const products:any[]=await db.product.findMany({where:{businessId,deleted:false},orderBy:{sku:"asc"},skip,take:limit});total=await db.product.count({where:{businessId,deleted:false}});rows=products.map(p=>{const g=readGroceryProductProfile(p);return{sku:p.sku,retailPrice:g.retailPrice,wholesalePrice:g.wholesalePrice,memberPrice:g.memberPrice,promotionalPrice:g.promotionalPrice,minimumSellingPrice:g.minimumSellingPrice};});}
 return{entityType,rows,meta:{page,pageSize:limit,totalRows:total,totalPages:Math.max(1,Math.ceil(total/limit))}};
}

export async function globalSearch(businessId:string,query:any={}){await assertGrocery(businessId);const q=text(query.q);if(q.length<2)throw new Error("Search requires at least 2 characters");const take=limitOf(query.limit,10,25),contains={contains:q,mode:"insensitive"};const [products,customers,suppliers,sales,purchases,grns,cheques,customerPayments,supplierPayments]=await Promise.all([
 db.product.findMany({where:{businessId,deleted:false,OR:[{name:contains},{sku:contains},{barcode:contains},{code:contains},{itemCode:contains},{productCode:contains}]},select:{id:true,name:true,sku:true,barcode:true,category:true},take,orderBy:{name:"asc"}}),db.customer.findMany({where:{businessId,OR:[{name:contains},{code:contains},{company:contains},{phone:contains},{email:contains}]},select:{id:true,name:true,code:true,phone:true,balance:true},take,orderBy:{name:"asc"}}),db.supplier.findMany({where:{businessId,OR:[{name:contains},{company:contains},{phone:contains},{email:contains}]},select:{id:true,name:true,phone:true,balance:true},take,orderBy:{name:"asc"}}),db.salesDocument.findMany({where:{businessId,OR:[{documentNo:contains},{customerName:contains},{referenceNo:contains}]},select:{id:true,documentNo:true,customerName:true,total:true,status:true,createdAt:true},take,orderBy:{createdAt:"desc"}}),db.purchase.findMany({where:{businessId,OR:[{purchaseNo:contains},{supplierName:contains},{referenceNo:contains}]},select:{id:true,purchaseNo:true,supplierName:true,total:true,status:true,purchaseDate:true},take,orderBy:{purchaseDate:"desc"}}),db.goodsReceipt.findMany({where:{businessId,OR:[{receiptNo:contains},{notes:contains}]},select:{id:true,receiptNo:true,purchaseId:true,receivedAt:true},take,orderBy:{receivedAt:"desc"}}),db.industryRecord.findMany({where:{businessId,industryCode:"grocery",entityType:"grocery_cheque",OR:[{referenceNo:contains},{displayName:contains}]},select:{id:true,referenceNo:true,displayName:true,status:true,dueAt:true,amount:true},take,orderBy:{dueAt:"desc"}}),db.customerPayment.findMany({where:{businessId,OR:[{receiptNo:contains},{customerName:contains},{referenceNo:contains}]},select:{id:true,receiptNo:true,customerName:true,amount:true,paymentDate:true},take,orderBy:{paymentDate:"desc"}}),db.supplierPayment.findMany({where:{businessId,OR:[{voucherNo:contains},{supplierName:contains},{referenceNo:contains}]},select:{id:true,voucherNo:true,supplierName:true,amount:true,paymentDate:true,referenceNo:true},take,orderBy:{paymentDate:"desc"}}),
 ]);return{query:q,groups:{products,customers,suppliers,sales,purchases,grns,cheques,vouchers:[...(customerPayments as any[]).map(x=>({...x,voucherType:"receipt"})),...(supplierPayments as any[]).map(x=>({...x,paymentNo:x.voucherNo,voucherType:"payment"}))].slice(0,take)},meta:{limitPerGroup:take,serverSide:true}};}
