import type { Request } from "express";
import { prisma } from "../db/prisma.js";
import { writeAudit } from "./audit.service.js";
import { readGroceryProductProfile } from "../controllers/grocery-product-uom.controller.js";
import { assertGrocery, GROCERY_PRINT_TEMPLATES } from "./grocery-41-50-valuation.service.js";

const db:any=prisma;
const text=(v:unknown)=>String(v??"").trim();
const num=(v:unknown,f=0)=>{const n=Number(v);return Number.isFinite(n)?n:f;};
const bool=(v:unknown,f=false)=>v===undefined||v===null||v===""?f:typeof v==="boolean"?v:["1","true","yes","on"].includes(String(v).toLowerCase());
const json=(v:unknown):Record<string,any>=>v&&typeof v==="object"&&!Array.isArray(v)?v as Record<string,any>:{};

function printDefaults(code:string,documentType:string,paperSize:string,widthMm:number|null=null){return{code,name:code.replaceAll("_"," ").replace(/\b\w/g,m=>m.toUpperCase()),documentType,paperSize,widthMm,heightMm:null,marginTopMm:paperSize.endsWith("mm")?3:8,marginRightMm:paperSize.endsWith("mm")?3:8,marginBottomMm:paperSize.endsWith("mm")?3:8,marginLeftMm:paperSize.endsWith("mm")?3:8,fontScale:1,bilingual:false,copies:["Original"],isDefault:true,active:true,config:{showLogo:true,showAddress:true,showPhone:true,showTaxNumber:true,showQr:true,showBarcode:true,showCashier:true,showCounter:true,showCustomer:true,showInvoiceNumber:true,showTaxSummary:true,footer:"",terms:""}};}

export async function ensurePrintProfiles(businessId:string,userId:string|null){for(const row of [printDefaults("thermal_58","sales_receipt","58mm",58),printDefaults("thermal_80","sales_receipt","80mm",80),printDefaults("a5_standard","document","A5"),printDefaults("a4_standard","document","A4"),printDefaults("letter_standard","document","Letter")])await db.printProfile.upsert({where:{businessId_code:{businessId,code:row.code}},create:{businessId,...row,createdByUserId:userId,updatedByUserId:userId},update:{}});}
export async function listPrintProfiles(businessId:string,userId:string|null){await assertGrocery(businessId);await ensurePrintProfiles(businessId,userId);return{templates:[...GROCERY_PRINT_TEMPLATES],paperSizes:["58mm","80mm","A5","A4","Letter"],profiles:await db.printProfile.findMany({where:{businessId,active:true},orderBy:[{documentType:"asc"},{code:"asc"}]})};}

export async function savePrintProfile(req:Request,businessId:string,userId:string|null,code:string,input:any){await assertGrocery(businessId);code=text(code);if(!code)throw new Error("Print profile code is required");const paperSize=text(input.paperSize||"A4");if(!["58mm","80mm","A5","A4","Letter"].includes(paperSize))throw new Error("Unsupported paper size");const before=await db.printProfile.findUnique({where:{businessId_code:{businessId,code}}}),base:any={name:text(input.name)||code,documentType:text(input.documentType)||"document",paperSize,widthMm:paperSize==="58mm"?58:paperSize==="80mm"?80:null,heightMm:input.heightMm==null?null:num(input.heightMm),marginTopMm:Math.max(0,num(input.marginTopMm,8)),marginRightMm:Math.max(0,num(input.marginRightMm,8)),marginBottomMm:Math.max(0,num(input.marginBottomMm,8)),marginLeftMm:Math.max(0,num(input.marginLeftMm,8)),fontScale:Math.max(.5,Math.min(2,num(input.fontScale,1))),bilingual:bool(input.bilingual),copies:Array.isArray(input.copies)&&input.copies.length?input.copies.map(text).filter(Boolean):["Original"],isDefault:bool(input.isDefault),active:input.active===undefined?true:bool(input.active),config:json(input.config),updatedByUserId:userId};const row=await db.printProfile.upsert({where:{businessId_code:{businessId,code}},create:{businessId,code,...base,createdByUserId:userId},update:base});await writeAudit(db,req,{businessId,userId,action:"grocery.print_profile.save",entityType:"PrintProfile",entityId:row.id,before:before||undefined,after:row});return row;}

async function businessIdentity(businessId:string){const [business,settings]=await Promise.all([db.business.findUnique({where:{id:businessId}}),db.appSetting.findMany({where:{businessId,key:{startsWith:"grocery."}}})]);const values=Object.fromEntries((settings as any[]).map(s=>[s.key,s.value]));return{name:business?.name,legalName:business?.legalName,address:values["grocery.business.address"]||"",phone:values["grocery.business.contact"]||"",taxNumber:business?.taxNumber,currency:business?.currency||"QAR",timezone:business?.timezone||"Asia/Qatar",logo:values["grocery.business.logo"]||null,footer:values["grocery.printing.footer"]||""};}

export async function printableDocument(businessId:string,type:string,id:string){await assertGrocery(businessId);type=text(type).toLowerCase();id=text(id);let document:any=null;if(["sales_receipt","tax_invoice","credit_invoice","quotation"].includes(type))document=await db.salesDocument.findFirst({where:{id,businessId},include:{items:true}});else if(type==="sales_return")document=await db.salesReturn.findFirst({where:{id,businessId},include:{items:true,sourceSalesDocument:{select:{documentNo:true}}}});else if(["customer_payment_receipt","receipt_voucher"].includes(type))document=await db.customerPayment.findFirst({where:{id,businessId}});else if(type==="customer_statement"){const customer=await db.customer.findFirst({where:{id,businessId}});if(customer){const [sales,payments]=await Promise.all([db.salesDocument.findMany({where:{businessId,customerId:id,documentType:"INVOICE"},orderBy:{createdAt:"desc"},take:500}),db.customerPayment.findMany({where:{businessId,customerId:id},orderBy:{paymentDate:"desc"},take:500})]);document={customer,sales,payments};}}else if(["purchase_order","purchase_invoice"].includes(type))document=await db.purchase.findFirst({where:{id,businessId},include:{items:true}});else if(type==="grn")document=await db.goodsReceipt.findFirst({where:{id,businessId},include:{items:true,purchase:{select:{purchaseNo:true,supplierName:true}}}});else if(type==="purchase_return")document=await db.purchaseReturn.findFirst({where:{id,businessId},include:{items:true}});else if(["supplier_payment_voucher","payment_voucher"].includes(type))document=await db.supplierPayment.findFirst({where:{id,businessId}});else if(type==="stock_count")document=await db.stockCount.findFirst({where:{id,businessId},include:{items:true}});else if(type==="expense_voucher")document=await db.expense.findFirst({where:{id,businessId}});else if(["stock_transfer","journal_voucher"].includes(type))document=await db.industryRecord.findFirst({where:{id,businessId,industryCode:"grocery"}});if(!document)throw new Error("Printable document not found");return{type,business:await businessIdentity(businessId),document};}

export async function labelPreview(businessId:string,input:any){await assertGrocery(businessId);const ids=[...new Set<string>((Array.isArray(input.productIds)?input.productIds:input.productId?[input.productId]:[]).map(text).filter(Boolean))].slice(0,100);if(!ids.length)throw new Error("At least one product is required");const copies=Math.max(1,Math.min(100,Math.trunc(num(input.quantity,1))));if(ids.length*copies>500)throw new Error("A label preview is limited to 500 labels");const labelType=text(input.labelType||"product_barcode"),barcodeType=text(input.barcodeType||"CODE128").toUpperCase();if(!["product_barcode","shelf_label","price_label"].includes(labelType))throw new Error("Unsupported label type");if(!["CODE128","EAN13","EAN8","UPC","QR"].includes(barcodeType))throw new Error("Unsupported barcode type");const products:any[]=await db.product.findMany({where:{businessId,id:{in:ids},deleted:false,active:true}}),labels:any[]=[];for(const p of products){const gp=readGroceryProductProfile(p),value=p.barcode||gp.barcodes[0]||p.sku;for(let i=0;i<copies;i++)labels.push({type:labelType,productId:p.id,name:p.name,sku:p.sku,barcode:value,barcodeType,unit:gp.baseUnit||p.unit,price:bool(input.showPrice,true)?Number(p.price):null,promotionalPrice:gp.promotionalPrice>0?gp.promotionalPrice:null,dimensions:{widthMm:Math.max(20,Math.min(150,num(input.widthMm,labelType==="shelf_label"?70:50))),heightMm:Math.max(15,Math.min(100,num(input.heightMm,labelType==="shelf_label"?35:30)))}});}return{labels,count:labels.length,printerFriendly:true};}
