import type { Request } from "express";
import { prisma } from "../db/prisma.js";
import { writeAudit } from "./audit.service.js";
import { assertGrocery, stockValuation } from "./grocery-41-50-valuation.service.js";

const db:any=prisma;
const DAY=86_400_000,INVALID_SALES=["DRAFT","CANCELLED","VOID"];
const text=(v:unknown)=>String(v??"").trim();
const num=(v:unknown,f=0)=>{const n=Number(v);return Number.isFinite(n)?n:f;};
const money=(v:unknown)=>Math.round((num(v)+Number.EPSILON)*100)/100;
const json=(v:unknown):Record<string,any>=>v&&typeof v==="object"&&!Array.isArray(v)?v as Record<string,any>:{};
const bool=(v:unknown,f=false)=>v===undefined||v===null||v===""?f:typeof v==="boolean"?v:["1","true","yes","on"].includes(String(v).toLowerCase());

export const GROCERY_SETTING_DEFAULTS:Record<string,any>={
 "grocery.business.logo":null,"grocery.business.address":"","grocery.business.contact":"",
 "grocery.pos.defaultCustomerId":null,"grocery.pos.defaultWarehouseId":null,"grocery.pos.defaultCounterId":null,"grocery.pos.receiptSize":"80mm","grocery.pos.allowNegativeStock":false,"grocery.pos.rounding":0.01,"grocery.pos.defaultPaymentMethod":"cash","grocery.pos.allowHoldSale":true,"grocery.pos.sound":true,"grocery.pos.barcodeBehavior":"scan_and_add",
 "grocery.sales.invoicePrefix":"INV","grocery.sales.quotationPrefix":"QUO","grocery.sales.paymentTermsDays":0,"grocery.sales.enforceCreditLimit":true,"grocery.sales.defaultDueDays":0,"grocery.sales.allowDiscounts":true,"grocery.sales.allowReturns":true,
 "grocery.purchases.poPrefix":"PO","grocery.purchases.grnPrefix":"GRN","grocery.purchases.invoicePrefix":"PINV","grocery.purchases.supplierPaymentTermsDays":30,"grocery.purchases.approvalLevel":0,
 "grocery.inventory.valuationMethod":"weighted_average","grocery.inventory.batchTracking":true,"grocery.inventory.expiryTracking":true,"grocery.inventory.allowNegative":false,"grocery.inventory.reorderEnabled":true,"grocery.inventory.fefo":true,"grocery.inventory.countApprovalRequired":true,
 "grocery.accounting.fiscalYearStartMonth":1,"grocery.accounting.basis":"accrual",
 "grocery.printing.receiptPaper":"80mm","grocery.printing.invoiceTemplate":"standard","grocery.printing.footer":"","grocery.printing.printerPreference":"browser","grocery.printing.copies":1,
 "grocery.notifications.expiryDays":30,"grocery.notifications.customerDueDays":7,"grocery.notifications.supplierDueDays":7,"grocery.notifications.lowStockThreshold":0,"grocery.notifications.chequeReminderDays":7,"grocery.notifications.largeDiscountAmount":100,"grocery.notifications.largeRefundAmount":100,
};

function qatarDayBounds(date=new Date()){const key=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Qatar",year:"numeric",month:"2-digit",day:"2-digit"}).format(date);return{key,from:new Date(`${key}T00:00:00.000+03:00`),to:new Date(`${key}T23:59:59.999+03:00`)};}
function qatarMonthBounds(date=new Date()){const parts=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Qatar",year:"numeric",month:"2-digit"}).format(date).split("-");const y=Number(parts[0]),m=Number(parts[1]);const from=new Date(`${y}-${String(m).padStart(2,"0")}-01T00:00:00.000+03:00`),nextM=m===12?1:m+1,nextY=m===12?y+1:y,to=new Date(new Date(`${nextY}-${String(nextM).padStart(2,"0")}-01T00:00:00.000+03:00`).getTime()-1);return{from,to};}
async function saleTotals(businessId:string,from:Date,to:Date){const docs:any[]=await db.salesDocument.findMany({where:{businessId,documentType:"INVOICE",status:{notIn:INVALID_SALES},createdAt:{gte:from,lte:to}},select:{total:true,metadata:true}});const sales=money(docs.reduce((s,d)=>s+num(d.total),0)),cogs=money(docs.reduce((s,d)=>s+num(json(d.metadata).groceryCostSnapshot?.totalCogs),0));return{sales,cogs,profit:money(sales-cogs),count:docs.length};}
function comparison(current:number,previous:number){if(Math.abs(previous)<.000001)return{previous:money(previous),difference:money(current-previous),changePct:null,valid:false};return{previous:money(previous),difference:money(current-previous),changePct:money((current-previous)/Math.abs(previous)*100),valid:true};}

export async function groceryDashboard41To50(businessId:string){
 await assertGrocery(businessId);const today=qatarDayBounds(),yesterday=qatarDayBounds(new Date(today.from.getTime()-DAY)),weekFrom=new Date(today.from.getTime()-7*DAY),priorWeekFrom=new Date(today.from.getTime()-14*DAY),month=qatarMonthBounds(today.from),priorMonth=qatarMonthBounds(new Date(month.from.getTime()-DAY));
 const [todaySales,yesterdaySales,thisWeekSales,priorWeekSales,thisMonthSales,priorMonthSales,purchases,expenses,receivables,payables,lowRows,expiring,overdueCustomers,supplierDue,chequesDue,accounts,valuation,trendDocs,topDocs]=await Promise.all([
  saleTotals(businessId,today.from,today.to),saleTotals(businessId,yesterday.from,yesterday.to),saleTotals(businessId,weekFrom,today.to),saleTotals(businessId,priorWeekFrom,new Date(weekFrom.getTime()-1)),saleTotals(businessId,month.from,month.to),saleTotals(businessId,priorMonth.from,priorMonth.to),
  db.purchase.aggregate({where:{businessId,purchaseDate:{gte:today.from,lte:today.to},status:{not:"CANCELLED"}},_sum:{total:true}}),db.expense.aggregate({where:{businessId,expenseDate:{gte:today.from,lte:today.to}},_sum:{amount:true}}),db.customer.aggregate({where:{businessId,active:true,balance:{gt:0}},_sum:{balance:true}}),db.supplier.aggregate({where:{businessId,active:true,balance:{gt:0}},_sum:{balance:true}}),
  db.$queryRawUnsafe(`SELECT COUNT(*)::int AS count FROM products WHERE business_id=$1 AND deleted=false AND active=true AND current_stock<=min_stock`,businessId),
  db.inventoryBatch.count({where:{businessId,qtyOnHandBase:{gt:0},expiryDate:{gte:today.from,lte:new Date(today.from.getTime()+30*DAY)},status:{notIn:["depleted","quarantined"]}}}),db.salesDocument.count({where:{businessId,documentType:"INVOICE",balance:{gt:0},dueDate:{lt:today.from},status:{notIn:INVALID_SALES}}}),db.purchase.count({where:{businessId,balance:{gt:0},dueDate:{lte:new Date(today.from.getTime()+7*DAY)},status:{not:"CANCELLED"}}}),db.industryRecord.count({where:{businessId,industryCode:"grocery",entityType:"grocery_cheque",dueAt:{lte:new Date(today.from.getTime()+7*DAY)},status:{notIn:["cleared","cancelled","replaced"]}}}),db.account.findMany({where:{businessId,active:true},select:{type:true,currentBalance:true}}),stockValuation(businessId,{page:1,limit:1}),
  db.salesDocument.findMany({where:{businessId,documentType:"INVOICE",status:{notIn:INVALID_SALES},createdAt:{gte:new Date(today.from.getTime()-13*DAY),lte:today.to}},select:{createdAt:true,total:true,paymentMethod:true,metadata:true},orderBy:{createdAt:"asc"},take:10000}),db.salesDocument.findMany({where:{businessId,documentType:"INVOICE",status:{notIn:INVALID_SALES},createdAt:{gte:new Date(today.from.getTime()-30*DAY),lte:today.to}},include:{items:true},orderBy:{createdAt:"desc"},take:5000}),
 ]);
 const trend=new Map<string,{date:string;sales:number;profit:number}>(),payments=new Map<string,number>();for(const d of trendDocs as any[]){const k=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Qatar"}).format(d.createdAt),row=trend.get(k)||{date:k,sales:0,profit:0},cogs=num(json(d.metadata).groceryCostSnapshot?.totalCogs);row.sales+=num(d.total);row.profit+=num(d.total)-cogs;trend.set(k,row);const pm=text(d.paymentMethod||"other").toLowerCase();payments.set(pm,(payments.get(pm)||0)+num(d.total));}
 const productTotals=new Map<string,{product:string;quantity:number;sales:number}>(),categoryTotals=new Map<string,number>(),customerTotals=new Map<string,number>();const productIds:string[]=[...new Set<string>((topDocs as any[]).flatMap(d=>d.items.map((i:any)=>text(i.productId)).filter(Boolean)))],products:any[]=productIds.length?await db.product.findMany({where:{businessId,id:{in:productIds}},select:{id:true,category:true}}):[],catMap=new Map<string,string>(products.map(p=>[String(p.id),text(p.category)||"Uncategorized"]));
 for(const d of topDocs as any[]){const cn=text(d.customerName)||"Walk-in Customer";customerTotals.set(cn,(customerTotals.get(cn)||0)+num(d.total));for(const i of d.items){const key=String(i.productId||i.sku||i.name),r=productTotals.get(key)||{product:text(i.name),quantity:0,sales:0};r.quantity+=num(i.qty);r.sales+=num(i.total);productTotals.set(key,r);const cat=catMap.get(String(i.productId))||"Uncategorized";categoryTotals.set(cat,(categoryTotals.get(cat)||0)+num(i.total));}}
 const cashTypes=["cash","bank","asset"],netCash=money((accounts as any[]).filter(a=>cashTypes.some(x=>text(a.type).toLowerCase().includes(x))).reduce((s,a)=>s+num(a.currentBalance),0));
 return{cards:{todaySales:todaySales.sales,todayProfit:todaySales.profit,todayPurchases:money(purchases._sum.total),todayExpenses:money(expenses._sum.amount),netCash,receivables:money(receivables._sum.balance),payables:money(payables._sum.balance),currentStockValue:valuation.summary.stockValue,lowStock:Number((lowRows as any[])[0]?.count||0),expiringProducts:expiring,overdueCustomers,supplierBillsDue:supplierDue,chequesDue},comparisons:{salesVsYesterday:comparison(todaySales.sales,yesterdaySales.sales),profitVsYesterday:comparison(todaySales.profit,yesterdaySales.profit),salesVsLastWeek:comparison(thisWeekSales.sales,priorWeekSales.sales),salesVsPreviousMonth:comparison(thisMonthSales.sales,priorMonthSales.sales)},charts:{salesTrend:[...trend.values()].map(r=>({...r,sales:money(r.sales),profit:money(r.profit)})),paymentMethods:[...payments].map(([name,value])=>({name,value:money(value)})),categories:[...categoryTotals].map(([name,value])=>({name,value:money(value)})).sort((a,b)=>b.value-a.value).slice(0,10),topProducts:[...productTotals.values()].sort((a,b)=>b.sales-a.sales).slice(0,10).map(r=>({...r,quantity:Math.round(r.quantity*1000)/1000,sales:money(r.sales)})),topCustomers:[...customerTotals].map(([name,value])=>({name,value:money(value)})).sort((a,b)=>b.value-a.value).slice(0,10)},meta:{timezone:"Asia/Qatar",generatedAt:new Date().toISOString(),chartDocumentCaps:{trend:10000,top:5000}}};
}

async function settingMap(businessId:string){const rows:any[]=await db.appSetting.findMany({where:{businessId,key:{startsWith:"grocery."}}});return new Map<string,any>(rows.map(r=>[String(r.key),r.value]));}
export async function grocerySettings(businessId:string){await assertGrocery(businessId);const [business,rows]=await Promise.all([db.business.findUnique({where:{id:businessId}}),db.appSetting.findMany({where:{businessId,key:{startsWith:"grocery."}},orderBy:{key:"asc"}})]);const values={...GROCERY_SETTING_DEFAULTS,...Object.fromEntries((rows as any[]).map(r=>[r.key,r.value]))};return{business:{name:business?.name,legalName:business?.legalName,taxId:business?.taxNumber,timezone:business?.timezone,currency:business?.currency,dateFormat:business?.dateFormat},values,groups:["business","pos","sales","purchases","inventory","accounting","printing","notifications"]};}
function validateSetting(key:string,value:any){if(!(key in GROCERY_SETTING_DEFAULTS)&&!key.startsWith("grocery.accounting.defaultAccount."))throw new Error(`Unsupported Grocery setting: ${key}`);if(key==="grocery.inventory.valuationMethod"&&value!=="weighted_average")throw new Error("This Grocery implementation uses Weighted Average valuation; changing methods after transactions is not allowed");if(key==="grocery.pos.receiptSize"&&!["58mm","80mm","A5","A4","Letter"].includes(text(value)))throw new Error("Unsupported receipt size");if(key.includes("Days")&&num(value)<0)throw new Error(`${key} cannot be negative`);return value;}
export async function saveGrocerySettings(req:Request,businessId:string,userId:string|null,input:any){await assertGrocery(businessId);const values=json(input.values||input),businessInput=json(input.business),saved:string[]=[];return db.$transaction(async(tx:any)=>{for(const [key,raw] of Object.entries(values)){const value=validateSetting(key,raw);await tx.appSetting.upsert({where:{businessId_key:{businessId,key}},create:{businessId,key,value},update:{value}});saved.push(key);}const patch:any={};if(businessInput.name!==undefined)patch.name=text(businessInput.name);if(businessInput.taxId!==undefined)patch.taxNumber=text(businessInput.taxId)||null;if(businessInput.timezone!==undefined)patch.timezone=text(businessInput.timezone)||"Asia/Qatar";if(businessInput.currency!==undefined)patch.currency=text(businessInput.currency).toUpperCase()||"QAR";if(businessInput.dateFormat!==undefined)patch.dateFormat=text(businessInput.dateFormat)||"yyyy-MM-dd";if(Object.keys(patch).length)await tx.business.update({where:{id:businessId},data:patch});await writeAudit(tx,req,{businessId,userId,action:"grocery.settings.save",entityType:"AppSetting",after:{keys:saved,business:Object.keys(patch)}});return{saved,business:patch};});}

export async function listNotificationRules(businessId:string){await assertGrocery(businessId);return db.notificationRule.findMany({where:{businessId},orderBy:{code:"asc"}});}
export async function saveNotificationRule(req:Request,businessId:string,userId:string|null,code:string,input:any){await assertGrocery(businessId);code=text(code);if(!code)throw new Error("Rule code is required");const row=await db.notificationRule.upsert({where:{businessId_code:{businessId,code}},create:{businessId,code,name:text(input.name)||code,eventType:text(input.eventType)||code,channels:["in_app"],schedule:input.schedule||null,conditions:json(input.conditions),template:json(input.template),quietHours:input.quietHours||null,active:input.active===undefined?true:bool(input.active),createdByUserId:userId,updatedByUserId:userId},update:{name:text(input.name)||code,eventType:text(input.eventType)||code,schedule:input.schedule||null,conditions:json(input.conditions),template:json(input.template),quietHours:input.quietHours||null,active:input.active===undefined?true:bool(input.active),updatedByUserId:userId}});await writeAudit(db,req,{businessId,userId,action:"grocery.notification_rule.save",entityType:"NotificationRule",entityId:row.id,after:row});return row;}
async function upsertNotice(tx:any,businessId:string,type:string,title:string,message:string,entityType:string,entityId:string){const existing=await tx.notification.findFirst({where:{businessId,type,entityType,entityId,readAt:null,title}});return existing||tx.notification.create({data:{businessId,type,title,message,entityType,entityId}});}
export async function generateOperationalNotifications(req:Request,businessId:string,userId:string|null){await assertGrocery(businessId);const s=await settingMap(businessId),now=new Date(),expiryDays=Math.max(0,num(s.get("grocery.notifications.expiryDays"),30)),customerDays=Math.max(0,num(s.get("grocery.notifications.customerDueDays"),7)),supplierDays=Math.max(0,num(s.get("grocery.notifications.supplierDueDays"),7)),chequeDays=Math.max(0,num(s.get("grocery.notifications.chequeReminderDays"),7)),largeDiscount=Math.max(0,num(s.get("grocery.notifications.largeDiscountAmount"),100)),largeRefund=Math.max(0,num(s.get("grocery.notifications.largeRefundAmount"),100));
 const [stockRows,batches,customerDue,supplierDue,cheques,pendingPo,transfers,counts,discounts,refunds]=await Promise.all([
  db.$queryRawUnsafe(`SELECT id,name,sku,current_stock AS "currentStock",min_stock AS "minStock" FROM products WHERE business_id=$1 AND deleted=false AND active=true AND current_stock<=min_stock ORDER BY current_stock ASC LIMIT 2000`,businessId),db.inventoryBatch.findMany({where:{businessId,qtyOnHandBase:{gt:0},expiryDate:{lte:new Date(now.getTime()+expiryDays*DAY)},status:{notIn:["depleted","quarantined"]}},include:{product:{select:{name:true,sku:true}}},orderBy:{expiryDate:"asc"},take:2000}),db.salesDocument.findMany({where:{businessId,documentType:"INVOICE",balance:{gt:0},dueDate:{lte:new Date(now.getTime()+customerDays*DAY)},status:{notIn:INVALID_SALES}},select:{id:true,documentNo:true,customerName:true,dueDate:true,balance:true},take:2000}),db.purchase.findMany({where:{businessId,balance:{gt:0},dueDate:{lte:new Date(now.getTime()+supplierDays*DAY)},status:{not:"CANCELLED"}},select:{id:true,purchaseNo:true,supplierName:true,dueDate:true,balance:true},take:2000}),db.industryRecord.findMany({where:{businessId,industryCode:"grocery",entityType:"grocery_cheque",dueAt:{lte:new Date(now.getTime()+chequeDays*DAY)},status:{notIn:["cleared","cancelled","replaced"]}},take:1000}),db.purchase.findMany({where:{businessId,status:"DRAFT"},select:{id:true,purchaseNo:true,supplierName:true},take:1000}),db.industryRecord.findMany({where:{businessId,industryCode:"grocery",entityType:"grocery_transfer",status:{in:["draft","approved","in_transit","partially_received"]}},take:1000}),db.stockCount.findMany({where:{businessId,status:{in:["draft","pending","submitted"]}},select:{id:true,countNo:true,status:true},take:1000}),db.salesDocument.findMany({where:{businessId,documentType:"INVOICE",discount:{gte:largeDiscount},createdAt:{gte:new Date(now.getTime()-DAY)},status:{notIn:INVALID_SALES}},select:{id:true,documentNo:true,discount:true},take:1000}),db.customerRefund.findMany({where:{businessId,amount:{gte:largeRefund},refundDate:{gte:new Date(now.getTime()-DAY)}},select:{id:true,refundNo:true,amount:true},take:1000}),
 ]);
 let attempted=0;await db.$transaction(async(tx:any)=>{for(const p of stockRows as any[]){const stock=num(p.currentStock),type=stock<=0?"out_of_stock":"low_stock";await upsertNotice(tx,businessId,type,stock<=0?"Out of Stock":"Low Stock",`${p.name} (${p.sku}) has ${stock} remaining.`,`Product`,String(p.id));attempted++;}for(const b of batches as any[]){const expired=b.expiryDate&&b.expiryDate<now;await upsertNotice(tx,businessId,expired?"expired_stock":"near_expiry",expired?"Expired Stock":"Near Expiry",`${b.product?.name||b.productId} batch ${b.batchNo} ${expired?"expired":"expires"} ${b.expiryDate?.toISOString().slice(0,10)}.`,`InventoryBatch`,b.id);attempted++;}for(const d of customerDue as any[]){const overdue=d.dueDate&&d.dueDate<now;await upsertNotice(tx,businessId,overdue?"customer_overdue":"customer_payment_due",overdue?"Customer Overdue":"Customer Payment Due",`${d.customerName} · ${d.documentNo} · balance ${money(d.balance)}.`,`SalesDocument`,d.id);attempted++;}for(const d of supplierDue as any[]){const overdue=d.dueDate&&d.dueDate<now;await upsertNotice(tx,businessId,overdue?"supplier_overdue":"supplier_payment_due",overdue?"Supplier Overdue":"Supplier Payment Due",`${d.supplierName} · ${d.purchaseNo} · balance ${money(d.balance)}.`,`Purchase`,d.id);attempted++;}for(const c of cheques as any[]){const direction=text(json(c.data).direction||json(c.data).type).toLowerCase(),out=direction.includes("out");await upsertNotice(tx,businessId,out?"outward_cheque_due":"inward_cheque_due",out?"Outward Cheque Due":"Inward Cheque Due",`${c.referenceNo||c.displayName} due ${c.dueAt?.toISOString().slice(0,10)}.`,`Cheque`,c.id);attempted++;}for(const p of pendingPo as any[]){await upsertNotice(tx,businessId,"pending_po","Pending Purchase Order",`${p.purchaseNo} · ${p.supplierName}.`,`Purchase`,p.id);attempted++;}for(const t of transfers as any[]){await upsertNotice(tx,businessId,"transfer_pending","Transfer Pending",`${t.referenceNo||t.displayName} · ${t.status}.`,`StockTransfer`,t.id);attempted++;}for(const c of counts as any[]){await upsertNotice(tx,businessId,"stock_count_pending","Stock Count Pending",`${c.countNo} · ${c.status}.`,`StockCount`,c.id);attempted++;}for(const d of discounts as any[]){await upsertNotice(tx,businessId,"large_discount","Large Discount",`${d.documentNo} discount ${money(d.discount)}.`,`SalesDocument`,d.id);attempted++;}for(const r of refunds as any[]){await upsertNotice(tx,businessId,"large_refund","Large Refund",`${r.refundNo} refund ${money(r.amount)}.`,`CustomerRefund`,r.id);attempted++;}await writeAudit(tx,req,{businessId,userId,action:"grocery.notifications.generate",entityType:"Notification",after:{attempted,caps:{stock:2000,expiry:2000,due:2000}}});});return{evaluatedAt:now.toISOString(),attempted};}
