(function(){
"use strict";
const PAGE=document.body.dataset.page||"dashboard";
const ROOT="/api/v1/manufacturing";
const NAV=[
["manufacturing-dashboard.html","Dashboard"],["manufacturing-materials.html","Materials"],["manufacturing-boms.html","Bills of Materials"],["manufacturing-work-orders.html","Work Orders"],["manufacturing-work-order-view.html","Work Order Detail"],["manufacturing-material-issues.html","Material Issue"],["manufacturing-material-returns.html","Material Return"],["manufacturing-wip.html","Work in Progress"],["manufacturing-stages.html","Production Stages"],["manufacturing-quality.html","Quality Checks"],["manufacturing-finished-goods.html","Finished Goods"],["manufacturing-scrap.html","Scrap & Yield"],["manufacturing-costing.html","Production Costing"],["manufacturing-capacity.html","Capacity Planning"],["manufacturing-reports.html","Reports"],["manufacturing-settings.html","Settings"]
];
const state={products:[],workOrders:[]};
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"})[c]);
const unwrap=v=>v&&Object.prototype.hasOwnProperty.call(v,"data")?v.data:v;
const dataOf=row=>row&&row.data&&typeof row.data==="object"&&!Array.isArray(row.data)?row.data:{};
const currentFile=()=>location.pathname.split("/").pop()||"manufacturing-dashboard.html";
function token(){return AxtorAPI.getToken();}
async function api(method,path,body,idempotent){
 const headers={Accept:"application/json",Authorization:"Bearer "+token()};
 if(body!==undefined)headers["Content-Type"]="application/json";
 if(idempotent)headers["Idempotency-Key"]="mfg:"+path+":"+Date.now()+":"+Math.random().toString(36).slice(2);
 const response=await fetch(AxtorAPI.getApiBaseUrl()+ROOT+path,{method,headers,body:body===undefined?undefined:JSON.stringify(body),cache:"no-store"});
 const payload=await response.json().catch(()=>null);
 if(response.status===401){AxtorAPI.goToLogin("session-expired",{clearToken:true});throw new Error("Session expired");}
 if(!response.ok)throw new Error(payload?.error?.message||"Manufacturing request failed");
 return unwrap(payload);
}
async function coreGet(path){return unwrap(await AxtorAPI.apiGet(path,{cache:false}));}
function badge(value){const s=String(value||"unknown").toLowerCase();const cls=/blocked|failed|rejected|expired|cancelled/.test(s)?" danger":/planned|pending|hold|warning|review/.test(s)?" warn":"";return '<span class="m-badge'+cls+'">'+esc(s.replaceAll("_"," "))+'</span>';}
function shell(title,subtitle){
 const links=NAV.map(([href,label])=>'<a class="'+(currentFile()===href?"active":"")+'" href="'+href+'">'+esc(label)+'</a>').join("");
 document.body.className="m-app";
 document.body.innerHTML='<div class="m-shell" id="mShell"><aside class="m-sidebar"><a class="m-brand" href="manufacturing-dashboard.html"><div class="m-mark">A</div><div><strong id="mBusiness">Axtor Manufacturing</strong><small>Production Management</small></div></a><nav class="m-nav">'+links+'</nav><div class="m-sidebar-footer">Tenant-scoped manufacturing records<br>Shared PostgreSQL backend</div></aside><div class="m-backdrop" id="mBackdrop"></div><main class="m-main"><header class="m-topbar"><button class="m-menu" id="mMenu" type="button">☰</button><div class="m-title"><h1>'+esc(title)+'</h1><p>'+esc(subtitle)+'</p></div><div class="m-user"><span id="mUser">User</span><div class="m-avatar" id="mAvatar">U</div><button class="m-btn m-btn-soft" id="mLogout" type="button">Logout</button></div></header><section class="m-page"><div id="mError"></div><div id="app"></div></section></main></div>';
 document.getElementById("mMenu").onclick=()=>document.getElementById("mShell").classList.toggle("open");
 document.getElementById("mBackdrop").onclick=()=>document.getElementById("mShell").classList.remove("open");
 document.getElementById("mLogout").onclick=async()=>{try{await AxtorAPI.apiPost("/api/v1/auth/logout",{});}catch(_){}AxtorAPI.goToLogin("logout",{clearToken:true});};
 try{const u=JSON.parse(localStorage.getItem("currentUser")||localStorage.getItem("axtorCurrentUser")||"{}");const b=JSON.parse(localStorage.getItem("axtorBusiness")||"{}");if(u.name){document.getElementById("mUser").textContent=u.name;document.getElementById("mAvatar").textContent=u.name.slice(0,1).toUpperCase();}if(b.name)document.getElementById("mBusiness").textContent=b.name;}catch(_){}
}
function hero(title,text){return '<section class="m-hero"><div class="m-eyebrow">Tenant manufacturing pack</div><h2>'+esc(title)+'</h2><p>'+esc(text)+'</p></section>';}
function panel(title,body,subtitle){return '<section class="m-card"><div class="m-section-head"><div><h3>'+esc(title)+'</h3>'+(subtitle?'<p>'+esc(subtitle)+'</p>':"")+'</div></div>'+body+'</section>';}
function field(f){const wide=f.wide?" wide":"";const req=f.required?" required":"";if(f.type==="textarea")return '<div class="m-field'+wide+'"><label>'+esc(f.label)+'</label><textarea name="'+esc(f.name)+'"'+req+' placeholder="'+esc(f.placeholder||"")+'"></textarea></div>';if(f.type==="select")return '<div class="m-field'+wide+'"><label>'+esc(f.label)+'</label><select name="'+esc(f.name)+'"'+req+'><option value="">Select</option>'+(f.options||[]).map(o=>'<option value="'+esc(typeof o==="object"?o.value:o)+'">'+esc(typeof o==="object"?o.label:o)+'</option>').join("")+'</select></div>';return '<div class="m-field'+wide+'"><label>'+esc(f.label)+'</label><input name="'+esc(f.name)+'" type="'+esc(f.type||"text")+'"'+req+' placeholder="'+esc(f.placeholder||"")+'"'+(f.step?' step="'+esc(f.step)+'"':"")+'></div>';}
function form(id,title,fields,button,subtitle){return panel(title,'<form id="'+id+'" class="m-form">'+fields.map(field).join("")+'<div class="m-actions"><button class="m-btn m-btn-primary" type="submit">'+esc(button||"Save")+'</button></div></form><div id="'+id+'Status" class="m-status"></div>',subtitle);}
function table(id,title,columns,subtitle){return panel(title,'<div class="m-toolbar"><input class="m-search" data-search="'+id+'" placeholder="Search records"></div><div class="m-table-wrap"><table class="m-table"><thead><tr>'+columns.map(c=>'<th>'+esc(c.label)+'</th>').join("")+'</tr></thead><tbody id="'+id+'"><tr><td colspan="'+columns.length+'">Loading…</td></tr></tbody></table></div>',subtitle);}
function value(row,path){return path.split(".").reduce((a,k)=>a==null?a:a[k],row);}
function shown(v){if(v===null||v===undefined||v==="")return "—";if(typeof v==="object")return JSON.stringify(v);if(/^\d{4}-\d{2}-\d{2}T/.test(String(v)))return new Date(v).toLocaleString();return String(v);}
function renderRows(id,rows,columns){const q=String(document.querySelector('[data-search="'+id+'"]')?.value||"").toLowerCase();const list=q?rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q)):rows;document.getElementById(id).innerHTML=list.map(row=>'<tr>'+columns.map(c=>'<td>'+(c.render?c.render(row):esc(shown(value(row,c.path))))+'</td>').join("")+'</tr>').join("")||'<tr><td colspan="'+columns.length+'" class="m-empty">No records found</td></tr>';const input=document.querySelector('[data-search="'+id+'"]');if(input&&!input.dataset.bound){input.dataset.bound="1";input.oninput=()=>renderRows(id,rows,columns);}}
function payload(formEl){const out=Object.fromEntries(new FormData(formEl).entries());for(const key of Object.keys(out)){if(out[key]==="")delete out[key];else if(["plannedQty","outputQuantity","revision","quantity","actualHours","completedQty","cost","plannedCost","availableHours","plannedHours","machineCount","shiftCount"].includes(key))out[key]=Number(out[key]);else if(out[key]==="true")out[key]=true;else if(out[key]==="false")out[key]=false;}return out;}
function parseJson(value,label){try{return JSON.parse(value);}catch(_){throw new Error(label+" must contain valid JSON");}}
function bind(id,method,pathFn,transform,reload,idempotent){const el=document.getElementById(id);if(!el)return;el.addEventListener("submit",async e=>{e.preventDefault();const status=document.getElementById(id+"Status");status.textContent="Saving…";status.className="m-status";try{let body=payload(e.currentTarget);if(transform)body=transform(body);const path=typeof pathFn==="function"?pathFn(body):pathFn;await api(method,path,body,idempotent);status.textContent="Saved successfully";status.className="m-status ok";e.currentTarget.reset();if(reload)await reload();}catch(err){status.textContent=err.message||"Save failed";status.className="m-status error";}});}
async function verifyTenant(){const registry=await coreGet("/api/v1/industry/registry");const code=String(registry?.selection?.code||registry?.selected?.code||"").toLowerCase();if(!["manufacturing","factory"].includes(code))throw new Error("This application is available only to Manufacturing tenants.");}
async function loadRefs(){const [products,orders]=await Promise.all([coreGet("/api/v1/products?limit=500").catch(()=>[]),api("GET","/work-orders").catch(()=>[])]);state.products=Array.isArray(products)?products:(products?.items||[]);state.workOrders=Array.isArray(orders)?orders:[];}
const productOptions=()=>state.products.map(p=>({value:p.id,label:(p.sku?"["+p.sku+"] ":"")+p.name}));
const orderOptions=()=>state.workOrders.map(o=>({value:o.id,label:(o.referenceNo||o.id)+" · "+(o.displayName||dataOf(o).productName||"Work order")}));
async function dashboard(){shell("Manufacturing Dashboard","Production orders, material flow, capacity, yield and cost control");const m=await api("GET","/dashboard");document.getElementById("app").innerHTML=hero("Factory Operations","Plan production, issue materials, record stages, quality results, finished goods and scrap without mixing Retail workflows.")+'<div class="m-kpis">'+[["Active work orders",m.activeWorkOrders],["Active BOMs",m.boms],["Planned quantity",m.plannedQty],["Finished quantity",m.completedQty],["Scrap quantity",m.scrapQty],["Yield",(m.yieldPct||0)+"%"],["Capacity hours",m.capacityHours]].map(x=>'<div class="m-card m-kpi"><span>'+esc(x[0])+'</span><strong>'+esc(x[1]||0)+'</strong></div>').join("")+'</div>'+panel("Production workflow",'<div class="m-flow">'+["BOM","Work Order","Material Issue","Production Stage","Quality Check","Finished Goods","Cost & Yield"].map(x=>'<div class="m-step">'+x+'</div>').join("")+'</div>');}
async function materials(){shell("Materials & Stock","Raw material, component and finished-goods availability");const rows=state.products;const columns=[{path:"sku",label:"SKU"},{path:"name",label:"Product"},{path:"unit",label:"Unit"},{path:"currentStock",label:"On hand"},{path:"reorderLevel",label:"Reorder"},{path:"costPrice",label:"Unit cost"},{path:"active",label:"Active",render:r=>badge(r.active?"active":"inactive")}];document.getElementById("app").innerHTML=hero("Material availability","Review shared inventory before releasing or issuing against a production order.")+table("rows","Material catalogue",columns);renderRows("rows",rows,columns);}
async function boms(){shell("Bills of Materials","Revision-controlled recipes and component requirements");const columns=[{path:"referenceNo",label:"BOM"},{path:"displayName",label:"Name"},{path:"data.productName",label:"Finished product"},{path:"data.revision",label:"Revision"},{path:"data.outputQuantity",label:"Output qty"},{path:"status",label:"Status",render:r=>badge(r.status)}];document.getElementById("app").innerHTML=hero("Bill of Materials","Define the finished item, output quantity and every required component.")+'<div class="m-grid">'+form("bomForm","Create BOM",[{name:"productId",label:"Finished product",type:"select",options:productOptions(),required:true},{name:"name",label:"BOM name",required:true},{name:"outputQuantity",label:"Output quantity",type:"number",step:"0.001",required:true},{name:"unit",label:"Output unit"},{name:"revision",label:"Revision",type:"number",required:true},{name:"componentsJson",label:"Components JSON",type:"textarea",wide:true,required:true,placeholder:'[{"productId":"...","quantity":2,"unit":"PCS"}]'},{name:"notes",label:"Engineering notes",type:"textarea",wide:true}],"Create BOM")+table("rows","BOM register",columns)+"</div>";let rows=[];const load=async()=>{rows=await api("GET","/boms");renderRows("rows",rows,columns);};bind("bomForm","POST","/boms",b=>{b.components=parseJson(b.componentsJson,"Components");delete b.componentsJson;return b;},load,true);await load();}
async function workOrders(){shell("Production Work Orders","Plan, release and monitor production demand");const columns=[{path:"referenceNo",label:"Work order"},{path:"displayName",label:"Description"},{path:"data.productName",label:"Product"},{path:"data.plannedQty",label:"Planned"},{path:"data.completedQty",label:"Completed"},{path:"data.scrapQty",label:"Scrap"},{path:"dueAt",label:"Due"},{path:"status",label:"Status",render:r=>badge(r.status)},{path:"id",label:"Open",render:r=>'<a class="m-btn m-btn-soft" href="manufacturing-work-order-view.html?id='+encodeURIComponent(r.id)+'">View</a>'}];document.getElementById("app").innerHTML=hero("Production orders","Create production demand against a finished product and optional approved BOM.")+'<div class="m-grid">'+form("woForm","Create Work Order",[{name:"productId",label:"Finished product",type:"select",options:productOptions(),required:true},{name:"bomId",label:"BOM ID"},{name:"name",label:"Description"},{name:"plannedQty",label:"Planned quantity",type:"number",step:"0.001",required:true},{name:"priority",label:"Priority",type:"select",options:["low","normal","high","urgent"]},{name:"warehouseId",label:"Warehouse ID"},{name:"assignedTeam",label:"Assigned team"},{name:"startAt",label:"Planned start",type:"datetime-local"},{name:"dueAt",label:"Due date",type:"datetime-local"},{name:"plannedCost",label:"Planned cost",type:"number",step:"0.01"},{name:"notes",label:"Production notes",type:"textarea",wide:true}],"Create Work Order")+table("rows","Work order register",columns)+"</div>";let rows=[];const load=async()=>{rows=await api("GET","/work-orders");state.workOrders=rows;renderRows("rows",rows,columns);};bind("woForm","POST","/work-orders",null,load,true);await load();}
async function workOrderView(){shell("Work Order Detail","Production history and status controls");const id=new URLSearchParams(location.search).get("id")||state.workOrders[0]?.id;if(!id){document.getElementById("app").innerHTML=panel("No work order selected",'<div class="m-empty">Open a work order from the Work Orders page.</div>');return;}const row=await api("GET","/work-orders/"+encodeURIComponent(id));document.getElementById("app").innerHTML=hero(row.referenceNo||"Work Order",row.displayName||dataOf(row).productName||"Production detail")+'<div class="m-grid">'+panel("Order summary",'<div class="m-report">'+esc(JSON.stringify(row,null,2))+'</div>')+form("statusForm","Update Status",[{name:"status",label:"Work order status",type:"select",options:["planned","released","in_progress","blocked","completed","cancelled"],required:true},{name:"notes",label:"Status notes",type:"textarea",wide:true}],"Update")+"</div>";bind("statusForm","PATCH","/work-orders/"+encodeURIComponent(id),null,async()=>location.reload(),false);}
function transactionPage(config){shell(config.title,config.subtitle);const fields=[{name:"workOrderId",label:"Work order",type:"select",options:orderOptions(),required:true},...config.fields];document.getElementById("app").innerHTML=hero(config.hero||config.title,config.description)+form("txForm",config.formTitle||config.title,fields,config.button);bind("txForm","POST",b=>{const id=b.workOrderId;delete b.workOrderId;return "/work-orders/"+encodeURIComponent(id)+config.path;},config.transform||null,null,true);}
async function materialIssues(){transactionPage({title:"Material Issue",subtitle:"Consume raw materials against a work order",hero:"Issue components to production",description:"Posting reduces shared inventory and records actual material cost against the selected work order.",button:"Post Material Issue",path:"/material-issues",fields:[{name:"itemsJson",label:"Issue items JSON",type:"textarea",wide:true,required:true,placeholder:'[{"productId":"...","quantity":5,"warehouseId":"..."}]'},{name:"notes",label:"Notes",type:"textarea",wide:true}],transform:b=>{b.items=parseJson(b.itemsJson,"Issue items");delete b.itemsJson;return b;}});}
async function materialReturns(){transactionPage({title:"Material Return",subtitle:"Return unused production material to stock",hero:"Return unused components",description:"Posting increases shared inventory and retains a tenant-scoped production trail.",button:"Post Material Return",path:"/material-returns",fields:[{name:"itemsJson",label:"Return items JSON",type:"textarea",wide:true,required:true,placeholder:'[{"productId":"...","quantity":1,"warehouseId":"..."}]'},{name:"notes",label:"Reason / notes",type:"textarea",wide:true}],transform:b=>{b.items=parseJson(b.itemsJson,"Return items");delete b.itemsJson;return b;}});}
async function stages(){transactionPage({title:"Production Stages",subtitle:"Record shop-floor progress and actual hours",hero:"Record work-in-progress events",description:"Capture stage, machine, operator, completed quantity, actual hours and stage cost.",button:"Post Stage Event",path:"/stages",fields:[{name:"stage",label:"Stage",required:true},{name:"status",label:"Stage status",type:"select",options:["planned","in_progress","completed","blocked","cancelled"],required:true},{name:"machine",label:"Machine / line"},{name:"operator",label:"Operator / team"},{name:"completedQty",label:"Completed quantity",type:"number",step:"0.001"},{name:"actualHours",label:"Actual hours",type:"number",step:"0.01"},{name:"actualCost",label:"Stage cost",type:"number",step:"0.01"},{name:"startedAt",label:"Started at",type:"datetime-local"},{name:"completedAt",label:"Completed at",type:"datetime-local"},{name:"notes",label:"Stage notes",type:"textarea",wide:true}]});}
async function finishedGoods(){transactionPage({title:"Finished Goods Receipt",subtitle:"Receive completed output into inventory",hero:"Receive production output",description:"Posting increases finished-goods stock and updates completed quantity and work-order status.",button:"Post Finished Goods",path:"/finished-goods",fields:[{name:"productId",label:"Finished product",type:"select",options:productOptions()},{name:"quantity",label:"Quantity",type:"number",step:"0.001",required:true},{name:"warehouseId",label:"Warehouse ID"},{name:"notes",label:"Receipt notes",type:"textarea",wide:true}]});}
async function scrap(){transactionPage({title:"Scrap & Yield",subtitle:"Record rejected or lost production output",hero:"Record production scrap",description:"Scrap is tied to the work order and included in production yield and variance reporting.",button:"Record Scrap",path:"/scrap",fields:[{name:"quantity",label:"Scrap quantity",type:"number",step:"0.001",required:true},{name:"reason",label:"Reason",required:true},{name:"disposition",label:"Disposition",type:"select",options:["discard","rework","recycle","return_to_supplier","quarantine"]},{name:"cost",label:"Scrap cost",type:"number",step:"0.01"},{name:"notes",label:"Notes",type:"textarea",wide:true}]});}
async function wip(){shell("Work in Progress","Active work orders and production-stage history");const rows=await api("GET","/work-in-progress");const columns=[{path:"referenceNo",label:"Work order"},{path:"displayName",label:"Description"},{path:"data.productName",label:"Product"},{path:"data.plannedQty",label:"Planned"},{path:"data.completedQty",label:"Completed"},{path:"stages",label:"Stages",render:r=>esc((r.stages||[]).length)},{path:"status",label:"Status",render:r=>badge(r.status)}];document.getElementById("app").innerHTML=hero("Live work in progress","Monitor released, in-progress and blocked production orders with their stage history.")+table("rows","WIP register",columns);renderRows("rows",rows,columns);}
async function quality(){shell("Quality Checkpoints","Inspection, acceptance, rework and rejection records");const columns=[{path:"referenceNo",label:"Check"},{path:"displayName",label:"Checkpoint"},{path:"data.workOrderReference",label:"Work order"},{path:"data.checkpoint",label:"Stage"},{path:"data.inspector",label:"Inspector"},{path:"data.checkedQty",label:"Checked"},{path:"data.acceptedQty",label:"Accepted"},{path:"data.rejectedQty",label:"Rejected"},{path:"status",label:"Result",render:r=>badge(r.status)}];document.getElementById("app").innerHTML=hero("Quality control","Record measurable checkpoints before finished goods are accepted into inventory.")+'<div class="m-grid">'+form("qualityForm","Record Quality Check",[{name:"workOrderId",label:"Work order",type:"select",options:orderOptions(),required:true},{name:"checkpoint",label:"Checkpoint / operation",required:true},{name:"inspector",label:"Inspector",required:true},{name:"checkedQty",label:"Checked quantity",type:"number",step:"0.001",required:true},{name:"acceptedQty",label:"Accepted quantity",type:"number",step:"0.001",required:true},{name:"rejectedQty",label:"Rejected quantity",type:"number",step:"0.001"},{name:"result",label:"Result",type:"select",options:["passed","conditional","failed","rework"],required:true},{name:"measurementsJson",label:"Measurements JSON",type:"textarea",wide:true,placeholder:'{"dimension":"10.02","tolerance":"±0.05"}'},{name:"notes",label:"Inspection notes",type:"textarea",wide:true}],"Save Quality Check")+table("rows","Quality register",columns)+"</div>";let rows=[];const load=async()=>{rows=await api("GET","/quality-checks");renderRows("rows",rows,columns);};bind("qualityForm","POST","/quality-checks",b=>{if(b.measurementsJson){b.measurements=parseJson(b.measurementsJson,"Measurements");delete b.measurementsJson;}return b;},load,true);await load();}
async function costing(){shell("Production Costing","Material, stage, scrap and variance visibility");const rows=await api("GET","/costs");const columns=[{path:"workOrderId",label:"Work order ID"},{path:"materialCost",label:"Material"},{path:"stageCost",label:"Labour / stage"},{path:"scrapCost",label:"Scrap"},{path:"finishedGoodsCost",label:"FG receipt value"},{path:"totalActualCost",label:"Actual cost"},{path:"plannedCost",label:"Planned cost"},{path:"variance",label:"Variance"}];document.getElementById("app").innerHTML=hero("Production cost variance","Compare planned order cost with posted material, stage and scrap cost.")+table("rows","Cost register",columns);renderRows("rows",rows,columns);}
async function capacity(){shell("Capacity Planning","Machines, lines, shifts and available production hours");const columns=[{path:"referenceNo",label:"Plan"},{path:"data.resource",label:"Resource"},{path:"data.period",label:"Period"},{path:"data.availableHours",label:"Available hours"},{path:"data.plannedHours",label:"Planned hours"},{path:"data.machineCount",label:"Machines"},{path:"data.shiftCount",label:"Shifts"},{path:"status",label:"Status",render:r=>badge(r.status)}];document.getElementById("app").innerHTML=hero("Capacity plan","Define available and planned capacity for a production line, machine group or work centre.")+'<div class="m-grid">'+form("capacityForm","Create Capacity Plan",[{name:"resource",label:"Resource / work centre",required:true},{name:"period",label:"Period",required:true,placeholder:"2026-W31"},{name:"availableHours",label:"Available hours",type:"number",step:"0.01",required:true},{name:"plannedHours",label:"Planned hours",type:"number",step:"0.01"},{name:"machineCount",label:"Machine count",type:"number"},{name:"shiftCount",label:"Shift count",type:"number"},{name:"startAt",label:"Period start",type:"datetime-local"},{name:"endAt",label:"Period end",type:"datetime-local"},{name:"notes",label:"Planning notes",type:"textarea",wide:true}],"Save Capacity Plan")+table("rows","Capacity register",columns)+"</div>";let rows=[];const load=async()=>{rows=await api("GET","/capacity");renderRows("rows",rows,columns);};bind("capacityForm","POST","/capacity",null,load,true);await load();}
async function reports(){shell("Manufacturing Reports","Production status, material flow, yield and capacity summaries");const report=await api("GET","/reports");document.getElementById("app").innerHTML=hero("Production reporting","Backend-calculated summaries remain tenant scoped and ready for later export/print enhancements.")+panel("Manufacturing report",'<div class="m-report">'+esc(JSON.stringify(report,null,2))+'</div>');}
async function settings(){shell("Manufacturing Settings","Defaults for production control and costing");const current=await api("GET","/settings");document.getElementById("app").innerHTML=hero("Factory controls","Configure defaults without changing shared Retail, Clinic, Pharmacy or other industry frontends.")+form("settingsForm","Production Defaults",[{name:"defaultWarehouseId",label:"Default warehouse ID"},{name:"defaultIssueMethod",label:"Issue method",type:"select",options:["manual","backflush","stage_based"]},{name:"requireApprovedBom",label:"Require approved BOM",type:"select",options:["true","false"]},{name:"requireQualityBeforeReceipt",label:"Require quality before finished-goods receipt",type:"select",options:["true","false"]},{name:"allowNegativeMaterialStock",label:"Allow negative material stock",type:"select",options:["false","true"]},{name:"costMethod",label:"Production cost method",type:"select",options:["standard","actual","weighted_average"]},{name:"defaultScrapDisposition",label:"Default scrap disposition",type:"select",options:["discard","rework","recycle","quarantine"]},{name:"notes",label:"Policy notes",type:"textarea",wide:true}],"Save Settings");const f=document.getElementById("settingsForm");for(const [k,v] of Object.entries(current||{})){if(f.elements[k])f.elements[k].value=String(v);}bind("settingsForm","PUT","/settings",null,null,false);}
const handlers={dashboard,materials,boms,"work-orders":workOrders,"work-order-view":workOrderView,"material-issues":materialIssues,"material-returns":materialReturns,wip,stages,quality,"finished-goods":finishedGoods,scrap,costing,capacity,reports,settings};
async function start(){if(!token()){AxtorAPI.goToLogin("authentication-required");return;}try{await verifyTenant();await loadRefs();const handler=handlers[PAGE];if(!handler)throw new Error("Unknown Manufacturing page: "+PAGE);await handler();}catch(error){if(!document.getElementById("app"))shell("Manufacturing","Dedicated production workspace");document.getElementById("mError").innerHTML='<div class="m-error">'+esc(error.message||"Manufacturing page failed to load")+'</div>';}}
document.addEventListener("DOMContentLoaded",start);
})();
