(function(){
"use strict";
const API="/api/v1/school";
const nav=[
 ["school-dashboard.html","Dashboard"],["school-admissions.html","Admissions"],["school-students.html","Students"],["school-guardians.html","Guardians"],["school-classes.html","Classes & Sections"],["school-enrollments.html","Enrollments"],["school-attendance.html","Attendance"],["school-timetable.html","Timetable"],["school-fees.html","Fees"],["school-fee-payments.html","Fee Payments"],["school-assessments.html","Assessments"],["school-results.html","Results"],["school-teachers.html","Teachers"],["school-employees.html","Employees"],["school-payroll.html","Payroll"],["school-reports.html","Reports"],["school-settings.html","Settings"]
];
const fields={
 admissions:[["applicationNo","Application number","text",1],["fullName","Applicant name","text",1],["requestedGrade","Requested grade","text",0],["guardianName","Guardian name","text",0],["guardianPhone","Guardian phone","text",0]],
 students:[["admissionNo","Admission number","text",1],["fullName","Student name","text",1],["dateOfBirth","Date of birth","date",0]],
 guardians:[["fullName","Guardian name","text",1],["phone","Phone","text",1],["email","Email","email",0],["relation","Relationship","text",0]],
 classes:[["academicYear","Academic year","text",1],["grade","Grade","text",1],["section","Section","text",1],["capacity","Capacity","number",1]],
 enrollments:[["studentId","Student ID","text",1],["classSectionId","Class section ID","text",1]],
 attendance:[["studentId","Student ID","text",1],["classSectionId","Class section ID","text",1],["attendanceDate","Attendance date","date",1],["status","Status","select",1,["present","absent","late","excused"]],["note","Note","text",0]],
 fees:[["studentId","Student ID","text",1],["feeHeadId","Fee head ID","text",1],["dueDate","Due date","date",1],["amount","Amount","number",1]],
 "fee-payments":[["studentFeeId","Student fee ID","text",1],["amount","Amount","number",1],["paymentMethod","Payment method","select",1,["cash","card","bank_transfer","cheque"]],["reference","Reference","text",0]],
 "academic-years":[["name","Academic year","text",1],["startsOn","Starts on","date",1],["endsOn","Ends on","date",1],["active","Set active","select",0,["true","false"]]],
 subjects:[["code","Subject code","text",1],["name","Subject name","text",1]],
 teachers:[["employeeNo","Employee number","text",0],["fullName","Teacher name","text",1],["phone","Phone","text",0],["email","Email","email",0]],
 rooms:[["code","Room code","text",1],["name","Room name","text",1],["capacity","Capacity","number",1]],
 timetable:[["classSectionId","Class section ID","text",1],["subjectId","Subject ID","text",1],["teacherId","Teacher ID","text",1],["roomId","Room ID","text",1],["weekday","Weekday 1-7","number",1],["startMinute","Start minute","number",1],["endMinute","End minute","number",1]],
 assessments:[["classSectionId","Class section ID","text",1],["subjectId","Subject ID","text",1],["termId","Term ID","text",0],["name","Assessment name","text",1],["maxMarks","Maximum marks","number",1],["assessmentDate","Assessment date","date",0]],
 results:[["assessmentId","Assessment ID","text",1],["studentId","Student ID","text",1],["marks","Marks","number",1],["grade","Grade","text",0],["remarks","Remarks","text",0]],
 employees:[["employeeNo","Employee number","text",1],["fullName","Employee name","text",1],["roleTitle","Role title","text",1],["monthlySalary","Monthly salary","number",1]],
 payroll:[["period","Payroll period","text",1],["paidAmount","Paid amount","number",0]],
 settings:[["eventKey","Event key","text",1],["channel","Channel","select",1,["in_app","email","sms","whatsapp"]],["daysBefore","Days before","number",0],["active","Active","select",0,["true","false"]]]
};
const pages={
 dashboard:{title:"School Operations Dashboard",subtitle:"Admissions, academics, attendance, fees and workforce control"},
 admissions:{title:"Admissions Pipeline",list:"/applicants",create:"/applicants",cols:[["applicationNo","Application"],["fullName","Applicant"],["requestedGrade","Grade"],["guardianName","Guardian"],["status","Status"]]},
 students:{title:"Student Register",list:"/students",create:"/students",cols:[["admissionNo","Admission"],["fullName","Student"],["dateOfBirth","DOB"],["status","Status"]]},
 guardians:{title:"Guardians",list:"/guardians",create:"/guardians",cols:[["fullName","Guardian"],["phone","Phone"],["email","Email"],["relation","Relation"]]},
 classes:{title:"Classes & Sections",list:"/classes",create:"/classes",cols:[["academicYear","Year"],["grade","Grade"],["section","Section"],["capacity","Capacity"]]},
 enrollments:{title:"Class Enrollments",list:"/enrollments",create:"/enrollments",cols:[["student.fullName","Student"],["classSection.grade","Grade"],["classSection.section","Section"],["status","Status"]]},
 attendance:{title:"Attendance Register",list:"/attendance",create:"/attendance",cols:[["attendanceDate","Date"],["student.fullName","Student"],["classSection.grade","Grade"],["status","Status"],["note","Note"]]},
 fees:{title:"Student Fees",list:"/fees",create:"/fees",cols:[["student.fullName","Student"],["feeHead.name","Fee Head"],["dueDate","Due"],["amount","Amount"],["paidAmount","Paid"],["status","Status"]]},
 "fee-payments":{title:"Fee Payments",list:"/fee-payments",create:"/fee-payments",idempotent:true,cols:[["paidAt","Paid At"],["studentFeeId","Fee ID"],["amount","Amount"],["paymentMethod","Method"],["reference","Reference"]]},
 "academic-years":{title:"Academic Years",list:"/academic-years",create:"/academic-years",cols:[["name","Academic Year"],["startsOn","Starts"],["endsOn","Ends"],["active","Active"]]},
 subjects:{title:"Subjects",list:"/subjects",create:"/subjects",cols:[["code","Code"],["name","Subject"],["active","Active"]]},
 teachers:{title:"Teachers",list:"/teachers",create:"/teachers",cols:[["employeeNo","Employee No"],["fullName","Teacher"],["phone","Phone"],["email","Email"]]},
 rooms:{title:"Rooms",list:"/rooms",create:"/rooms",cols:[["code","Code"],["name","Room"],["capacity","Capacity"]]},
 timetable:{title:"Timetable",list:"/timetable",create:"/timetable",cols:[["weekday","Day"],["startMinute","Start"],["endMinute","End"],["classSectionId","Class"],["teacherId","Teacher"],["roomId","Room"]]},
 assessments:{title:"Assessments",list:"/assessments",create:"/assessments",cols:[["name","Assessment"],["assessmentDate","Date"],["classSectionId","Class"],["subjectId","Subject"],["maxMarks","Max Marks"],["status","Status"]]},
 results:{title:"Results",list:"/results",create:"/results",cols:[["assessmentId","Assessment"],["studentId","Student"],["marks","Marks"],["grade","Grade"],["publishedAt","Published"]]},
 employees:{title:"Employees",list:"/employees",create:"/employees",cols:[["employeeNo","Employee No"],["fullName","Employee"],["roleTitle","Role"],["monthlySalary","Monthly Salary"]]},
 payroll:{title:"Payroll Runs",list:"/payroll-runs",create:"/payroll-runs",idempotent:true,cols:[["period","Period"],["grossAmount","Gross"],["paidAmount","Paid"],["status","Status"],["postedAt","Posted"]]},
 reports:{title:"School Reports",subtitle:"Date-filtered fee collection, payroll and operational summaries"},
 settings:{title:"School Notification Settings",list:"/notification-rules",create:"/notification-rules",put:true,cols:[["eventKey","Event"],["channel","Channel"],["daysBefore","Days Before"],["active","Active"]]},
 "student-profile":{title:"Student Profile",subtitle:"Longitudinal enrollment, guardian, attendance, fee and result history"}
};
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function data(v){return v&&Object.prototype.hasOwnProperty.call(v,"data")?v.data:v;}
function value(row,path){return path.split(".").reduce((x,k)=>x==null?x:x[k],row);}
function shown(v){if(v===null||v===undefined||v==="")return "—";if(typeof v==="boolean")return v?"Yes":"No";if(/^\d{4}-\d{2}-\d{2}T/.test(String(v)))return new Date(v).toLocaleString();if(/^\d{4}-\d{2}-\d{2}$/.test(String(v)))return new Date(v+"T00:00:00").toLocaleDateString();return String(v);}
function current(){return document.body.dataset.page||"dashboard";}
function shell(page){const p=pages[page]||pages.dashboard;document.body.innerHTML=`<div class="school-shell"><aside class="school-nav"><div class="school-brand">AXTOR · SCHOOL</div>${nav.map(n=>`<a href="${n[0]}" class="${n[0].startsWith("school-"+page) ? "active":""}">${n[1]}</a>`).join("")}<a href="school-academic-years.html">Academic Years</a><a href="school-subjects.html">Subjects</a><a href="school-rooms.html">Rooms</a></aside><main class="school-main"><section class="school-hero"><h1>${esc(p.title)}</h1><p>${esc(p.subtitle||"Purpose-built school administration workspace")}</p></section><div id="app"></div></main></div>`;}
async function guard(){const r=data(await AxtorAPI.apiGet("/api/v1/industry/registry",{cache:false}))||{};const code=String(r.selection?.code||r.selected?.code||"").toLowerCase();if(!["school","education"].includes(code))throw new Error("This application is available only to School tenants.");return r;}
function form(page){const defs=fields[page]||[];if(!defs.length)return "";return `<section class="school-panel"><h2>New ${esc((pages[page]?.title||page).replace(/s$/,""))}</h2><form id="schoolForm" class="school-form">${defs.map(f=>`<div><label>${esc(f[1])}</label>${f[2]==="select"?`<select name="${f[0]}" ${f[3]?"required":""}><option value="">Select</option>${(f[4]||[]).map(o=>`<option value="${esc(o)}">${esc(o)}</option>`).join("")}</select>`:`<input name="${f[0]}" type="${f[2]}" ${f[3]?"required":""}></div>`).join("")}<div class="school-actions"><button class="school-btn">Save</button></div></form><div id="status" class="school-status"></div></section>`;}
function table(page){const p=pages[page],cols=p.cols||[];return `<section class="school-panel"><div class="school-toolbar"><h2>Records</h2><input id="search" class="school-search" placeholder="Search or filter displayed records"></div><div class="school-table-wrap"><table class="school-table"><thead><tr>${cols.map(c=>`<th>${esc(c[1])}</th>`).join("")}</tr></thead><tbody id="rows"><tr><td colspan="${cols.length}">Loading…</td></tr></tbody></table></div></section>`;}
function normalize(body){Object.keys(body).forEach(k=>{if(body[k]==="true")body[k]=true;else if(body[k]==="false")body[k]=false;else if(body[k]!==""&&["amount","paidAmount","monthlySalary","capacity","weekday","startMinute","endMinute","marks","maxMarks","daysBefore"].includes(k))body[k]=Number(body[k]);});return body;}
async function list(page){const p=pages[page];const rows=data(await AxtorAPI.apiGet(API+p.list,{cache:false}))||[];const q=String(document.getElementById("search")?.value||"").toLowerCase();const filtered=q?rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q)):rows;const body=document.getElementById("rows");body.innerHTML=filtered.map(r=>`<tr>${p.cols.map(c=>`<td>${esc(shown(value(r,c[0])))}</td>`).join("")}</tr>`).join("")||`<tr><td class="school-empty" colspan="${p.cols.length}">No records found.</td></tr>`;}
async function submit(page,event){event.preventDefault();const p=pages[page],fd=new FormData(event.currentTarget),body=normalize(Object.fromEntries(fd.entries()));const status=document.getElementById("status");status.textContent="Saving…";status.className="school-status";try{const options=p.idempotent?{headers:{"Idempotency-Key":"school:"+page+":"+Date.now()+":"+Math.random().toString(36).slice(2)}}:undefined;if(p.put)await AxtorAPI.apiPut(API+p.create,body,options);else await AxtorAPI.apiPost(API+p.create,body,options);status.textContent="Saved successfully.";status.className="school-status ok";event.currentTarget.reset();await list(page);}catch(e){status.textContent=e.message||"Save failed";status.className="school-status error";}}
async function dashboard(){const [d,fees,attendance]=await Promise.all([AxtorAPI.apiGet(API+"/dashboard",{cache:false}),AxtorAPI.apiGet(API+"/fees?limit=500",{cache:false}),AxtorAPI.apiGet(API+"/attendance?limit=500",{cache:false})]);const k=data(d)||{},f=data(fees)||[],a=data(attendance)||[];const outstanding=f.reduce((s,x)=>s+Math.max(0,Number(x.amount||0)-Number(x.paidAmount||0)),0);document.getElementById("app").innerHTML=`<div class="school-kpis"><div class="school-kpi"><span>Active Students</span><strong>${esc(k.activeStudents||0)}</strong></div><div class="school-kpi"><span>Active Classes</span><strong>${esc(k.activeClasses||0)}</strong></div><div class="school-kpi"><span>Current Enrollments</span><strong>${esc(k.activeEnrollments||0)}</strong></div><div class="school-kpi"><span>Outstanding Fees</span><strong>${esc(outstanding.toFixed(2))}</strong></div></div><section class="school-panel"><h2>Academic Operations</h2><p>Attendance records loaded: <strong>${a.length}</strong></p><div class="school-note">Use the dedicated modules for admissions, attendance, fees, timetable, assessments and payroll. All records are isolated by tenant.</div></section>`;}
async function reports(){const today=new Date(),from=new Date(today.getTime()-30*86400000).toISOString().slice(0,10),to=today.toISOString().slice(0,10);document.getElementById("app").innerHTML=`<section class="school-panel"><form id="reportForm" class="school-form"><div><label>From</label><input name="from" type="date" value="${from}"></div><div><label>To</label><input name="to" type="date" value="${to}"></div><div class="school-actions"><button class="school-btn">Run Report</button></div></form><pre id="reportOutput" class="mt-3"></pre></section>`;const run=async e=>{if(e)e.preventDefault();const q=new URLSearchParams(new FormData(document.getElementById("reportForm")));document.getElementById("reportOutput").textContent=JSON.stringify(data(await AxtorAPI.apiGet(API+"/reports/filtered?"+q.toString(),{cache:false})),null,2);};document.getElementById("reportForm").addEventListener("submit",run);await run();}
async function profile(){const id=new URLSearchParams(location.search).get("id");if(!id)throw new Error("Student id is required");const r=data(await AxtorAPI.apiGet(API+"/students/"+encodeURIComponent(id)+"/summary",{cache:false}));document.getElementById("app").innerHTML=`<section class="school-panel"><h2>${esc(r.student.fullName)}</h2><p>Admission: ${esc(r.student.admissionNo)}</p><pre>${esc(JSON.stringify(r,null,2))}</pre></section>`;}
async function boot(){const page=current();shell(page);try{await guard();if(page==="dashboard")return dashboard();if(page==="reports")return reports();if(page==="student-profile")return profile();const p=pages[page];document.getElementById("app").innerHTML=form(page)+table(page);document.getElementById("schoolForm")?.addEventListener("submit",e=>submit(page,e));document.getElementById("search")?.addEventListener("input",()=>list(page));await list(page);}catch(e){document.getElementById("app").innerHTML=`<section class="school-panel"><div class="school-status error">${esc(e.message||"Unable to load School application")}</div></section>`;}}
document.addEventListener("DOMContentLoaded",boot);
})();
