(function(){"use strict";
  const form=document.querySelector('#onboardingForm'); if(!form||!window.AxtorAPI)return;
  const steps=[1,6,11,15,18], sections=[...document.querySelectorAll('.setup-step')]; let current=1,catalog=null,record=null;
  const $=selector=>document.querySelector(selector); const unwrap=value=>value&&Object.prototype.hasOwnProperty.call(value,'data')?value.data:value;
  function message(text,type='danger'){const el=$('#setupMessage');el.className=`alert alert-${type} mt-3`;el.textContent=text;el.classList.remove('d-none');el.scrollIntoView({behavior:'smooth',block:'nearest'});} function clearMessage(){$('#setupMessage').classList.add('d-none')}
  function values(){const data=new FormData(form),additional=[...$('#additionalCurrencies').selectedOptions].map(x=>x.value);return{businessName:String(data.get('businessName')||'').trim(),logoUrl:String(data.get('logoUrl')||'').trim(),industryCode:data.get('industryCode'),country:data.get('country'),timezone:data.get('timezone'),baseCurrency:data.get('baseCurrency'),additionalCurrencies:additional,language:data.get('language'),dateFormat:data.get('dateFormat'),numberLocale:String(data.get('numberLocale')||'').trim(),tax:{system:data.get('taxSystem'),label:String(data.get('taxLabel')||'Tax').trim(),registrationNumber:String(data.get('taxRegistrationNumber')||'').trim(),pricesIncludeTax:data.get('pricesIncludeTax')==='on'},branchName:String(data.get('branchName')||'').trim(),warehouseName:String(data.get('warehouseName')||'').trim(),invoicePrefix:String(data.get('invoicePrefix')||'INV').trim(),quotationPrefix:String(data.get('quotationPrefix')||'QUO').trim(),deliveryPrefix:String(data.get('deliveryPrefix')||'DN').trim(),invoiceTemplate:data.get('invoiceTemplate'),sampleDataRequested:data.get('dataMode')==='sample',planCode:data.get('planCode')||'basic',billingCycle:data.get('billingCycle')||'MONTHLY'};}
  function fill(answers){if(!answers)return;Object.entries(answers).forEach(([key,value])=>{if(key==='additionalCurrencies'&&Array.isArray(value)){[...$('#additionalCurrencies').options].forEach(o=>o.selected=value.includes(o.value));return}if(key==='tax'&&value){form.taxSystem.value=value.system||'none';form.taxLabel.value=value.label||'Tax';form.taxRegistrationNumber.value=value.registrationNumber||'';form.pricesIncludeTax.checked=Boolean(value.pricesIncludeTax);return}if(key==='sampleDataRequested'){form.dataMode.value=value?'sample':'empty';return}const field=form.elements.namedItem(key);if(field&&typeof value!=='object')field.value=value??'';});}
  function options(select,rows,value='code',label='name'){select.innerHTML=rows.map(row=>`<option value="${String(row[value]).replace(/"/g,'&quot;')}">${row[value]} — ${row[label]}</option>`).join('')}
  function plans(){const root=$('#planChoices');root.innerHTML=catalog.plans.map(plan=>`<div class="col-md-6 col-xl-3"><label class="choice-card d-block ${plan.code==='professional'?'border-success':''}"><input class="form-check-input me-2" type="radio" name="planCode" value="${plan.code}" ${plan.code==='basic'?'checked':''}><strong>${plan.name}</strong>${plan.isRecommended?'<span class="badge bg-success ms-1">Best Value</span>':''}<div class="small text-muted mt-2">${plan.maxUsers??'Custom'} users · ${plan.maxBranches??'Custom'} branches · ${plan.maxWarehouses??'Custom'} warehouses</div><div class="small mt-2">${plan.supportLevel} support</div></label></div>`).join('');root.addEventListener('change',()=>{root.querySelectorAll('.choice-card').forEach(card=>card.classList.toggle('selected',card.querySelector('input').checked));review()});}
  function review(){const v=values();const industry=catalog?.industries.find(x=>x.code===v.industryCode)?.name||v.industryCode;const plan=catalog?.plans.find(x=>x.code===v.planCode)?.name||v.planCode;$('#reviewGrid').innerHTML=[['Business',v.businessName||'—'],['Industry',industry||'—'],['Country / Time zone',`${v.country||'—'} · ${v.timezone||'—'}`],['Currency',`${v.baseCurrency||'—'}${v.additionalCurrencies.length?' + '+v.additionalCurrencies.join(', '):''}`],['Language',v.language||'—'],['Tax',v.tax.system==='none'?'No tax':`${v.tax.label} · ${v.tax.system}`],['Operations',`${v.branchName||'—'} · ${v.warehouseName||'—'}`],['Opening data',v.sampleDataRequested?'Labelled sample data':'Empty business'],['Plan',`${plan} · ${v.billingCycle}`]].map(([a,b])=>`<div class="review-item"><small class="text-muted">${a}</small><div class="fw-bold">${b}</div></div>`).join('')}
  function show(index){current=Math.min(5,Math.max(1,index));sections.forEach((section,i)=>section.classList.toggle('active',i===current-1));$('#stepLabel').textContent=`Section ${current} of 5`;$('#setupProgress').style.width=`${current*20}%`;$('#backBtn').disabled=current===1;$('#nextBtn').classList.toggle('d-none',current===5);$('#completeBtn').classList.toggle('d-none',current!==5);if(current===5)review();scrollTo({top:0,behavior:'smooth'})}
  function validCurrent(){const invalid=[...sections[current-1].querySelectorAll('[required]')].find(field=>!field.checkValidity());if(invalid){invalid.reportValidity();return false}return true}
  async function save(silent=false){clearMessage();const button=$('#saveBtn');button.disabled=true;$('#saveState').textContent='Saving…';try{const completed=Array.from({length:steps[current-1]-1},(_,i)=>i+1);record=unwrap(await AxtorAPI.apiPut('/api/v1/commercial/onboarding',{currentStep:steps[current-1],completedSteps:completed,answers:values(),sampleDataRequested:values().sampleDataRequested}));$('#saveState').textContent='Saved to cloud';if(!silent)message('Progress saved securely.','success');return true}catch(error){$('#saveState').textContent='Save failed';message(error.message||'Unable to save progress');return false}finally{button.disabled=false}}
  $('#backBtn').addEventListener('click',()=>show(current-1));$('#nextBtn').addEventListener('click',async()=>{if(!validCurrent())return;if(await save(true))show(current+1)});$('#saveBtn').addEventListener('click',()=>save(false));
  form.addEventListener('submit',async event=>{event.preventDefault();if(!form.checkValidity()){form.reportValidity();return}const button=$('#completeBtn');button.disabled=true;button.textContent='Completing…';try{await AxtorAPI.apiPost('/api/v1/commercial/onboarding/complete',{answers:values()});message('Setup complete. Opening your dashboard…','success');setTimeout(()=>location.href='index.html',900)}catch(error){message(error.message||'Setup could not be completed')}finally{button.disabled=false;button.innerHTML='<i class="bi bi-check2-circle"></i> Complete Setup'}});
  (async()=>{try{const [cat,ctx]=await Promise.all([AxtorAPI.apiGet('/api/v1/commercial/catalog'),AxtorAPI.apiGet('/api/v1/commercial/context')]);catalog=unwrap(cat);const context=unwrap(ctx);record=context.onboarding;options($('#industrySelect'),catalog.industries);options($('#baseCurrency'),catalog.currencies);options($('#additionalCurrencies'),catalog.currencies);$('#languageSelect').innerHTML=catalog.languages.map(x=>`<option value="${x.code}">${x.name}</option>`).join('');plans();fill(record?.answers);if(context.user)$('#adminDisplay').value=`${context.user.name} · ${context.user.email}`;if(record?.state==='COMPLETED')message('This business setup is complete. You can review and update the configuration.','success');const savedStep=Number(record?.currentStep||1);show(savedStep>=18?5:savedStep>=15?4:savedStep>=11?3:savedStep>=6?2:1);$('#saveState').textContent=record?'Cloud progress loaded':'Ready'}catch(error){message(error.message||'Unable to load setup catalog');$('#saveState').textContent='Unavailable'}})();
})();
