(function(){
"use strict";
const PAGE=document.body.dataset.page||"dashboard",ROOT="/api/v1/workshop";
const NAV=[["workshop-dashboard.html","Dashboard"],["workshop-vehicles.html","Vehicles"],["workshop-inspections.html","Inspections"],["workshop-estimates.html","Estimates"],["workshop-jobs.html","Job Cards"],["workshop-parts.html","Parts"],["workshop-quality.html","Quality Check"],["workshop-invoices.html","Invoices"],["workshop-payments.html","Payments"],["workshop-reminders.html","Service Reminders"],["workshop-delivery.html","Vehicle Delivery"],["workshop-reports.html","Reports"],["workshop-settings.html","Settings"]];
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function unwrap(v){return v&&Object.prototype.hasOwnProperty.call(v,"data")?v.data:v;}
async function request(method,path,body,idempotent){const headers={Accept:"application/json",Authorization:"Bearer "+AxtorAPI.getToken()};if(body!==undefined)headers["Content-Type"]="application/json";if(idempotent)headers["Idempotency-Key"]="workshop:"+path+":"+Date.now()+":"+Math.random().toString(36).slice(2);const response=await fetch(AxtorAPI.getApiBaseUrl()+ROOT+path,{method,headers,body:body===undefined?undefined:JSON.stringify(body),cache:"no-store"});const payload=await response.json().catch(()=>null);if(response.status===401){AxtorAPI.goToLogin("session-expired",{clearToken:true});throw new Error("Session expired.");}if(!response.ok)throw new Error(payload?.error?.message||"Workshop request failed");return unwrap(payload);}
function shell(title,subtitle){const current=location.pathname.split("/").pop();const links=NAV.map(x=>'<a class="'+(x[0]===current?"active":"")+'" href="'+x[0]+'">'+esc(x[1])+"</a>").join("");document.body.innerHTML='<div class="w-shell"><aside class="w-nav"><div class="w-brand">AXTOR · WORKSHOP</div>'+links+'</aside><main class="w-main"><section class="w-hero"><h1>'+esc(title)+"</h1><p>"+esc(subtitle)+'</p></section><div id="app"></div></main></div>';}
async function guard(){const r=unwrap(await AxtorAPI.apiGet("/api/v1/industry/registry",{cache:false}))||{};const code=String(r.selection?.code||r.selected?.code||"").toLowerCase();if(!["workshop","garage"].includes(code))throw new Error("This application is available only to Workshop tenants.");}
function fieldHtml(f){const req=f.required?" required":"";if(f.type==="select")return '<div><label>'+esc(f.label)+'</label><select name="'+f.name+'"'+req+'><option value="">Select</option>'+f.options.map(o=>'<option value="'+esc(o)+'">'+esc(o)+"</option>").join("")+"</select></div>";if(f.type==="textarea")return '<div><label>'+esc(f.label)+'</label><textarea name="'+f.name+'"'+req+'></textarea></div>';return '<div><label>'+esc(f.label)+'</label><input name="'+f.name+'" type="'+f.type+'"'+req+'></div>';}
function formPanel(id,title,fields,button){return '<section class="w-panel"><h2>'+esc(title)+'</h2><form id="'+id+'" class="w-form">'+fields.map(fieldHtml).join("")+'<div class="w-actions"><button class="w-btn" type="submit">'+esc(button||"Save")+'</button></div></form><div id="'+id+'Status" class="w-status"></div></section>';}
function tablePanel(id,title,columns){return '<section class="w-panel"><div class="w-toolbar"><h2>'+esc(title)+'</h2><input class="w-search" data-search="'+id+'" placeholder="Search records"></div><div class="w-table-wrap"><table class="w-table"><thead><tr>'+columns.map(c=>"<th>"+esc(c[1])+"</th>").join("")+'</tr></thead><tbody id="'+id+'"></tbody></table></div></section>';}
function nested(row,path){return path.split(".").reduce((x,k)=>x==null?x:x[k],row);}function shown(v){if(v===null||v===undefined||v==="")return"—";const t=String(v);return /^\d{4}-\d{2}-\d{2}T/.test(t)?new Date(t).toLocaleString():t;}
function renderRows(id,rows,columns){const q=String(document.querySelector('[data-search="'+id+'"]')?.value||"").toLowerCase();const filtered=q?rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q)):rows;document.getElementById(id).innerHTML=filtered.map(r=>"<tr>"+columns.map(c=>"<td>"+esc(shown(nested(r,c[0])))+"</td>").join("")+"</tr>").join("")||'<tr><td colspan="'+columns.length+'">No records found.</td></tr>';}
function body(form){const v=Object.fromEntries(new FormData(form).entries());const nums=new Set(["modelYear","mileage","tax","quantity","total","amount","dueMileage","daysBefore"]);Object.keys(v).forEach(k=>{if(v[k]==="true")v[k]=true;else if(v[k]==="false")v[k]=false;else if(nums.has(k)&&v[k]!=="")v[k]=Number(v[k]);});return v;}
function bind(id,method,pathBuilder,transform,reload,idempotent){document.getElementById(id).addEventListener("submit",async e=>{e.preventDefault();const status=document.getElementById(id+"Status");status.textContent="Saving…";status.className="w-status";try{let value=body(e.currentTarget);if(transform)value=transform(value);const path=typeof pathBuilder==="function"?pathBuilder(value):pathBuilder;await request(method,path,value,idempotent);status.textContent="Saved successfully.";status.className="w-status ok";e.currentTarget.reset();if(reload)await reload();}catch(error){status.textContent=error.message||"Save failed";status.className="w-status error";}});}
async function dashboard(){shell("Workshop Dashboard","Vehicles, estimates, bays, jobs and quality control");const m=await request("GET","/dashboard");document.getElementById("app").innerHTML='<div class="w-kpis"><div class="w-kpi"><span>Vehicles</span><strong>'+esc(m.vehicles||0)+'</strong></div><div class="w-kpi"><span>Open Jobs</span><strong>'+esc(m.openJobs||0)+'</strong></div><div class="w-kpi"><span>Awaiting Approval</span><strong>'+esc(m.awaitingApproval||0)+'</strong></div><div class="w-kpi"><span>Service Bays</span><strong>'+esc(m.serviceBays||0)+'</strong></div></div><section class="w-panel"><h2>Workshop Workflow</h2><div class="w-flow"><div class="w-step">Vehicle</div><div class="w-step">Inspection</div><div class="w-step">Estimate</div><div class="w-step">Job & Parts</div><div class="w-step">Quality</div><div class="w-step">Invoice & Delivery</div></div></section>';}
async function vehicles(){shell("Vehicle Register","Customer vehicles, VIN, mileage and history foundation");const cols=[["registrationNo","Registration"],["make","Make"],["model","Model"],["modelYear","Year"],["mileage","Mileage"],["customerId","Customer"]];document.getElementById("app").innerHTML=formPanel("vehicleForm","Add Vehicle",[{name:"customerId",label:"Customer ID",type:"text",required:true},{name:"registrationNo",label:"Registration number",type:"text",required:true},{name:"vin",label:"VIN",type:"text"},{name:"make",label:"Make",type:"text",required:true},{name:"model",label:"Model",type:"text",required:true},{name:"modelYear",label:"Model year",type:"number"},{name:"mileage",label:"Mileage",type:"number"}])+tablePanel("vehicleRows","Vehicles",cols);let rows=[];const load=async()=>{rows=await request("GET","/vehicles");renderRows("vehicleRows",rows,cols);};bind("vehicleForm","POST","/vehicles",null,load,false);await load();}
async function jobs(){shell("Job Cards","Technician, service-bay and promised-time control");const cols=[["jobNo","Job"],["vehicleId","Vehicle"],["technicianId","Technician"],["bayId","Bay"],["priority","Priority"],["promisedAt","Promised"],["status","Status"]];document.getElementById("app").innerHTML=formPanel("jobForm","Create Job Card",[{name:"vehicleId",label:"Vehicle ID",type:"text",required:true},{name:"estimateId",label:"Estimate ID",type:"text"},{name:"technicianId",label:"Technician ID",type:"text"},{name:"bayId",label:"Service bay ID",type:"text"},{name:"priority",label:"Priority",type:"select",options:["low","normal","high","urgent"]},{name:"promisedAt",label:"Promised at",type:"datetime-local"}])+tablePanel("jobRows","Job Queue",cols);let rows=[];const load=async()=>{rows=await request("GET","/jobs");renderRows("jobRows",rows,cols);};bind("jobForm","POST","/jobs",null,load,true);await load();}
const ACTIONS={
 inspections:{title:"Vehicle Inspections",subtitle:"Condition checklist before estimate and repair",id:"inspectionForm",button:"Save Inspection",fields:[{name:"vehicleId",label:"Vehicle ID",type:"text",required:true},{name:"mileage",label:"Mileage",type:"number"},{name:"fuelLevel",label:"Fuel level",type:"text"},{name:"notes",label:"Notes",type:"textarea"},{name:"itemsJson",label:"Inspection items JSON",type:"textarea"}],method:"POST",path:"/inspections",transform:b=>{if(b.itemsJson){try{b.items=JSON.parse(b.itemsJson);}catch{throw Error("Inspection items JSON is invalid");}}delete b.itemsJson;return b;}},
 estimates:{title:"Repair Estimates",subtitle:"Labour and parts estimate awaiting customer approval",id:"estimateForm",button:"Create Estimate",fields:[{name:"vehicleId",label:"Vehicle ID",type:"text",required:true},{name:"tax",label:"Tax",type:"number"},{name:"itemsJson",label:"Estimate items JSON",type:"textarea",required:true}],method:"POST",path:"/estimates",idempotent:true,transform:b=>{try{b.items=JSON.parse(b.itemsJson);}catch{throw Error("Estimate items JSON is invalid");}delete b.itemsJson;return b;}},
 quality:{title:"Quality Check",subtitle:"Pass, fail or return completed work for rework",id:"qualityForm",button:"Record Quality",fields:[{name:"jobId",label:"Job card ID",type:"text",required:true},{name:"result",label:"Result",type:"select",required:true,options:["passed","failed","rework"]},{name:"checklist",label:"Checklist",type:"textarea"},{name:"notes",label:"Notes",type:"textarea"},{name:"checkedBy",label:"Checked by",type:"text"}],method:"POST",path:b=>{const id=b.jobId;delete b.jobId;return "/jobs/"+encodeURIComponent(id)+"/quality-checks";}},
 invoices:{title:"Workshop Invoices",subtitle:"Create invoice after labour and parts posting",id:"invoiceForm",button:"Create Invoice",fields:[{name:"jobId",label:"Job card ID",type:"text",required:true},{name:"total",label:"Invoice total override",type:"number"}],method:"POST",idempotent:true,path:b=>{const id=b.jobId;delete b.jobId;return "/jobs/"+encodeURIComponent(id)+"/invoices";}},
 payments:{title:"Invoice Payments",subtitle:"Allocate customer payment to workshop invoice",id:"paymentForm",button:"Post Payment",fields:[{name:"invoiceId",label:"Invoice ID",type:"text",required:true},{name:"amount",label:"Amount",type:"number",required:true},{name:"method",label:"Method",type:"select",options:["cash","card","bank_transfer","cheque"]},{name:"reference",label:"Reference",type:"text"}],method:"POST",idempotent:true,path:b=>{const id=b.invoiceId;delete b.invoiceId;return "/invoices/"+encodeURIComponent(id)+"/payments";}},
 reminders:{title:"Service Reminders",subtitle:"Date and mileage-based customer follow-up",id:"reminderForm",button:"Create Reminder",fields:[{name:"vehicleId",label:"Vehicle ID",type:"text",required:true},{name:"dueAt",label:"Due date",type:"date",required:true},{name:"dueMileage",label:"Due mileage",type:"number"},{name:"message",label:"Message",type:"textarea"}],method:"POST",path:"/service-reminders"},
 delivery:{title:"Vehicle Delivery",subtitle:"Customer receiver and sign-off after quality approval",id:"deliveryForm",button:"Deliver Vehicle",fields:[{name:"jobId",label:"Job card ID",type:"text",required:true},{name:"deliveredTo",label:"Delivered to",type:"text",required:true},{name:"signatureReference",label:"Signature reference",type:"text"},{name:"notes",label:"Notes",type:"textarea"}],method:"POST",path:b=>{const id=b.jobId;delete b.jobId;return "/jobs/"+encodeURIComponent(id)+"/deliver";}},
 settings:{title:"Workshop Settings",subtitle:"Service, estimate and reminder notification rules",id:"ruleForm",button:"Save Rule",fields:[{name:"eventKey",label:"Event key",type:"text",required:true},{name:"channel",label:"Channel",type:"select",options:["in_app","email","sms","whatsapp"]},{name:"daysBefore",label:"Days before",type:"number"},{name:"active",label:"Active",type:"select",options:["true","false"]}],method:"PUT",path:"/notification-rules/workshop"}
};
async function actionPage(c){shell(c.title,c.subtitle);document.getElementById("app").innerHTML=formPanel(c.id,c.button,c.fields,c.button)+'<section class="w-panel"><div class="w-note">All operations are tenant-scoped and protected by role permissions.</div></section>';bind(c.id,c.method,c.path,c.transform||null,null,Boolean(c.idempotent));}
async function parts(){shell("Parts Reservation & Posting","Reserve job parts, validate stock and post consumption");document.getElementById("app").innerHTML=formPanel("reserveForm","Reserve Part",[{name:"jobId",label:"Job card ID",type:"text",required:true},{name:"productId",label:"Product ID",type:"text",required:true},{name:"quantity",label:"Quantity",type:"number",required:true}])+formPanel("postForm","Post Reserved Parts",[{name:"jobId",label:"Job card ID",type:"text",required:true}],"Post Parts");bind("reserveForm","POST",b=>{const id=b.jobId;delete b.jobId;return "/jobs/"+encodeURIComponent(id)+"/parts/reserve";},null,null,true);bind("postForm","POST",b=>"/jobs/"+encodeURIComponent(b.jobId)+"/parts/post",()=>({}),null,true);}
async function reports(){shell("Workshop Reports","Jobs, invoices, receivables, quality and reminders");document.getElementById("app").innerHTML='<section class="w-panel"><button id="run" class="w-btn">Refresh Report</button><pre id="out"></pre></section>';const load=async()=>document.getElementById("out").textContent=JSON.stringify(await request("GET","/reports"),null,2);document.getElementById("run").onclick=load;await load();}
document.addEventListener("DOMContentLoaded",async()=>{try{await guard();if(PAGE==="dashboard")return dashboard();if(PAGE==="vehicles")return vehicles();if(PAGE==="jobs")return jobs();if(PAGE==="parts")return parts();if(PAGE==="reports")return reports();if(ACTIONS[PAGE])return actionPage(ACTIONS[PAGE]);throw Error("Unsupported Workshop page.");}catch(error){if(!document.getElementById("app"))shell("Workshop Application","Unable to open requested module");document.getElementById("app").innerHTML='<section class="w-panel"><div class="w-status error">'+esc(error.message||"Workshop application failed")+"</div></section>";}});
})();
