import type { Request,Response } from "express";
import { prisma } from "../db/prisma.js";
const db:any=prisma; const bid=(r:Request):string=>r.tenant!.businessId!; const ok=(res:Response,data:any,status=200)=>res.status(status).json({ok:true,data}); const fail=(res:Response,m:string,s=400)=>res.status(s).json({ok:false,error:{message:m}});
const key=(r:Request)=>r.header("Idempotency-Key")||r.header("X-Idempotency-Key")||null;
export async function restaurantDashboard(r:Request,res:Response){const b=bid(r); const [tables,open,queued]=await Promise.all([db.restaurantTable.count({where:{businessId:b,active:true}}),db.restaurantOrder.count({where:{businessId:b,status:{in:["open","preparing","ready"]}}}),db.restaurantKitchenTicket.count({where:{businessId:b,status:{in:["queued","preparing"]}}})]); return ok(res,{tables,openOrders:open,kitchenQueue:queued});}
export async function restaurantTables(r:Request,res:Response){return ok(res,await db.restaurantTable.findMany({where:{businessId:bid(r)},orderBy:{tableNo:"asc"}}));}
export async function restaurantTableCreate(r:Request,res:Response){const {tableNo,capacity=2,areaId}=r.body;if(!tableNo)return fail(res,"Table number is required");return ok(res,await db.restaurantTable.create({data:{businessId:bid(r),tableNo:String(tableNo),capacity:Number(capacity),areaId:areaId||null}}),201);}
export async function restaurantMenu(r:Request,res:Response){const b=bid(r);return ok(res,{categories:await db.restaurantMenuCategory.findMany({where:{businessId:b,active:true}}),items:await db.restaurantMenuItem.findMany({where:{businessId:b,active:true}})});}
export async function restaurantCategoryCreate(r:Request,res:Response){if(!r.body.name)return fail(res,"Category name is required");return ok(res,await db.restaurantMenuCategory.create({data:{businessId:bid(r),name:String(r.body.name),kitchenStation:r.body.kitchenStation||null}}),201);}
export async function restaurantMenuItemCreate(r:Request,res:Response){if(!r.body.name||Number(r.body.price)<0)return fail(res,"Valid item name and price are required");return ok(res,await db.restaurantMenuItem.create({data:{businessId:bid(r),name:String(r.body.name),categoryId:r.body.categoryId||null,sku:r.body.sku||null,price:Number(r.body.price),preparationMinutes:Number(r.body.preparationMinutes||10)}}),201);}
export async function restaurantOrders(r:Request,res:Response){return ok(res,await db.restaurantOrder.findMany({where:{businessId:bid(r)},orderBy:{createdAt:"desc"},take:100}));}
export async function restaurantOrderCreate(r:Request,res:Response){const b=bid(r),k=key(r),x=r.body,items=Array.isArray(x.items)?x.items:[];if(!items.length)return fail(res,"At least one order item is required");if(k){const old=await db.restaurantOrder.findFirst({where:{businessId:b,idempotencyKey:k}});if(old)return ok(res,old);}const subtotal=items.reduce((s:any,i:any)=>s+Number(i.quantity||1)*Number(i.unitPrice||0),0),discount=Number(x.discount||0),serviceCharge=Number(x.serviceCharge||0),total=Math.max(0,subtotal-discount+serviceCharge);const order=await db.$transaction(async(tx:any)=>{const no=`RST-${Date.now()}`;const o=await tx.restaurantOrder.create({data:{businessId:b,orderNo:no,orderType:x.orderType||"dine_in",tableId:x.tableId||null,customerName:x.customerName||null,subtotal,discount,serviceCharge,total,idempotencyKey:k}});await tx.restaurantOrderItem.createMany({data:items.map((i:any)=>({businessId:b,orderId:o.id,menuItemId:i.menuItemId||null,itemName:String(i.itemName),quantity:Number(i.quantity||1),unitPrice:Number(i.unitPrice||0),modifiers:i.modifiers||undefined,lineTotal:Number(i.quantity||1)*Number(i.unitPrice||0)}))});await tx.restaurantKitchenTicket.create({data:{businessId:b,orderId:o.id,station:x.station||"main",ticketNo:`KOT-${Date.now()}`}});if(x.tableId)await tx.restaurantTable.updateMany({where:{id:x.tableId,businessId:b},data:{status:"occupied"}});return o;});return ok(res,order,201);}
export async function restaurantOrderStatus(r:Request,res:Response){const allowed=["open","preparing","ready","served","closed","cancelled"];if(!allowed.includes(r.body.status))return fail(res,"Invalid order status");const result=await db.restaurantOrder.updateMany({where:{id:r.params.id,businessId:bid(r)},data:{status:r.body.status,...(r.body.status==="closed"?{closedAt:new Date()}: {})}});if(!result.count)return fail(res,"Order not found",404);return ok(res,{updated:true});}
export async function restaurantKitchen(r:Request,res:Response){return ok(res,await db.restaurantKitchenTicket.findMany({where:{businessId:bid(r),status:{not:"completed"}},orderBy:{createdAt:"asc"},take:100}));}
export async function hardwareDashboard(r:Request,res:Response){const b=bid(r);const [projects,backorders,deliveries,rentals]=await Promise.all([db.customerProject.count({where:{businessId:b,status:"active"}}),db.hardwareBackorder.count({where:{businessId:b,status:"open"}}),db.hardwareStagedDelivery.count({where:{businessId:b,status:{in:["planned","partial"]}}}),db.hardwareRentalContract.count({where:{businessId:b,status:"active"}})]);return ok(res,{activeProjects:projects,openBackorders:backorders,pendingDeliveries:deliveries,activeRentals:rentals});}
export async function hardwareProjects(r:Request,res:Response){return ok(res,await db.customerProject.findMany({where:{businessId:bid(r)},orderBy:{projectCode:"asc"}}));}
export async function hardwareProjectCreate(r:Request,res:Response){const x=r.body;if(!x.customerId||!x.projectCode||!x.name)return fail(res,"Customer, project code and name are required");return ok(res,await db.customerProject.create({data:{businessId:bid(r),customerId:x.customerId,projectCode:x.projectCode,name:x.name,location:x.location||null,creditLimit:Number(x.creditLimit||0)}}),201);}
export async function hardwarePriceLevels(r:Request,res:Response){return ok(res,await db.tradePriceLevel.findMany({where:{businessId:bid(r),active:true}}));}
export async function hardwarePriceLevelCreate(r:Request,res:Response){if(!r.body.name)return fail(res,"Name is required");return ok(res,await db.tradePriceLevel.create({data:{businessId:bid(r),name:r.body.name,discountPercent:Number(r.body.discountPercent||0)}}),201);}
export async function hardwareDeliveries(r:Request,res:Response){return ok(res,await db.hardwareStagedDelivery.findMany({where:{businessId:bid(r)},orderBy:{scheduledDate:"asc"}}));}
export async function hardwareDeliveryCreate(r:Request,res:Response){const x=r.body,k=key(r);if(!x.documentNo||!x.scheduledDate)return fail(res,"Document number and date are required");if(k){const old=await db.hardwareStagedDelivery.findFirst({where:{businessId:bid(r),idempotencyKey:k}});if(old)return ok(res,old);}return ok(res,await db.hardwareStagedDelivery.create({data:{businessId:bid(r),documentNo:x.documentNo,scheduledDate:new Date(x.scheduledDate),projectId:x.projectId||null,notes:x.notes||null,idempotencyKey:k}}),201);}
export async function hardwareBackorders(r:Request,res:Response){return ok(res,await db.hardwareBackorder.findMany({where:{businessId:bid(r),status:"open"},orderBy:{createdAt:"desc"}}));}
export async function hardwareBackorderCreate(r:Request,res:Response){if(!r.body.productId||Number(r.body.quantity)<=0)return fail(res,"Product and positive quantity are required");return ok(res,await db.hardwareBackorder.create({data:{businessId:bid(r),productId:r.body.productId,customerId:r.body.customerId||null,quantity:Number(r.body.quantity)}}),201);}
export async function hardwareRentals(r:Request,res:Response){return ok(res,await db.hardwareRentalContract.findMany({where:{businessId:bid(r)},orderBy:{dueAt:"asc"}}));}
export async function hardwareRentalCreate(r:Request,res:Response){const x=r.body;if(!x.contractNo||!x.customerId||!x.itemDescription||!x.startAt||!x.dueAt)return fail(res,"Complete rental details are required");if(new Date(x.dueAt)<=new Date(x.startAt))return fail(res,"Due date must be after start date");return ok(res,await db.hardwareRentalContract.create({data:{businessId:bid(r),contractNo:x.contractNo,customerId:x.customerId,itemDescription:x.itemDescription,startAt:new Date(x.startAt),dueAt:new Date(x.dueAt),deposit:Number(x.deposit||0)}}),201);}
export async function paintDashboard(r:Request,res:Response){const b=bid(r);const [formulas,queued,ready,failed]=await Promise.all([db.paintFormula.count({where:{businessId:b,active:true}}),db.paintMixJob.count({where:{businessId:b,status:{in:["queued","mixing"]}}}),db.paintMixJob.count({where:{businessId:b,status:"ready"}}),db.paintMixQualityCheck.count({where:{businessId:b,result:"failed"}})]);return ok(res,{activeFormulas:formulas,queuedMixJobs:queued,readyJobs:ready,failedChecks:failed});}
export async function paintBrands(r:Request,res:Response){return ok(res,await db.paintBrand.findMany({where:{businessId:bid(r),active:true}}));}
export async function paintBrandCreate(r:Request,res:Response){if(!r.body.name)return fail(res,"Brand name is required");return ok(res,await db.paintBrand.create({data:{businessId:bid(r),name:r.body.name}}),201);}
export async function paintColors(r:Request,res:Response){return ok(res,await db.paintColor.findMany({where:{businessId:bid(r),active:true},orderBy:{code:"asc"}}));}
export async function paintColorCreate(r:Request,res:Response){if(!r.body.code||!r.body.name)return fail(res,"Color code and name are required");return ok(res,await db.paintColor.create({data:{businessId:bid(r),code:r.body.code,name:r.body.name,collection:r.body.collection||null}}),201);}
export async function paintFormulas(r:Request,res:Response){return ok(res,await db.paintFormula.findMany({where:{businessId:bid(r),active:true},orderBy:{formulaCode:"asc"}}));}
export async function paintFormulaCreate(r:Request,res:Response){const x=r.body,components=Array.isArray(x.components)?x.components:[];if(!x.formulaCode||!x.colorId||!x.productLineId||!x.baseCode||!components.length)return fail(res,"Formula header and normalized components are required");const result=await db.$transaction(async(tx:any)=>{const formula=await tx.paintFormula.create({data:{businessId:bid(r),formulaCode:x.formulaCode,colorId:x.colorId,productLineId:x.productLineId,baseCode:x.baseCode,packSize:Number(x.packSize||1),unit:x.unit||"L"}});const rev=await tx.paintFormulaRevision.create({data:{businessId:bid(r),formulaId:formula.id,revision:1,notes:x.notes||null}});await tx.paintFormulaComponent.createMany({data:components.map((c:any,i:number)=>({businessId:bid(r),revisionId:rev.id,componentCode:c.componentCode,componentName:c.componentName,quantity:Number(c.quantity),unit:c.unit||"g",sequence:i}))});return formula;});return ok(res,result,201);}
export async function paintFormulaRevisionCreate(r:Request,res:Response){const b=bid(r),formula=await db.paintFormula.findFirst({where:{id:r.params.id,businessId:b}});if(!formula)return fail(res,"Formula not found",404);if(Number(r.body.expectedRevision)!==formula.currentRevision)return fail(res,"Formula revision is stale",409);const components=Array.isArray(r.body.components)?r.body.components:[];if(!components.length)return fail(res,"Components are required");const next=formula.currentRevision+1;await db.$transaction(async(tx:any)=>{const rev=await tx.paintFormulaRevision.create({data:{businessId:b,formulaId:formula.id,revision:next,notes:r.body.notes||null}});await tx.paintFormulaComponent.createMany({data:components.map((c:any,i:number)=>({businessId:b,revisionId:rev.id,componentCode:c.componentCode,componentName:c.componentName,quantity:Number(c.quantity),unit:c.unit||"g",sequence:i}))});await tx.paintFormula.update({where:{id:formula.id},data:{currentRevision:next}});});return ok(res,{revision:next},201);}
export async function paintMixJobs(r:Request,res:Response){return ok(res,await db.paintMixJob.findMany({where:{businessId:bid(r)},orderBy:{createdAt:"desc"},take:100}));}
export async function paintMixJobCreate(r:Request,res:Response){const b=bid(r),x=r.body,k=key(r);if(!x.formulaId||Number(x.quantity)<=0||!x.nonReturnableAccepted)return fail(res,"Formula, quantity and custom-mix acknowledgement are required");if(k){const old=await db.paintMixJob.findFirst({where:{businessId:b,idempotencyKey:k}});if(old)return ok(res,old);}const formula=await db.paintFormula.findFirst({where:{id:x.formulaId,businessId:b,active:true}});if(!formula)return fail(res,"Formula not found",404);return ok(res,await db.paintMixJob.create({data:{businessId:b,jobNo:`MIX-${Date.now()}`,formulaId:formula.id,formulaRevision:formula.currentRevision,customerReference:x.customerReference||null,vehicleProjectReference:x.vehicleProjectReference||null,quantity:Number(x.quantity),unit:x.unit||formula.unit,sellingPrice:Number(x.sellingPrice||0),nonReturnableAccepted:true,idempotencyKey:k}}),201);}
export async function paintMixJobStatus(r:Request,res:Response){const allowed=["queued","mixing","quality_check","ready","delivered","cancelled"];if(!allowed.includes(r.body.status))return fail(res,"Invalid mix status");const result=await db.paintMixJob.updateMany({where:{id:r.params.id,businessId:bid(r)},data:{status:r.body.status,...(r.body.status==="ready"?{completedAt:new Date()}: {})}});if(!result.count)return fail(res,"Mix job not found",404);return ok(res,{updated:true});}

export async function restaurantReservations(r:Request,res:Response){return ok(res,await db.restaurantReservation.findMany({where:{businessId:bid(r)},orderBy:{reservedAt:"asc"},take:200}));}
export async function restaurantReservationCreate(r:Request,res:Response){const b=bid(r),x=r.body;if(!x.customerName||!x.reservedAt||Number(x.partySize)<=0)return fail(res,"Customer, reservation time and party size are required");const at=new Date(x.reservedAt);if(Number.isNaN(at.getTime()))return fail(res,"Invalid reservation time");if(x.tableId){const table=await db.restaurantTable.findFirst({where:{id:x.tableId,businessId:b,active:true}});if(!table)return fail(res,"Table not found",404);if(Number(x.partySize)>table.capacity)return fail(res,"Party size exceeds table capacity",409);const start=new Date(at.getTime()-90*60000),end=new Date(at.getTime()+90*60000);const clash=await db.restaurantReservation.findFirst({where:{businessId:b,tableId:x.tableId,status:{in:["booked","seated"]},reservedAt:{gte:start,lte:end}}});if(clash)return fail(res,"Table is already reserved in this time window",409);}return ok(res,await db.restaurantReservation.create({data:{businessId:b,reservationNo:`RSV-${Date.now()}`,tableId:x.tableId||null,customerName:String(x.customerName),phone:x.phone||null,partySize:Number(x.partySize),reservedAt:at,notes:x.notes||null}}),201);}
export async function restaurantReservationStatus(r:Request,res:Response){const allowed=["booked","seated","completed","cancelled","no_show"];if(!allowed.includes(r.body.status))return fail(res,"Invalid reservation status");const q=await db.restaurantReservation.updateMany({where:{id:r.params.id,businessId:bid(r)},data:{status:r.body.status}});if(!q.count)return fail(res,"Reservation not found",404);return ok(res,{updated:true});}
export async function restaurantModifierGroupCreate(r:Request,res:Response){const x=r.body;if(!x.name)return fail(res,"Modifier group name is required");if(Number(x.maxSelect||1)<Number(x.minSelect||0))return fail(res,"Maximum selections cannot be below minimum");return ok(res,await db.restaurantModifierGroup.create({data:{businessId:bid(r),name:String(x.name),required:Boolean(x.required),minSelect:Number(x.minSelect||0),maxSelect:Number(x.maxSelect||1)}}),201);}
export async function restaurantModifierCreate(r:Request,res:Response){const x=r.body;if(!x.groupId||!x.name)return fail(res,"Modifier group and name are required");const group=await db.restaurantModifierGroup.findFirst({where:{id:x.groupId,businessId:bid(r),active:true}});if(!group)return fail(res,"Modifier group not found",404);return ok(res,await db.restaurantModifier.create({data:{businessId:bid(r),groupId:x.groupId,name:String(x.name),priceDelta:Number(x.priceDelta||0)}}),201);}
export async function restaurantRecipeCreate(r:Request,res:Response){const b=bid(r),x=r.body,ings=Array.isArray(x.ingredients)?x.ingredients:[];if(!x.menuItemId||!ings.length)return fail(res,"Menu item and ingredients are required");const menu=await db.restaurantMenuItem.findFirst({where:{id:x.menuItemId,businessId:b,active:true}});if(!menu)return fail(res,"Menu item not found",404);for(const i of ings){const p=await db.product.findFirst({where:{id:i.productId,businessId:b}});if(!p)return fail(res,"Recipe product does not belong to tenant",403);}const rec=await db.$transaction(async(tx:any)=>{const rcp=await tx.restaurantRecipe.upsert({where:{businessId_menuItemId:{businessId:b,menuItemId:x.menuItemId}},update:{yieldQuantity:Number(x.yieldQuantity||1),active:true},create:{businessId:b,menuItemId:x.menuItemId,yieldQuantity:Number(x.yieldQuantity||1)}});await tx.restaurantRecipeIngredient.deleteMany({where:{businessId:b,recipeId:rcp.id}});await tx.restaurantRecipeIngredient.createMany({data:ings.map((i:any)=>({businessId:b,recipeId:rcp.id,productId:i.productId,quantity:Number(i.quantity),unit:i.unit||"unit"}))});return rcp;});return ok(res,rec,201);}
export async function restaurantWastageList(r:Request,res:Response){const from=r.query.from?new Date(String(r.query.from)):undefined,to=r.query.to?new Date(String(r.query.to)):undefined;return ok(res,await db.restaurantWastage.findMany({where:{businessId:bid(r),...(from||to?{postedAt:{...(from?{gte:from}:{}),...(to?{lte:to}:{})}}:{})},orderBy:{postedAt:"desc"},take:200}));}
export async function restaurantWastageCreate(r:Request,res:Response){const b=bid(r),x=r.body,k=key(r);if(!x.productId||Number(x.quantity)<=0||!x.reason)return fail(res,"Product, positive quantity and reason are required");if(k){const old=await db.restaurantWastage.findFirst({where:{businessId:b,idempotencyKey:k}});if(old)return ok(res,old);}const p=await db.product.findFirst({where:{id:x.productId,businessId:b}});if(!p)return fail(res,"Product not found",404);return ok(res,await db.restaurantWastage.create({data:{businessId:b,productId:x.productId,quantity:Number(x.quantity),unit:x.unit||"unit",reason:String(x.reason),postedBy:r.tenant?.userId||null,idempotencyKey:k}}),201);}
export async function restaurantReports(r:Request,res:Response){const b=bid(r),from=r.query.from?new Date(String(r.query.from)):new Date(Date.now()-30*86400000),to=r.query.to?new Date(String(r.query.to)):new Date();const [orders,waste,reservations]=await Promise.all([db.restaurantOrder.aggregate({where:{businessId:b,createdAt:{gte:from,lte:to},status:{not:"cancelled"}},_sum:{total:true},_count:{_all:true}}),db.restaurantWastage.aggregate({where:{businessId:b,postedAt:{gte:from,lte:to},reversedAt:null},_sum:{quantity:true},_count:{_all:true}}),db.restaurantReservation.count({where:{businessId:b,reservedAt:{gte:from,lte:to}}})]);return ok(res,{from,to,orders:orders._count._all,revenue:Number(orders._sum.total||0),wastageRecords:waste._count._all,wastageQuantity:Number(waste._sum.quantity||0),reservations});}

export async function hardwareQuotations(r:Request,res:Response){return ok(res,await db.hardwareQuotation.findMany({where:{businessId:bid(r)},orderBy:{createdAt:"desc"},take:200}));}
export async function hardwareQuotationCreate(r:Request,res:Response){const b=bid(r),x=r.body,k=key(r),items=Array.isArray(x.items)?x.items:[];if(!x.customerId||!items.length)return fail(res,"Customer and quotation items are required");if(k){const old=await db.hardwareQuotation.findFirst({where:{businessId:b,idempotencyKey:k}});if(old)return ok(res,old);}const customer=await db.customer.findFirst({where:{id:x.customerId,businessId:b}});if(!customer)return fail(res,"Customer not found",404);if(x.projectId){const project=await db.customerProject.findFirst({where:{id:x.projectId,businessId:b,customerId:x.customerId}});if(!project)return fail(res,"Project does not belong to customer",403);}let subtotal=0;for(const i of items){const p=await db.product.findFirst({where:{id:i.productId,businessId:b}});if(!p)return fail(res,"Quotation product not found",404);if(Number(i.quantity)<=0||Number(i.unitPrice)<0)return fail(res,"Invalid quotation quantity or price");subtotal+=Number(i.quantity)*Number(i.unitPrice);}const discount=Math.max(0,Number(x.discount||0)),total=Math.max(0,subtotal-discount);const quote=await db.$transaction(async(tx:any)=>{const q=await tx.hardwareQuotation.create({data:{businessId:b,quotationNo:`HQ-${Date.now()}`,customerId:x.customerId,projectId:x.projectId||null,lpoNo:x.lpoNo||null,subtotal,discount,total,validUntil:x.validUntil?new Date(x.validUntil):null,idempotencyKey:k}});await tx.hardwareQuotationItem.createMany({data:items.map((i:any)=>({businessId:b,quotationId:q.id,productId:i.productId,description:String(i.description||"Item"),quantity:Number(i.quantity),unit:i.unit||"piece",cutLength:i.cutLength?Number(i.cutLength):null,unitPrice:Number(i.unitPrice),lineTotal:Number(i.quantity)*Number(i.unitPrice)}))});return q;});return ok(res,quote,201);}
export async function hardwareDeliveryItemsPost(r:Request,res:Response){const b=bid(r),x=r.body,items=Array.isArray(x.items)?x.items:[];const delivery=await db.hardwareStagedDelivery.findFirst({where:{id:r.params.id,businessId:b}});if(!delivery)return fail(res,"Delivery not found",404);if(!items.length)return fail(res,"Delivery items are required");await db.$transaction(async(tx:any)=>{for(const i of items){if(Number(i.deliveredQuantity)<0||Number(i.deliveredQuantity)>Number(i.orderedQuantity))throw new Error("Invalid delivered quantity");await tx.hardwareDeliveryItem.create({data:{businessId:b,deliveryId:delivery.id,productId:i.productId,orderedQuantity:Number(i.orderedQuantity),deliveredQuantity:Number(i.deliveredQuantity),unit:i.unit||"piece"}});if(Number(i.deliveredQuantity)<Number(i.orderedQuantity))await tx.hardwareBackorder.create({data:{businessId:b,customerId:x.customerId||null,productId:i.productId,quantity:Number(i.orderedQuantity)-Number(i.deliveredQuantity)}});}await tx.hardwareStagedDelivery.update({where:{id:delivery.id},data:{status:items.every((i:any)=>Number(i.deliveredQuantity)>=Number(i.orderedQuantity))?"completed":"partial"}});});return ok(res,{posted:true});}
export async function hardwareWarrantyCreate(r:Request,res:Response){const b=bid(r),x=r.body;if(!x.productId||!x.customerId||!x.startsAt||!x.expiresAt)return fail(res,"Product, customer and warranty dates are required");if(new Date(x.expiresAt)<=new Date(x.startsAt))return fail(res,"Warranty expiry must be after start date");const [p,c]=await Promise.all([db.product.findFirst({where:{id:x.productId,businessId:b}}),db.customer.findFirst({where:{id:x.customerId,businessId:b}})]);if(!p||!c)return fail(res,"Product or customer not found",404);return ok(res,await db.hardwareWarrantyRecord.create({data:{businessId:b,productId:x.productId,customerId:x.customerId,serialNo:x.serialNo||null,invoiceNo:x.invoiceNo||null,startsAt:new Date(x.startsAt),expiresAt:new Date(x.expiresAt),notes:x.notes||null}}),201);}
export async function hardwareUnitConversionCreate(r:Request,res:Response){const b=bid(r),x=r.body;if(!x.productId||!x.fromUnit||!x.toUnit||Number(x.factor)<=0)return fail(res,"Product, units and positive factor are required");const p=await db.product.findFirst({where:{id:x.productId,businessId:b}});if(!p)return fail(res,"Product not found",404);return ok(res,await db.hardwareUnitConversion.upsert({where:{businessId_productId_fromUnit_toUnit:{businessId:b,productId:x.productId,fromUnit:x.fromUnit,toUnit:x.toUnit}},update:{factor:Number(x.factor)},create:{businessId:b,productId:x.productId,fromUnit:x.fromUnit,toUnit:x.toUnit,factor:Number(x.factor)}}),201);}
export async function hardwareReports(r:Request,res:Response){const b=bid(r);const [quotes,backorders,deliveries,rentals,warranties]=await Promise.all([db.hardwareQuotation.aggregate({where:{businessId:b,status:{not:"cancelled"}},_sum:{total:true},_count:{_all:true}}),db.hardwareBackorder.aggregate({where:{businessId:b,status:"open"},_sum:{quantity:true},_count:{_all:true}}),db.hardwareStagedDelivery.count({where:{businessId:b,status:{in:["planned","partial"]}}}),db.hardwareRentalContract.count({where:{businessId:b,status:"active"}}),db.hardwareWarrantyRecord.count({where:{businessId:b,status:"active",expiresAt:{gte:new Date()}}})]);return ok(res,{quotations:quotes._count._all,quotationValue:Number(quotes._sum.total||0),openBackorders:backorders._count._all,backorderQuantity:Number(backorders._sum.quantity||0),pendingDeliveries:deliveries,activeRentals:rentals,activeWarranties:warranties});}

export async function paintComponentStocks(r:Request,res:Response){return ok(res,await db.paintComponentStock.findMany({where:{businessId:bid(r),active:true},orderBy:{componentCode:"asc"}}));}
export async function paintComponentStockUpsert(r:Request,res:Response){const b=bid(r),x=r.body;if(!x.componentCode||!x.componentName||!x.unit)return fail(res,"Component code, name and unit are required");return ok(res,await db.paintComponentStock.upsert({where:{businessId_componentCode:{businessId:b,componentCode:x.componentCode}},update:{componentName:x.componentName,quantityOnHand:Number(x.quantityOnHand||0),unit:x.unit,averageCost:Number(x.averageCost||0),minimumStock:Number(x.minimumStock||0),active:true},create:{businessId:b,componentCode:x.componentCode,componentName:x.componentName,quantityOnHand:Number(x.quantityOnHand||0),unit:x.unit,averageCost:Number(x.averageCost||0),minimumStock:Number(x.minimumStock||0)}}),201);}
export async function paintMixPostConsumption(r:Request,res:Response){const b=bid(r),job=await db.paintMixJob.findFirst({where:{id:r.params.id,businessId:b}});if(!job)return fail(res,"Mix job not found",404);if(!["queued","mixing","quality_check"].includes(job.status))return fail(res,"Mix job cannot be posted in current status",409);const formula=await db.paintFormulaRevision.findFirst({where:{businessId:b,formulaId:job.formulaId,revision:job.formulaRevision}});if(!formula)return fail(res,"Formula revision not found",404);const components=await db.paintFormulaComponent.findMany({where:{businessId:b,revisionId:formula.id},orderBy:{sequence:"asc"}});if(!components.length)return fail(res,"Formula has no components",409);const scale=Number(job.quantity);let totalCost=0;await db.$transaction(async(tx:any)=>{for(const c of components){const planned=Number(c.quantity)*scale;const stock=await tx.paintComponentStock.findFirst({where:{businessId:b,componentCode:c.componentCode,active:true}});if(!stock||Number(stock.quantityOnHand)<planned)throw new Error(`Insufficient component stock: ${c.componentCode}`);const cost=planned*Number(stock.averageCost||0);totalCost+=cost;await tx.paintComponentStock.update({where:{id:stock.id},data:{quantityOnHand:{decrement:planned}}});await tx.paintMixConsumption.create({data:{businessId:b,mixJobId:job.id,componentCode:c.componentCode,plannedQuantity:planned,actualQuantity:planned,unit:c.unit,cost}});}await tx.paintMixJob.update({where:{id:job.id},data:{mixCost:totalCost,status:"quality_check"}});});return ok(res,{posted:true,mixCost:totalCost});}
export async function paintQualityCheckCreate(r:Request,res:Response){const b=bid(r),x=r.body;if(!["passed","failed","rework"].includes(x.result))return fail(res,"Invalid quality result");const job=await db.paintMixJob.findFirst({where:{id:r.params.id,businessId:b}});if(!job)return fail(res,"Mix job not found",404);const qc=await db.$transaction(async(tx:any)=>{const q=await tx.paintMixQualityCheck.create({data:{businessId:b,mixJobId:job.id,result:x.result,checkedBy:r.tenant?.userId||null,notes:x.notes||null}});await tx.paintMixJob.update({where:{id:job.id},data:{status:x.result==="passed"?"ready":x.result==="failed"?"cancelled":"mixing",...(x.result==="passed"?{completedAt:new Date()}: {})}});return q;});return ok(res,qc,201);}
export async function paintMixLabel(r:Request,res:Response){const b=bid(r),job=await db.paintMixJob.findFirst({where:{id:r.params.id,businessId:b}});if(!job)return fail(res,"Mix job not found",404);if(job.status!=="ready"&&job.status!=="delivered")return fail(res,"Label is available only after quality approval",409);const label=await db.paintMixLabel.upsert({where:{businessId_mixJobId:{businessId:b,mixJobId:job.id}},update:{printedAt:new Date(),printCount:{increment:1}},create:{businessId:b,mixJobId:job.id,labelNo:`LBL-${job.jobNo}`,printedAt:new Date(),printCount:1}});return ok(res,{...label,jobNo:job.jobNo,quantity:job.quantity,unit:job.unit,customerReference:job.customerReference,nonReturnableAccepted:job.nonReturnableAccepted});}
export async function paintReports(r:Request,res:Response){const b=bid(r),from=r.query.from?new Date(String(r.query.from)):new Date(Date.now()-30*86400000),to=r.query.to?new Date(String(r.query.to)):new Date();const [jobs,cost,failed,stocks]=await Promise.all([db.paintMixJob.count({where:{businessId:b,createdAt:{gte:from,lte:to}}}),db.paintMixJob.aggregate({where:{businessId:b,createdAt:{gte:from,lte:to},status:{in:["ready","delivered"]}},_sum:{mixCost:true,sellingPrice:true}}),db.paintMixQualityCheck.count({where:{businessId:b,result:"failed",checkedAt:{gte:from,lte:to}}}),db.paintComponentStock.findMany({where:{businessId:b,active:true},select:{quantityOnHand:true,minimumStock:true}})]);const low=stocks.filter((x:any)=>Number(x.quantityOnHand)<=Number(x.minimumStock)).length;return ok(res,{from,to,mixJobs:jobs,mixCost:Number(cost._sum.mixCost||0),salesValue:Number(cost._sum.sellingPrice||0),margin:Number(cost._sum.sellingPrice||0)-Number(cost._sum.mixCost||0),failedChecks:failed,lowStockComponents:low});}
const routeIndustry=(r:Request)=>r.originalUrl.includes("/restaurant/")?"restaurant":r.originalUrl.includes("/hardware/")?"hardware":"paint";
export async function releaseCNotificationRules(r:Request,res:Response){return ok(res,await db.releaseCNotificationRule.findMany({where:{businessId:bid(r),industry:routeIndustry(r)},orderBy:{eventKey:"asc"}}));}
export async function releaseCNotificationRuleUpsert(r:Request,res:Response){const industry=routeIndustry(r),x=r.body;if(!["restaurant","hardware","paint"].includes(industry)||!x.eventKey)return fail(res,"Valid industry and event key are required");return ok(res,await db.releaseCNotificationRule.upsert({where:{businessId_industry_eventKey_channel:{businessId:bid(r),industry,eventKey:x.eventKey,channel:x.channel||"in_app"}},update:{daysBefore:Number(x.daysBefore||0),active:x.active!==false},create:{businessId:bid(r),industry,eventKey:x.eventKey,channel:x.channel||"in_app",daysBefore:Number(x.daysBefore||0),active:x.active!==false}}),201);}

export async function restaurantMoveTable(r:Request,res:Response){const b=bid(r),x=r.body;const order=await db.restaurantOrder.findFirst({where:{id:r.params.id,businessId:b,status:{notIn:["closed","cancelled"]}}});if(!order)return fail(res,"Open order not found",404);const table=await db.restaurantTable.findFirst({where:{id:x.tableId,businessId:b,active:true}});if(!table)return fail(res,"Target table not found",404);await db.$transaction(async(tx:any)=>{if(order.tableId)await tx.restaurantTable.updateMany({where:{id:order.tableId,businessId:b},data:{status:"available"}});await tx.restaurantOrder.update({where:{id:order.id},data:{tableId:table.id}});await tx.restaurantTable.update({where:{id:table.id},data:{status:"occupied"}})});return ok(res,{moved:true});}
export async function restaurantCourseAction(r:Request,res:Response){if(!["held","fired"].includes(r.body.courseStatus))return fail(res,"Invalid course action");const q=await db.restaurantOrder.updateMany({where:{id:r.params.id,businessId:bid(r),status:{notIn:["closed","cancelled"]}},data:{courseStatus:r.body.courseStatus}});if(!q.count)return fail(res,"Order not found",404);return ok(res,{updated:true});}
export async function restaurantBillAdjust(r:Request,res:Response){const b=bid(r),x=r.body,tip=Math.max(0,Number(x.tip||0)),discount=Math.max(0,Number(x.discount||0));const o=await db.restaurantOrder.findFirst({where:{id:r.params.id,businessId:b,status:{notIn:["closed","cancelled"]}}});if(!o)return fail(res,"Order not found",404);const total=Math.max(0,Number(o.subtotal)-discount+Number(o.serviceCharge)+tip);return ok(res,await db.restaurantOrder.update({where:{id:o.id},data:{discount,tip,total}}));}
export async function restaurantWastageReverse(r:Request,res:Response){const b=bid(r),w=await db.restaurantWastage.findFirst({where:{id:r.params.id,businessId:b,reversedAt:null}});if(!w)return fail(res,"Active wastage record not found",404);await db.restaurantWastage.update({where:{id:w.id},data:{reversedAt:new Date()}});return ok(res,{reversed:true});}
export async function hardwareRentalReturn(r:Request,res:Response){const b=bid(r),x=r.body,contract=await db.hardwareRentalContract.findFirst({where:{id:r.params.id,businessId:b,status:"active"}});if(!contract)return fail(res,"Active rental contract not found",404);const rentalCharge=Math.max(0,Number(x.rentalCharge||0)),damageCharge=Math.max(0,Number(x.damageCharge||0)),refundAmount=Math.max(0,Number(contract.deposit)-rentalCharge-damageCharge);return ok(res,await db.hardwareRentalContract.update({where:{id:contract.id},data:{returnedAt:new Date(),status:"returned",rentalCharge,damageCharge,refundAmount}}));}
export async function hardwareCreditCheck(r:Request,res:Response){const b=bid(r),project=await db.customerProject.findFirst({where:{id:r.params.id,businessId:b}});if(!project)return fail(res,"Project not found",404);const requested=Math.max(0,Number(r.query.amount||0));return ok(res,{projectId:project.id,creditLimit:Number(project.creditLimit),requested,allowed:requested<=Number(project.creditLimit),remaining:Math.max(0,Number(project.creditLimit)-requested)});}
export async function paintConsumptionAdjust(r:Request,res:Response){const b=bid(r),x=r.body,cons=await db.paintMixConsumption.findFirst({where:{id:r.params.id,businessId:b}});if(!cons)return fail(res,"Consumption record not found",404);const actual=Math.max(0,Number(x.actualQuantity));const stock=await db.paintComponentStock.findFirst({where:{businessId:b,componentCode:cons.componentCode,active:true}});if(!stock)return fail(res,"Component stock not found",404);const delta=actual-Number(cons.actualQuantity);if(delta>0&&Number(stock.quantityOnHand)<delta)return fail(res,"Insufficient stock for adjustment",409);await db.$transaction(async(tx:any)=>{await tx.paintComponentStock.update({where:{id:stock.id},data:{quantityOnHand:{increment:-delta}}});await tx.paintMixConsumption.update({where:{id:cons.id},data:{actualQuantity:actual,cost:actual*Number(stock.averageCost||0)}})});return ok(res,{adjusted:true});}
export async function paintMixReverse(r:Request,res:Response){const b=bid(r),job=await db.paintMixJob.findFirst({where:{id:r.params.id,businessId:b,status:"cancelled"}});if(!job)return fail(res,"Failed/cancelled mix job not found",404);const rows=await db.paintMixConsumption.findMany({where:{businessId:b,mixJobId:job.id}});await db.$transaction(async(tx:any)=>{for(const row of rows){const stock=await tx.paintComponentStock.findFirst({where:{businessId:b,componentCode:row.componentCode}});if(stock)await tx.paintComponentStock.update({where:{id:stock.id},data:{quantityOnHand:{increment:Number(row.actualQuantity)}}});}await tx.paintMixConsumption.deleteMany({where:{businessId:b,mixJobId:job.id}});await tx.paintMixJob.update({where:{id:job.id},data:{status:"queued",mixCost:0}})});return ok(res,{reversed:true});}
export async function paintMixDeliver(r:Request,res:Response){const q=await db.paintMixJob.updateMany({where:{id:r.params.id,businessId:bid(r),status:"ready"},data:{status:"delivered",deliveredAt:new Date()}});if(!q.count)return fail(res,"Ready mix job not found",404);return ok(res,{delivered:true});}
