import type { Request, Response } from "express";
import * as s from "../services/release-ab.service.js";
import { handleError, tenant } from "../utils/http.js";

const run = (fn: (req: Request, businessId: string, userId: string | null) => Promise<any>) => async (req: Request, res: Response) => {
  try {
    const context = tenant(req);
    res.json({ ok: true, data: await fn(req, context.businessId, context.userId) });
  } catch (error) {
    handleError(res, error);
  }
};

export const gymDashboard = run((_r, b) => s.gymDashboard(b));
export const gymMembers = run((r, b) => s.listGymMembers(b, r.query));
export const gymMemberCreate = run((r, b) => s.createGymMember(b, r.body));
export const gymMemberUpdate = run((r, b) => s.updateGymMember(b, r.params.id, r.body));
export const gymMemberArchive = run((r, b) => s.archiveGymMember(b, r.params.id));
export const gymPlans = run((_r, b) => s.listGymPlans(b));
export const gymPlanCreate = run((r, b) => s.createGymPlan(b, r.body));
export const gymMembershipCreate = run((r, b) => s.createGymMembership(b, r.body));
export const schoolDashboard = run((_r, b) => s.schoolDashboard(b));
export const schoolStudents = run((r, b) => s.listSchoolStudents(b, r.query));
export const schoolStudentCreate = run((r, b) => s.createSchoolStudent(b, r.body));
export const schoolClasses = run((_r, b) => s.listSchoolClasses(b));
export const schoolClassCreate = run((r, b) => s.createSchoolClass(b, r.body));
export const schoolEnroll = run((r, b) => s.enrollStudent(b, r.body));
export const clinicDashboard = run((_r, b) => s.clinicDashboard(b));
export const clinicPatients = run((r, b) => s.listClinicPatients(b, r.query));
export const clinicPatientCreate = run((r, b) => s.createClinicPatient(b, r.body));
export const clinicPractitioners = run((_r, b) => s.listPractitioners(b));
export const clinicPractitionerCreate = run((r, b) => s.createPractitioner(b, r.body));
export const clinicAppointments = run((r, b) => s.listAppointments(b, r.query));
export const clinicAppointmentCreate = run((r, b) => s.createAppointment(b, r.body));
export const gymTrainers = run((_r, b) => s.listGymTrainers(b));
export const gymTrainerCreate = run((r, b) => s.createGymTrainer(b, r.body));
export const gymClasses = run((r, b) => s.listGymClasses(b, r.query));
export const gymClassCreate = run((r, b) => s.createGymClass(b, r.body));
export const gymClassBook = run((r, b) => s.bookGymClass(b, r.body));
export const gymCheckIn = run((r, b) => s.gymCheckIn(b, r.body));
export const schoolGuardians = run((_r, b) => s.listSchoolGuardians(b));
export const schoolGuardianCreate = run((r, b) => s.createSchoolGuardian(b, r.body));
export const schoolGuardianLink = run((r, b) => s.linkSchoolGuardian(b, r.body));
export const schoolAttendanceCreate = run((r, b) => s.recordSchoolAttendance(b, r.body));
export const schoolFeeHeadCreate = run((r, b) => s.createSchoolFeeHead(b, r.body));
export const schoolFees = run((r, b) => s.listSchoolFees(b, r.query));
export const schoolFeeCreate = run((r, b) => s.createSchoolFee(b, r.body));
export const schoolFeePay = run((r, b) => s.paySchoolFee(b, r.body, String(r.header("Idempotency-Key") || "")));
export const clinicConsentCreate = run((r, b) => s.createClinicConsent(b, r.body));
export const clinicQueue = run((_r, b) => s.listClinicQueue(b));
export const clinicQueueCreate = run((r, b) => s.clinicQueueCheckIn(b, r.body));
export const clinicQueueUpdate = run((r, b) => s.updateClinicQueue(b, r.params.id, r.body));
export const clinicServices = run((_r, b) => s.listClinicServices(b));
export const clinicServiceCreate = run((r, b) => s.createClinicService(b, r.body));
export const clinicFollowUps = run((_r, b) => s.listClinicFollowUps(b));
export const clinicFollowUpCreate = run((r, b) => s.createClinicFollowUp(b, r.body));
export const gymPrograms = run((_r, b) => s.listGymPrograms(b));
export const gymProgramCreate = run((r, b) => s.createGymProgram(b, r.body));
export const gymProgramEnroll = run((r, b) => s.enrollGymProgram(b, r.body));
export const gymFacilities = run((_r, b) => s.listGymFacilities(b));
export const gymFacilityCreate = run((r, b) => s.createGymFacility(b, r.body));
export const gymFacilityEnroll = run((r, b) => s.assignGymFacility(b, r.body));
export const gymTrainerAssign = run((r, b) => s.assignGymTrainer(b, r.body));
export const gymLockerAssign = run((r, b) => s.assignGymLocker(b, r.body));
export const gymMeasurementCreate = run((r, b) => s.recordGymMeasurement(b, r.body));
export const gymReports = run((_r, b) => s.releaseBReports(b, "gym"));
export const schoolApplicants = run((_r, b) => s.listSchoolApplicants(b));
export const schoolApplicantCreate = run((r, b) => s.createSchoolApplicant(b, r.body));
export const schoolAcademicYearCreate = run((r, b) => s.createAcademicYear(b, r.body));
export const schoolAcademicTermCreate = run((r, b) => s.createAcademicTerm(b, r.body));
export const schoolSubjectCreate = run((r, b) => s.createSchoolSubject(b, r.body));
export const schoolTeacherCreate = run((r, b) => s.createSchoolTeacher(b, r.body));
export const schoolRoomCreate = run((r, b) => s.createSchoolRoom(b, r.body));
export const schoolTimetableCreate = run((r, b) => s.createTimetableEntry(b, r.body));
export const schoolAssessmentCreate = run((r, b) => s.createSchoolAssessment(b, r.body));
export const schoolResultCreate = run((r, b) => s.recordSchoolResult(b, r.body));
export const schoolEmployeeCreate = run((r, b) => s.createSchoolEmployee(b, r.body));
export const schoolReports = run((_r, b) => s.releaseBReports(b, "school"));
export const clinicSpecialtyCreate = run((r, b) => s.createClinicSpecialty(b, r.body));
export const clinicEncounterCreate = run((r, b) => s.createClinicEncounter(b, r.body));
export const clinicEncounterUpdate = run((r, b) => s.updateClinicEncounter(b, r.params.id, r.body));
export const clinicServiceRequestCreate = run((r, b) => s.createClinicServiceRequest(b, r.body));
export const clinicMedicationRequestCreate = run((r, b, u) => s.createClinicMedicationRequest(b, r.body, u || "system"));
export const clinicReports = run((_r, b) => s.releaseBReports(b, "clinic"));
