/* Live PostgreSQL report renderer.  Deliberately isolated from legacy localStorage report scripts. */
(function () {
  'use strict';
  var U = window.AxtorPage, active = 'daily-sales', last = null;
  var countKeys = new Set(['qty', 'invoices', 'customers', 'returns', 'entries', 'products']);
  var percentageKeys = new Set(['achievement', 'margin']);
  function option(el, rows, label) { U.setOptions(el, rows || [], label, 'id'); }
  function dates() { var mode = U.value('#reportDateRange'), now = new Date(), from = '', to = now.toISOString().slice(0, 10); if (mode === 'today') from = to; else if (mode === 'this_week') { var d = new Date(now); d.setDate(d.getDate() - 6); from = d.toISOString().slice(0, 10); } else if (mode === 'this_month') from = now.toISOString().slice(0, 7) + '-01'; else if (mode === 'this_year') from = now.getFullYear() + '-01-01'; else if (mode === 'custom') { from = U.value('#reportDateFrom'); to = U.value('#reportDateTo'); } return { from: from, to: to }; }
  function params() { var d = dates(), p = new URLSearchParams(); Object.entries({ from: d.from, to: d.to, month: U.value('#reportMonth'), year: U.value('#reportYear'), branchId: U.value('#reportBranch'), customerId: U.value('#reportCustomer'), productId: U.value('#reportProduct'), supplierId: U.value('#reportSupplier'), salesmanId: U.value('#reportSalesman') }).forEach(function (entry) { if (entry[1]) p.set(entry[0], entry[1]); }); return p.toString(); }
  function display(value, key) { if (typeof value !== 'number') return value == null ? '-' : String(value); if (percentageKeys.has(key)) return value.toFixed(2) + '%'; if (countKeys.has(key)) return key === 'qty' ? value.toFixed(3).replace(/\.000$/, '') : String(value); return 'QAR ' + U.money(value); }
  function csvCell(value) { var text = String(value == null ? '' : value); return /^[=+\-@]/.test(text) ? "'" + text : text; }
  function exportCsv() { if (!last) return; var columns = last.columns || [], rows = last.rows || []; var csv = [columns.map(function (c) { return JSON.stringify(c.label); }).join(',')].concat(rows.map(function (row) { return columns.map(function (c) { return JSON.stringify(csvCell(row[c.key])); }).join(','); })).join('\r\n'); var blob = new Blob([csv], { type: 'text/csv;charset=utf-8' }); var link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = (last.title || 'axtor-report').replace(/[^a-z0-9]+/gi, '-').replace(/^-|-$/g, '').toLowerCase() + '.csv'; document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(link.href); }
  async function run() { last = U.data(await U.api().apiGet('/api/v1/reports/' + active + '?' + params())); var title = U.q('#activeReportTitle'); if (title) title.textContent = last.title; var meta = U.q('#activeReportMeta'); if (meta) meta.textContent = 'Live PostgreSQL data • ' + new Date().toLocaleString(); var badge = U.q('#activeReportBadge'); if (badge) badge.textContent = last.title.replace(' Report', ''); var sum = U.q('#activeReportSummary'); if (sum) sum.innerHTML = (last.summary || []).map(function (x) { return '<div class="col-md-3"><div class="mini-stat"><span class="small text-muted">' + U.esc(x.label) + '</span><strong class="d-block">' + U.esc(display(x.value, String(x.label || '').toLowerCase().replace(/\s+/g, ''))) + '</strong></div></div>'; }).join(''); var h = U.q('#activeReportHead'), b = U.q('#activeReportBody'), columns = last.columns || []; if (h) h.innerHTML = '<tr>' + columns.map(function (x) { return '<th>' + U.esc(x.label) + '</th>'; }).join('') + '</tr>'; if (b) b.innerHTML = (last.rows || []).length ? last.rows.map(function (row) { return '<tr>' + columns.map(function (c) { return '<td>' + U.esc(display(row[c.key], c.key)) + '</td>'; }).join('') + '</tr>'; }).join('') : U.emptyRow(columns.length || 1); }
  U.run(async function () { var o = U.data(await U.api().apiGet('/api/v1/reports/options')); option(U.q('#reportBranch'), o.branches, 'name'); option(U.q('#reportCustomer'), o.customers, 'name'); option(U.q('#reportProduct'), o.products, function (x) { return (x.sku ? x.sku + ' — ' : '') + x.name; }); option(U.q('#reportSupplier'), o.suppliers, 'name'); option(U.q('#reportSalesman'), o.salesmen, 'name'); document.addEventListener('click', function (e) { var card = e.target.closest('[data-report-id]'); if (!card) return; e.preventDefault(); active = card.dataset.reportId; run().catch(U.error); }); U.bind('#applyReportFilters', 'click', function () { run().catch(U.error); }); U.bind('#resetReportFilters', 'click', function () { U.qa('#reportFilterPanel input,#reportFilterPanel select').forEach(function (x) { x.value = x.id === 'reportDateRange' ? 'this_month' : ''; }); run().catch(U.error); }); U.bind('#copyActiveReport', 'click', exportCsv); U.bind('#printActiveReport', 'click', function () { window.print(); }); U.bind('#reportTopPrintBtn', 'click', function () { window.print(); }); await run(); });
}());
