import { Router } from "express";
import { requireAuth } from "../middleware/auth.middleware.js";
import { requireIndustry } from "../middleware/industry-guard.middleware.js";
import { requireIndustryWritePermission } from "../middleware/industry-permission.middleware.js";
import * as c from "../controllers/release-c.controller.js";
export const restaurantRouter=Router(); restaurantRouter.use(requireAuth,requireIndustry("restaurant"),requireIndustryWritePermission("restaurant")); restaurantRouter.get("/dashboard",c.restaurantDashboard); restaurantRouter.get("/tables",c.restaurantTables); restaurantRouter.post("/tables",c.restaurantTableCreate); restaurantRouter.get("/menu",c.restaurantMenu); restaurantRouter.post("/menu/categories",c.restaurantCategoryCreate); restaurantRouter.post("/menu/items",c.restaurantMenuItemCreate); restaurantRouter.get("/orders",c.restaurantOrders); restaurantRouter.post("/orders",c.restaurantOrderCreate); restaurantRouter.patch("/orders/:id/status",c.restaurantOrderStatus); restaurantRouter.get("/kitchen",c.restaurantKitchen);
export const hardwareRouter=Router(); hardwareRouter.use(requireAuth,requireIndustry("hardware","hardware_paint"),requireIndustryWritePermission("hardware","hardware_paint")); hardwareRouter.get("/dashboard",c.hardwareDashboard); hardwareRouter.get("/projects",c.hardwareProjects); hardwareRouter.post("/projects",c.hardwareProjectCreate); hardwareRouter.get("/price-levels",c.hardwarePriceLevels); hardwareRouter.post("/price-levels",c.hardwarePriceLevelCreate); hardwareRouter.get("/deliveries",c.hardwareDeliveries); hardwareRouter.post("/deliveries",c.hardwareDeliveryCreate); hardwareRouter.get("/backorders",c.hardwareBackorders); hardwareRouter.post("/backorders",c.hardwareBackorderCreate); hardwareRouter.get("/rentals",c.hardwareRentals); hardwareRouter.post("/rentals",c.hardwareRentalCreate);
export const paintRouter=Router(); paintRouter.use(requireAuth,requireIndustry("paint"),requireIndustryWritePermission("paint")); paintRouter.get("/dashboard",c.paintDashboard); paintRouter.get("/brands",c.paintBrands); paintRouter.post("/brands",c.paintBrandCreate); paintRouter.get("/colors",c.paintColors); paintRouter.post("/colors",c.paintColorCreate); paintRouter.get("/formulas",c.paintFormulas); paintRouter.post("/formulas/:id/revisions",c.paintFormulaRevisionCreate); paintRouter.get("/mix-jobs",c.paintMixJobs); paintRouter.post("/mix-jobs",c.paintMixJobCreate); paintRouter.patch("/mix-jobs/:id/status",c.paintMixJobStatus);
restaurantRouter.get("/reservations",c.restaurantReservations); restaurantRouter.post("/reservations",c.restaurantReservationCreate); restaurantRouter.patch("/reservations/:id/status",c.restaurantReservationStatus); restaurantRouter.post("/modifier-groups",c.restaurantModifierGroupCreate); restaurantRouter.post("/modifiers",c.restaurantModifierCreate); restaurantRouter.post("/recipes",c.restaurantRecipeCreate); restaurantRouter.get("/wastage",c.restaurantWastageList); restaurantRouter.post("/wastage",c.restaurantWastageCreate); restaurantRouter.get("/reports",c.restaurantReports); restaurantRouter.get("/notification-rules",c.releaseCNotificationRules); restaurantRouter.put("/notification-rules",c.releaseCNotificationRuleUpsert);
hardwareRouter.get("/quotations",c.hardwareQuotations); hardwareRouter.post("/quotations",c.hardwareQuotationCreate); hardwareRouter.post("/deliveries/:id/items",c.hardwareDeliveryItemsPost); hardwareRouter.post("/warranties",c.hardwareWarrantyCreate); hardwareRouter.post("/unit-conversions",c.hardwareUnitConversionCreate); hardwareRouter.get("/reports",c.hardwareReports); hardwareRouter.get("/notification-rules",c.releaseCNotificationRules); hardwareRouter.put("/notification-rules",c.releaseCNotificationRuleUpsert);
paintRouter.get("/component-stock",c.paintComponentStocks); paintRouter.put("/component-stock",c.paintComponentStockUpsert); paintRouter.post("/mix-jobs/:id/post-consumption",c.paintMixPostConsumption); paintRouter.post("/mix-jobs/:id/quality-checks",c.paintQualityCheckCreate); paintRouter.post("/mix-jobs/:id/label",c.paintMixLabel); paintRouter.get("/reports",c.paintReports); paintRouter.get("/notification-rules",c.releaseCNotificationRules); paintRouter.put("/notification-rules",c.releaseCNotificationRuleUpsert);

restaurantRouter.patch("/orders/:id/move-table",c.restaurantMoveTable); restaurantRouter.patch("/orders/:id/course",c.restaurantCourseAction); restaurantRouter.patch("/orders/:id/bill",c.restaurantBillAdjust); restaurantRouter.post("/wastage/:id/reverse",c.restaurantWastageReverse);
hardwareRouter.post("/rentals/:id/return",c.hardwareRentalReturn); hardwareRouter.get("/projects/:id/credit-check",c.hardwareCreditCheck);
paintRouter.patch("/consumptions/:id",c.paintConsumptionAdjust); paintRouter.post("/mix-jobs/:id/reverse",c.paintMixReverse); paintRouter.post("/mix-jobs/:id/deliver",c.paintMixDeliver);
