import { Router } from "express";
import { requireAuth } from "../middleware/auth.middleware.js";
import { requireIndustry } from "../middleware/industry-guard.middleware.js";
import { requireAnyPermission } from "../middleware/permission.middleware.js";
import * as c from "../controllers/release-d.controller.js";

const permission = (...names: string[]) => requireAnyPermission(...names);

export const furnitureRouter = Router();
furnitureRouter.use(requireAuth, requireIndustry("furniture"));
const furnitureOrderWrite = permission("industry.furniture.order.manage", "industry.furniture.orders.manage");
const furnitureProductionWrite = permission("industry.furniture.production.manage");
const furniturePaymentWrite = permission("industry.furniture.payment.create", "industry.furniture.payments.manage");
const furnitureDeliveryWrite = permission("industry.furniture.delivery.manage", "industry.furniture.installation.manage");
const furnitureApprovalWrite = permission("industry.furniture.approval.manage", "industry.furniture.design.manage");
const furnitureWarrantyWrite = permission("industry.furniture.warranty.manage", "industry.furniture.returns.manage");
const furnitureProcurementWrite = permission("industry.furniture.procurement.manage", "purchases.manage");
const furnitureSettingsWrite = permission("industry.furniture.settings.manage", "furniture.settings.manage");
furnitureRouter.get("/dashboard", c.furnitureDashboard);
furnitureRouter.get("/orders", c.furnitureOrders);
furnitureRouter.post("/orders", furnitureOrderWrite, c.furnitureOrderCreate);
furnitureRouter.post("/orders/:id/measurements", furnitureOrderWrite, c.furnitureMeasurements);
furnitureRouter.patch("/production-stages/:id", furnitureProductionWrite, c.furnitureStageUpdate);
furnitureRouter.post("/orders/:id/payments", furniturePaymentWrite, c.furniturePayment);
furnitureRouter.post("/deliveries", furnitureDeliveryWrite, c.furnitureDeliveryCreate);
furnitureRouter.post("/orders/:id/approvals", furnitureApprovalWrite, c.furnitureApprovalCreate);
furnitureRouter.post("/installations", furnitureDeliveryWrite, c.furnitureInstallationCreate);
furnitureRouter.patch("/installations/:id/complete", furnitureDeliveryWrite, c.furnitureInstallationComplete);
furnitureRouter.post("/installations/:id/signoff", furnitureDeliveryWrite, c.furnitureInstallationSignoff);
furnitureRouter.post("/warranty-claims", furnitureWarrantyWrite, c.furnitureWarrantyClaimCreate);
furnitureRouter.patch("/warranty-claims/:id/resolve", furnitureWarrantyWrite, c.furnitureWarrantyClaimResolve);
furnitureRouter.post("/procurements", furnitureProcurementWrite, c.furnitureProcurementCreate);
furnitureRouter.post("/returns", furnitureWarrantyWrite, c.furnitureReturnCreate);
furnitureRouter.patch("/returns/:id/resolve", furnitureWarrantyWrite, c.furnitureReturnResolve);
furnitureRouter.get("/reports", c.furnitureReports);
furnitureRouter.get("/notification-rules/:industry", c.releaseDNotificationRules);
furnitureRouter.put("/notification-rules/:industry", furnitureSettingsWrite, c.releaseDNotificationRuleUpsert);

export const workshopRouter = Router();
workshopRouter.use(requireAuth, requireIndustry("workshop", "garage"));
const workshopVehicleWrite = permission("industry.workshop.vehicle.manage", "industry.workshop.vehicles.manage");
const workshopInspectionWrite = permission("industry.workshop.inspection.manage");
const workshopEstimateWrite = permission("industry.workshop.estimate.manage", "industry.workshop.estimates.manage");
const workshopJobWrite = permission("industry.workshop.job.manage", "industry.workshop.jobs.manage");
const workshopPartsWrite = permission("industry.workshop.parts.manage", "inventory.manage");
const workshopQualityWrite = permission("industry.workshop.quality.manage");
const workshopBillingWrite = permission("industry.workshop.billing.manage", "sales_documents.create");
const workshopPaymentWrite = permission("industry.workshop.payment.create", "payments.receive");
const workshopReminderWrite = permission("industry.workshop.reminder.manage", "notifications.manage");
const workshopSettingsWrite = permission("industry.workshop.settings.manage", "workshop.settings.manage");
workshopRouter.get("/dashboard", c.workshopDashboard);
workshopRouter.get("/vehicles", c.workshopVehicles);
workshopRouter.post("/vehicles", workshopVehicleWrite, c.workshopVehicleCreate);
workshopRouter.post("/inspections", workshopInspectionWrite, c.workshopInspectionCreate);
workshopRouter.post("/estimates", workshopEstimateWrite, c.workshopEstimateCreate);
workshopRouter.get("/jobs", c.workshopJobs);
workshopRouter.post("/jobs", workshopJobWrite, c.workshopJobCreate);
workshopRouter.post("/jobs/:id/parts/reserve", workshopPartsWrite, c.workshopPartReserve);
workshopRouter.post("/jobs/:id/parts/post", workshopPartsWrite, c.workshopPostReservedParts);
workshopRouter.post("/jobs/:id/quality-checks", workshopQualityWrite, c.workshopQualityCheckCreate);
workshopRouter.post("/jobs/:id/invoices", workshopBillingWrite, c.workshopInvoiceCreate);
workshopRouter.post("/invoices/:id/payments", workshopPaymentWrite, c.workshopPaymentCreate);
workshopRouter.post("/jobs/:id/deliver", workshopJobWrite, c.workshopVehicleDeliver);
workshopRouter.post("/service-reminders", workshopReminderWrite, c.workshopReminderCreate);
workshopRouter.get("/reports", c.workshopReports);
workshopRouter.get("/notification-rules/:industry", c.releaseDNotificationRules);
workshopRouter.put("/notification-rules/:industry", workshopSettingsWrite, c.releaseDNotificationRuleUpsert);

export const wholesaleRouter = Router();
wholesaleRouter.use(requireAuth, requireIndustry("wholesale", "distribution"));
const wholesalePricingWrite = permission("industry.wholesale.pricing.manage", "industry.wholesale.price_lists.manage");
const wholesaleOrderWrite = permission("industry.wholesale.order.manage", "industry.wholesale.orders.manage");
const wholesaleAllocationWrite = permission("industry.wholesale.allocation.manage", "inventory.manage");
const wholesaleDispatchWrite = permission("industry.wholesale.dispatch.manage", "industry.wholesale.delivery.manage");
const wholesaleCollectionWrite = permission("industry.wholesale.collection.manage", "payments.receive");
const wholesaleCreditWrite = permission("industry.wholesale.credit.manage", "customers.credit.manage");
const wholesaleSettingsWrite = permission("industry.wholesale.settings.manage", "wholesale.settings.manage");
wholesaleRouter.get("/dashboard", c.wholesaleDashboard);
wholesaleRouter.get("/price-lists", c.wholesalePriceLists);
wholesaleRouter.post("/price-lists", wholesalePricingWrite, c.wholesalePriceListCreate);
wholesaleRouter.post("/price-list-assignments", wholesalePricingWrite, c.wholesaleAssignPriceList);
wholesaleRouter.post("/unit-conversions", wholesalePricingWrite, c.wholesaleUnitConversionCreate);
wholesaleRouter.get("/orders", c.wholesaleOrders);
wholesaleRouter.post("/orders", wholesaleOrderWrite, c.wholesaleOrderCreate);
wholesaleRouter.post("/orders/:id/allocate", wholesaleAllocationWrite, c.wholesaleAllocate);
wholesaleRouter.post("/packing-lists", wholesaleAllocationWrite, c.wholesalePackingCreate);
wholesaleRouter.post("/packing-lists/detailed", wholesaleAllocationWrite, c.wholesalePackingCreateDetailed);
wholesaleRouter.post("/routes", wholesaleDispatchWrite, c.wholesaleRouteCreate);
wholesaleRouter.post("/dispatches", wholesaleDispatchWrite, c.wholesaleDispatchCreate);
wholesaleRouter.patch("/dispatches/:id/deliver", wholesaleDispatchWrite, c.wholesaleDispatchDeliver);
wholesaleRouter.post("/dispatches/:id/proof-of-delivery", wholesaleDispatchWrite, c.wholesaleProofOfDelivery);
wholesaleRouter.post("/collections", wholesaleCollectionWrite, c.wholesaleCollectionCreate);
wholesaleRouter.put("/credit-profiles", wholesaleCreditWrite, c.wholesaleCreditProfileUpsert);
wholesaleRouter.get("/customers/:customerId/credit-check", c.wholesaleCreditCheck);
wholesaleRouter.get("/receivables/ageing", c.wholesaleAgeing);
wholesaleRouter.get("/reports", c.wholesaleReports);
wholesaleRouter.get("/notification-rules/:industry", c.releaseDNotificationRules);
wholesaleRouter.put("/notification-rules/:industry", wholesaleSettingsWrite, c.releaseDNotificationRuleUpsert);
