import { Router } from "express";
import { requireAuth } from "../middleware/auth.middleware.js";
import { requireIndustry } from "../middleware/industry-guard.middleware.js";
import { requireIndustryWritePermission } from "../middleware/industry-permission.middleware.js";
import * as c from "../controllers/release-ab.controller.js";
import * as f from "../controllers/release-b-final.controller.js";

export { default as clinicRouter } from "./clinic.routes.js";
export { default as gymRouter } from "./gym.routes.js";

export const schoolRouter = Router();
schoolRouter.use(requireAuth, requireIndustry("school", "education"), requireIndustryWritePermission("school", "education"));
schoolRouter.get("/dashboard", c.schoolDashboard);
schoolRouter.get("/students", c.schoolStudents);
schoolRouter.post("/students", c.schoolStudentCreate);
schoolRouter.get("/classes", c.schoolClasses);
schoolRouter.post("/classes", c.schoolClassCreate);
schoolRouter.post("/enrollments", c.schoolEnroll);
schoolRouter.get("/guardians", c.schoolGuardians);
schoolRouter.post("/guardians", c.schoolGuardianCreate);
schoolRouter.post("/student-guardians", c.schoolGuardianLink);
schoolRouter.post("/attendance", c.schoolAttendanceCreate);
schoolRouter.post("/fee-heads", c.schoolFeeHeadCreate);
schoolRouter.get("/fees", c.schoolFees);
schoolRouter.post("/fees", c.schoolFeeCreate);
schoolRouter.post("/fee-payments", c.schoolFeePay);
schoolRouter.get("/applicants", c.schoolApplicants);
schoolRouter.post("/applicants", c.schoolApplicantCreate);
schoolRouter.post("/academic-years", c.schoolAcademicYearCreate);
schoolRouter.post("/academic-terms", c.schoolAcademicTermCreate);
schoolRouter.post("/subjects", c.schoolSubjectCreate);
schoolRouter.post("/teachers", c.schoolTeacherCreate);
schoolRouter.post("/rooms", c.schoolRoomCreate);
schoolRouter.post("/timetable", c.schoolTimetableCreate);
schoolRouter.post("/assessments", c.schoolAssessmentCreate);
schoolRouter.post("/results", c.schoolResultCreate);
schoolRouter.post("/employees", c.schoolEmployeeCreate);
schoolRouter.get("/reports/summary", c.schoolReports);
schoolRouter.post("/fee-adjustments", f.schoolAdjustment);
schoolRouter.post("/payroll-runs", f.schoolPayroll);
schoolRouter.get("/reports/filtered", f.schoolFilteredReport);
schoolRouter.get("/notification-rules", f.schoolRules);
schoolRouter.put("/notification-rules", f.schoolRuleSave);
