import {Router} from 'express'; import {requireAuth} from '../middleware/auth.middleware.js'; import {requireIndustry} from '../middleware/industry-guard.middleware.js'; import {requireIndustryWritePermission} from '../middleware/industry-permission.middleware.js'; import * as c from '../controllers/release-ab.controller.js'; import * as f from '../controllers/release-b-final.controller.js';
export const gymRouter=Router(); gymRouter.use(requireAuth,requireIndustry('gym'),requireIndustryWritePermission('gym')); gymRouter.get('/dashboard',c.gymDashboard); gymRouter.get('/members',c.gymMembers); gymRouter.post('/members',c.gymMemberCreate); gymRouter.patch('/members/:id',c.gymMemberUpdate); gymRouter.delete('/members/:id',c.gymMemberArchive); gymRouter.get('/membership-plans',c.gymPlans); gymRouter.post('/membership-plans',c.gymPlanCreate); gymRouter.post('/memberships',c.gymMembershipCreate); gymRouter.get('/trainers',c.gymTrainers); gymRouter.post('/trainers',c.gymTrainerCreate); gymRouter.get('/classes',c.gymClasses); gymRouter.post('/classes',c.gymClassCreate); gymRouter.post('/class-bookings',c.gymClassBook); gymRouter.post('/check-ins',c.gymCheckIn);
export const schoolRouter=Router(); schoolRouter.use(requireAuth,requireIndustry('school','education'),requireIndustryWritePermission('school','education')); schoolRouter.get('/dashboard',c.schoolDashboard); schoolRouter.get('/students',c.schoolStudents); schoolRouter.post('/students',c.schoolStudentCreate); schoolRouter.get('/classes',c.schoolClasses); schoolRouter.post('/classes',c.schoolClassCreate); schoolRouter.post('/enrollments',c.schoolEnroll); schoolRouter.get('/guardians',c.schoolGuardians); schoolRouter.post('/guardians',c.schoolGuardianCreate); schoolRouter.post('/student-guardians',c.schoolGuardianLink); schoolRouter.post('/attendance',c.schoolAttendanceCreate); schoolRouter.post('/fee-heads',c.schoolFeeHeadCreate); schoolRouter.get('/fees',c.schoolFees); schoolRouter.post('/fees',c.schoolFeeCreate); schoolRouter.post('/fee-payments',c.schoolFeePay);
export const clinicRouter=Router(); clinicRouter.use(requireAuth,requireIndustry('clinic'),requireIndustryWritePermission('clinic')); clinicRouter.get('/dashboard',c.clinicDashboard); clinicRouter.get('/patients',c.clinicPatients); clinicRouter.post('/patients',c.clinicPatientCreate); clinicRouter.get('/practitioners',c.clinicPractitioners); clinicRouter.post('/practitioners',c.clinicPractitionerCreate); clinicRouter.get('/appointments',c.clinicAppointments); clinicRouter.post('/appointments',c.clinicAppointmentCreate); clinicRouter.post('/consents',c.clinicConsentCreate); clinicRouter.get('/queue',c.clinicQueue); clinicRouter.post('/queue',c.clinicQueueCreate); clinicRouter.patch('/queue/:id',c.clinicQueueUpdate); clinicRouter.get('/services',c.clinicServices); clinicRouter.post('/services',c.clinicServiceCreate); clinicRouter.get('/follow-ups',c.clinicFollowUps); clinicRouter.post('/follow-ups',c.clinicFollowUpCreate);
gymRouter.get('/programs',c.gymPrograms); gymRouter.post('/programs',c.gymProgramCreate); gymRouter.post('/program-enrollments',c.gymProgramEnroll); gymRouter.get('/facilities',c.gymFacilities); gymRouter.post('/facilities',c.gymFacilityCreate); gymRouter.post('/facility-enrollments',c.gymFacilityEnroll); gymRouter.post('/trainer-assignments',c.gymTrainerAssign); gymRouter.post('/locker-assignments',c.gymLockerAssign); gymRouter.post('/measurements',c.gymMeasurementCreate); gymRouter.get('/reports/summary',c.gymReports);
schoolRouter.get('/applicants',c.schoolApplicants); schoolRouter.post('/applicants',c.schoolApplicantCreate); schoolRouter.post('/academic-years',c.schoolAcademicYearCreate); schoolRouter.post('/academic-terms',c.schoolAcademicTermCreate); schoolRouter.post('/subjects',c.schoolSubjectCreate); schoolRouter.post('/teachers',c.schoolTeacherCreate); schoolRouter.post('/rooms',c.schoolRoomCreate); schoolRouter.post('/timetable',c.schoolTimetableCreate); schoolRouter.post('/assessments',c.schoolAssessmentCreate); schoolRouter.post('/results',c.schoolResultCreate); schoolRouter.post('/employees',c.schoolEmployeeCreate); schoolRouter.get('/reports/summary',c.schoolReports);
clinicRouter.post('/specialties',c.clinicSpecialtyCreate); clinicRouter.post('/encounters',c.clinicEncounterCreate); clinicRouter.patch('/encounters/:id',c.clinicEncounterUpdate); clinicRouter.post('/service-requests',c.clinicServiceRequestCreate); clinicRouter.post('/medication-requests',c.clinicMedicationRequestCreate); clinicRouter.get('/reports/summary',c.clinicReports);

gymRouter.post('/membership-payments',f.gymPayment); gymRouter.post('/membership-renewals',f.gymRenew); gymRouter.get('/reports/filtered',f.gymFilteredReport); gymRouter.get('/notification-rules',f.gymRules); gymRouter.put('/notification-rules',f.gymRuleSave);
schoolRouter.post('/fee-adjustments',f.schoolAdjustment); schoolRouter.post('/payroll-runs',f.schoolPayroll); schoolRouter.get('/reports/filtered',f.schoolFilteredReport); schoolRouter.get('/notification-rules',f.schoolRules); schoolRouter.put('/notification-rules',f.schoolRuleSave);
clinicRouter.post('/invoices',f.clinicInvoice); clinicRouter.post('/payments',f.clinicPayment); clinicRouter.get('/reports/filtered',f.clinicFilteredReport); clinicRouter.get('/notification-rules',f.clinicRules); clinicRouter.put('/notification-rules',f.clinicRuleSave);
