import { Router } from "express";
import { requireAuth } from "../middleware/auth.middleware.js";
import { requireIndustry } from "../middleware/industry-guard.middleware.js";
import { requireAnyPermission } from "../middleware/permission.middleware.js";
import * as c from "../controllers/release-c.controller.js";
import { bootstrapPaintIndustry } from "../controllers/paint-bootstrap.controller.js";

const permission = (...names: string[]) => requireAnyPermission(...names);

export const restaurantRouter = Router();
restaurantRouter.use(requireAuth, requireIndustry("restaurant"));
const restaurantTableWrite = permission("industry.restaurant.table.manage", "industry.restaurant.tables.manage");
const restaurantMenuWrite = permission("industry.restaurant.menu.manage");
const restaurantOrderWrite = permission("industry.restaurant.order.create", "industry.restaurant.orders.manage");
const restaurantKitchenWrite = permission("industry.restaurant.kitchen.manage", "industry.restaurant.orders.manage");
const restaurantReservationWrite = permission("industry.restaurant.reservation.manage", "industry.restaurant.reservations.manage");
const restaurantInventoryWrite = permission("industry.restaurant.inventory.manage", "industry.restaurant.wastage.manage");
const restaurantSettingsWrite = permission("industry.restaurant.settings.manage", "restaurant.settings.manage");
restaurantRouter.get("/dashboard", c.restaurantDashboard);
restaurantRouter.get("/tables", c.restaurantTables);
restaurantRouter.post("/tables", restaurantTableWrite, c.restaurantTableCreate);
restaurantRouter.get("/menu", c.restaurantMenu);
restaurantRouter.post("/menu/categories", restaurantMenuWrite, c.restaurantCategoryCreate);
restaurantRouter.post("/menu/items", restaurantMenuWrite, c.restaurantMenuItemCreate);
restaurantRouter.get("/orders", c.restaurantOrders);
restaurantRouter.post("/orders", restaurantOrderWrite, c.restaurantOrderCreate);
restaurantRouter.patch("/orders/:id/status", restaurantOrderWrite, c.restaurantOrderStatus);
restaurantRouter.patch("/orders/:id/move-table", restaurantOrderWrite, c.restaurantMoveTable);
restaurantRouter.patch("/orders/:id/course", restaurantKitchenWrite, c.restaurantCourseAction);
restaurantRouter.patch("/orders/:id/bill", restaurantOrderWrite, c.restaurantBillAdjust);
restaurantRouter.get("/kitchen", c.restaurantKitchen);
restaurantRouter.get("/reservations", c.restaurantReservations);
restaurantRouter.post("/reservations", restaurantReservationWrite, c.restaurantReservationCreate);
restaurantRouter.patch("/reservations/:id/status", restaurantReservationWrite, c.restaurantReservationStatus);
restaurantRouter.post("/modifier-groups", restaurantMenuWrite, c.restaurantModifierGroupCreate);
restaurantRouter.post("/modifiers", restaurantMenuWrite, c.restaurantModifierCreate);
restaurantRouter.post("/recipes", restaurantMenuWrite, c.restaurantRecipeCreate);
restaurantRouter.get("/wastage", c.restaurantWastageList);
restaurantRouter.post("/wastage", restaurantInventoryWrite, c.restaurantWastageCreate);
restaurantRouter.post("/wastage/:id/reverse", restaurantInventoryWrite, c.restaurantWastageReverse);
restaurantRouter.get("/reports", c.restaurantReports);
restaurantRouter.get("/notification-rules", c.releaseCNotificationRules);
restaurantRouter.put("/notification-rules", restaurantSettingsWrite, c.releaseCNotificationRuleUpsert);

export const hardwareRouter = Router();
hardwareRouter.use(requireAuth, requireIndustry("hardware", "hardware_paint"));
const hardwareProjectWrite = permission("industry.hardware.project.manage", "industry.hardware.projects.manage", "industry.hardware_paint.project.manage");
const hardwarePricingWrite = permission("industry.hardware.pricing.manage", "industry.hardware.trade_pricing.manage");
const hardwareDeliveryWrite = permission("industry.hardware.delivery.manage", "industry.hardware.deliveries.manage");
const hardwareBackorderWrite = permission("industry.hardware.backorder.manage", "industry.hardware.inventory.manage");
const hardwareRentalWrite = permission("industry.hardware.rental.manage", "industry.hardware.rentals.manage");
const hardwareQuotationWrite = permission("industry.hardware.quotation.manage", "sales_documents.create");
const hardwareWarrantyWrite = permission("industry.hardware.warranty.manage");
const hardwareSettingsWrite = permission("industry.hardware.settings.manage", "hardware.settings.manage");
hardwareRouter.get("/dashboard", c.hardwareDashboard);
hardwareRouter.get("/projects", c.hardwareProjects);
hardwareRouter.post("/projects", hardwareProjectWrite, c.hardwareProjectCreate);
hardwareRouter.get("/price-levels", c.hardwarePriceLevels);
hardwareRouter.post("/price-levels", hardwarePricingWrite, c.hardwarePriceLevelCreate);
hardwareRouter.get("/deliveries", c.hardwareDeliveries);
hardwareRouter.post("/deliveries", hardwareDeliveryWrite, c.hardwareDeliveryCreate);
hardwareRouter.post("/deliveries/:id/items", hardwareDeliveryWrite, c.hardwareDeliveryItemsPost);
hardwareRouter.get("/backorders", c.hardwareBackorders);
hardwareRouter.post("/backorders", hardwareBackorderWrite, c.hardwareBackorderCreate);
hardwareRouter.get("/rentals", c.hardwareRentals);
hardwareRouter.post("/rentals", hardwareRentalWrite, c.hardwareRentalCreate);
hardwareRouter.post("/rentals/:id/return", hardwareRentalWrite, c.hardwareRentalReturn);
hardwareRouter.get("/quotations", c.hardwareQuotations);
hardwareRouter.post("/quotations", hardwareQuotationWrite, c.hardwareQuotationCreate);
hardwareRouter.post("/warranties", hardwareWarrantyWrite, c.hardwareWarrantyCreate);
hardwareRouter.post("/unit-conversions", hardwarePricingWrite, c.hardwareUnitConversionCreate);
hardwareRouter.get("/projects/:id/credit-check", c.hardwareCreditCheck);
hardwareRouter.get("/reports", c.hardwareReports);
hardwareRouter.get("/notification-rules", c.releaseCNotificationRules);
hardwareRouter.put("/notification-rules", hardwareSettingsWrite, c.releaseCNotificationRuleUpsert);

export const paintRouter = Router();
paintRouter.use(requireAuth, requireIndustry("paint", "hardware_paint"));
const paintCatalogueWrite = permission("industry.paint.catalogue.manage", "industry.paint.formula.manage", "industry.hardware_paint.formula.manage");
const paintMixWrite = permission("industry.paint.mix_job.manage", "industry.paint.mix_jobs.manage", "industry.hardware_paint.mix_job.manage");
const paintStockWrite = permission("industry.paint.component_stock.manage", "inventory.manage");
const paintQualityWrite = permission("industry.paint.quality.manage", "industry.paint.mix_job.manage");
const paintSettingsWrite = permission("industry.paint.settings.manage", "paint.settings.manage");
paintRouter.get("/dashboard", c.paintDashboard);
paintRouter.post("/bootstrap", paintSettingsWrite, bootstrapPaintIndustry);
paintRouter.get("/brands", c.paintBrands);
paintRouter.post("/brands", paintCatalogueWrite, c.paintBrandCreate);
paintRouter.get("/colors", c.paintColors);
paintRouter.post("/colors", paintCatalogueWrite, c.paintColorCreate);
paintRouter.get("/formulas", c.paintFormulas);
paintRouter.post("/formulas", paintCatalogueWrite, c.paintFormulaCreate);
paintRouter.post("/formulas/:id/revisions", paintCatalogueWrite, c.paintFormulaRevisionCreate);
paintRouter.get("/mix-jobs", c.paintMixJobs);
paintRouter.post("/mix-jobs", paintMixWrite, c.paintMixJobCreate);
paintRouter.patch("/mix-jobs/:id/status", paintMixWrite, c.paintMixJobStatus);
paintRouter.get("/component-stock", c.paintComponentStocks);
paintRouter.put("/component-stock", paintStockWrite, c.paintComponentStockUpsert);
paintRouter.post("/mix-jobs/:id/post-consumption", paintStockWrite, c.paintMixPostConsumption);
paintRouter.post("/mix-jobs/:id/quality-checks", paintQualityWrite, c.paintQualityCheckCreate);
paintRouter.post("/mix-jobs/:id/label", paintMixWrite, c.paintMixLabel);
paintRouter.patch("/consumptions/:id", paintStockWrite, c.paintConsumptionAdjust);
paintRouter.post("/mix-jobs/:id/reverse", paintMixWrite, c.paintMixReverse);
paintRouter.post("/mix-jobs/:id/deliver", paintMixWrite, c.paintMixDeliver);
paintRouter.get("/reports", c.paintReports);
paintRouter.get("/notification-rules", c.releaseCNotificationRules);
paintRouter.put("/notification-rules", paintSettingsWrite, c.releaseCNotificationRuleUpsert);
